Repository moondance-labs/tanssi, pull requests merged in 2023-11, with the labels that each got.

#311 Increment runtimes version to 400
  container-chains/templates/frontier/runtime/src/lib.rs
  container-chains/templates/simple/runtime/src/lib.rs
  runtime/dancebox/src/lib.rs
Labels: B0-silent, D3-trivial

#312 Girazoki ci improvement
  .github/workflows/enforce-pr-labels.yml
  .github/workflows/prepare-binary.yml
  .github/workflows/publish-runtime.yml
  tools/github/generate-release-body.ts
Labels: B0-silent, D3-trivial

#313 add inflation rewards smoke test
  test/suites/smoke-test/test-inflation-rewards.ts
  test/suites/smoke-test/test-randomness-consistency.ts
  test/util/block.ts
Labels: B0-silent, D3-trivial, I4-tests 🎯

#317 fix parachain bond smoke test cal
  test/suites/smoke-test/test-inflation-rewards.ts
Labels: B0-silent, not-breaking

#319 Prefund pallet accounts in genesis to ensure they are always alive
  node/src/chain_spec.rs
  test/suites/dev-tanssi/staking/test_staking_rewards_balanced.ts
  test/suites/dev-tanssi/staking/test_staking_rewards_non_balanced.ts
Labels: B0-silent, not-breaking

#318 Fix typo in zombienet config
  test/configs/zombieTanssiRotation.json
  test/moonwall.config.json
Labels: B0-silent, not-breaking

#320 profile production when building runtime
  scripts/build-runtime-srtool.sh
  tools/benchmarking.sh
Labels: B0-silent

#323 fix benchmarking claim manual rewards
  pallets/pooled-staking/src/benchmarking.rs
  tools/benchmarking.sh
Labels: B0-silent

#324 Fix rounding in inflation test
  runtime/dancebox/tests/integration_test.rs
Labels: B0-silent, not-breaking

#314 Add pallet services payment to runtime
  Cargo.lock
  Cargo.toml
  node/src/chain_spec.rs
  pallets/collator-assignment/src/benchmarking.rs
  pallets/collator-assignment/src/lib.rs
  pallets/collator-assignment/src/mock.rs
  pallets/collator-assignment/src/weights.rs
  pallets/services-payment/Cargo.toml
  pallets/services-payment/src/benchmarks.rs
  pallets/services-payment/src/lib.rs
  pallets/services-payment/src/mock.rs
  pallets/services-payment/src/tests.rs
  pallets/services-payment/src/weights.rs
  primitives/traits/Cargo.toml
  primitives/traits/src/lib.rs
  runtime/dancebox/Cargo.toml
  runtime/dancebox/src/lib.rs
  runtime/dancebox/src/migrations.rs
  runtime/dancebox/tests/common/mod.rs
  runtime/dancebox/tests/integration_test.rs
  test/suites/dev-tanssi/services-payment/test_services_payment.ts
  test/suites/para/test_tanssi_containers.ts
  typescript-api/src/dancebox/interfaces/augment-api-errors.ts
  typescript-api/src/dancebox/interfaces/augment-api-events.ts
  typescript-api/src/dancebox/interfaces/augment-api-query.ts
  typescript-api/src/dancebox/interfaces/augment-api-tx.ts
  typescript-api/src/dancebox/interfaces/lookup.ts
  typescript-api/src/dancebox/interfaces/registry.ts
  typescript-api/src/dancebox/interfaces/types-lookup.ts
Labels: B7-runtimenoteworthy, breaking

#326 Remove session key tests
  test/suites/dev-tanssi/session-keys/test_remove_session_key_invulnerables.ts
  test/suites/dev-tanssi/session-keys/test_remove_session_key_staking.ts
Labels: B0-silent, I4-tests 🎯

#330 generate covidr
  .github/workflows/coverage.yml
Labels: a0-pleasereview, B0-silent

#329 rework coverage
  .github/scripts/coverage-report.py
  .github/workflows/coverage.yml
Labels: a0-pleasereview, B0-silent, not-breaking

#332 author-noting: check all the digests, not only the first one
  pallets/author-noting/src/lib.rs
  pallets/author-noting/src/tests.rs
Labels: B7-runtimenoteworthy, not-breaking

#337 Disable coverage gathering during cargo build
  .github/workflows/coverage.yml
Labels: B0-silent, ci, not-breaking

#328 adapt to dancekit
  Cargo.lock
  Cargo.toml
  client/orchestrator-chain-interface/Cargo.toml
  client/orchestrator-chain-interface/src/lib.rs
  container-chains/pallets/authorities-noting/Cargo.toml
  container-chains/pallets/authorities-noting/src/benchmarks.rs
  container-chains/pallets/authorities-noting/src/lib.rs
  container-chains/pallets/authorities-noting/src/mock.rs
  container-chains/pallets/authorities-noting/src/mock_proof.rs
  container-chains/pallets/authorities-noting/src/tests.rs
  container-chains/pallets/authorities-noting/src/weights.rs
  container-chains/primitives/authorities-noting-inherent/Cargo.toml
  container-chains/primitives/authorities-noting-inherent/src/client_side.rs
  container-chains/primitives/authorities-noting-inherent/src/lib.rs
  container-chains/primitives/authorities-noting-inherent/src/mock.rs
  container-chains/primitives/authorities-noting-inherent/src/tests.rs
  container-chains/primitives/xcm/Cargo.toml
  container-chains/primitives/xcm/src/lib.rs
  node/Cargo.toml
  node/src/container_chain_spawner.rs
  node/src/service.rs
  pallets/author-noting/Cargo.toml
  pallets/author-noting/src/lib.rs
  pallets/author-noting/src/tests.rs
  pallets/authority-assignment/Cargo.toml
  pallets/authority-assignment/src/lib.rs
  pallets/authority-assignment/src/mock.rs
  pallets/authority-assignment/src/tests.rs
  pallets/collator-assignment/Cargo.toml
  pallets/collator-assignment/src/lib.rs
  pallets/inflation-rewards/Cargo.toml
  pallets/inflation-rewards/src/lib.rs
  pallets/inflation-rewards/src/mock.rs
  pallets/pooled-staking/Cargo.toml
  primitives/author-noting-inherent/Cargo.toml
  primitives/author-noting-inherent/src/client_side.rs
  primitives/author-noting-inherent/src/tests.rs
  primitives/chain-state-snapshot/Cargo.toml
  primitives/chain-state-snapshot/src/lib.rs
  primitives/collator-assignment/Cargo.toml
  primitives/collator-assignment/src/lib.rs
  primitives/core/Cargo.toml
  primitives/core/src/lib.rs
  runtime/dancebox/Cargo.toml
  runtime/dancebox/src/lib.rs
  runtime/dancebox/tests/integration_test.rs
  test-sproof-builder/Cargo.toml
  test-sproof-builder/src/lib.rs
  typescript-api/src/dancebox/interfaces/augment-api-query.ts
  typescript-api/src/dancebox/interfaces/lookup.ts
  typescript-api/src/dancebox/interfaces/registry.ts
  typescript-api/src/dancebox/interfaces/types-lookup.ts
Labels: a0-pleasereview, B7-runtimenoteworthy, breaking

#322 Add precompiles and tests to evm template
  .github/workflows/coverage.yml
  Cargo.lock
  Cargo.toml
  container-chains/templates/frontier/node/src/chain_spec.rs
  container-chains/templates/frontier/runtime/Cargo.toml
  container-chains/templates/frontier/runtime/src/lib.rs
  container-chains/templates/frontier/runtime/src/migrations.rs
  container-chains/templates/frontier/runtime/src/precompiles.rs
  runtime/dancebox/Cargo.toml
  test/contracts/solidity/Batch.sol
  test/contracts/solidity/CallPermit.sol
  test/contracts/solidity/CallPermitDemo.sol
  test/contracts/solidity/ERC20.sol
  test/contracts/solidity/SmartContractPrecompileCallTests.sol
  test/contracts/solidity/XcmUtils.sol
  test/helpers/eth-transactions.ts
  test/helpers/index.ts
  test/helpers/xcm.ts
  test/moonwall.config.json
  test/suites/dev-frontier-template/test-precompiles/test-precompile-batch.ts
  test/suites/dev-frontier-template/test-precompiles/test-precompile-call-permit.ts
  test/suites/dev-frontier-template/test-precompiles/test-precompile-erc20.ts
  test/suites/dev-frontier-template/test-precompiles/test-precompile-smart-contract-call.ts
  test/suites/dev-frontier-template/test-precompiles/test-precompile-xcm-utils.ts
  test/suites/rt-upgrade-chopsticks/test-upgrade-chain.ts
  test/suites/rt-upgrade-zombienet/test-upgrade-chain.ts
  test/util/ethereum.ts
Labels: a0-pleasereview, B7-runtimenoteworthy, breaking

#344 Set latest authorities data weight annotation & tests
  Cargo.lock
  pallets/author-noting/src/lib.rs
  test/suites/dev-frontier-template/weights/test_set_latest_authorities_data.ts
  test/suites/dev-tanssi/weights/test_set_latest_author_data_weight.ts
  typescript-api/src/dancebox/interfaces/augment-api-query.ts
Labels: B0-silent

#346 fix smoket test randomness
  test/suites/smoke-test/test-randomness-consistency.ts
Labels: a0-pleasereview, B0-silent, I4-tests 🎯

#347 Fix smoke test again
  test/suites/smoke-test/test-randomness-consistency.ts
Labels: B0-silent, I4-tests 🎯
