Repository moondance-labs/tanssi, pull requests merged in 2023-12, with the labels that each got.

#355 refactor coverage job to be more configurable
  .github/workflow-templates/typescript-tests-dev-frontier-template/action.yml
  .github/workflow-templates/typescript-tests-moonwall/action.yml
  .github/workflows/coverage.yml
Labels: a0-pleasereview, B0-silent, I4-tests 🎯

#338 Give free credits once on container chain register
  pallets/registrar/src/lib.rs
  pallets/registrar/src/mock.rs
  pallets/registrar/src/tests.rs
  pallets/registrar/src/weights.rs
  pallets/services-payment/src/benchmarks.rs
  pallets/services-payment/src/lib.rs
  pallets/services-payment/src/weights.rs
  runtime/dancebox/src/lib.rs
  runtime/dancebox/src/migrations.rs
  runtime/dancebox/tests/integration_test.rs
  test/suites/dev-tanssi/registrar/test_registrar_register.ts
  typescript-api/src/dancebox/interfaces/augment-api-query.ts
  typescript-api/src/dancebox/interfaces/augment-api-tx.ts
  typescript-api/src/dancebox/interfaces/lookup.ts
  typescript-api/src/dancebox/interfaces/types-lookup.ts
Labels: B7-runtimenoteworthy, breaking

#342 Upgrade 1.3.0
  Cargo.lock
  Cargo.toml
  client/node-common/src/service.rs
  container-chains/templates/frontier/runtime/src/lib.rs
  container-chains/templates/frontier/runtime/src/xcm_config.rs
  container-chains/templates/simple/runtime/src/lib.rs
  container-chains/templates/simple/runtime/src/xcm_config.rs
  pallets/inflation-rewards/src/mock.rs
  pallets/invulnerables/src/mock.rs
  pallets/pooled-staking/src/benchmarking.rs
  pallets/pooled-staking/src/calls.rs
  pallets/pooled-staking/src/lib.rs
  pallets/pooled-staking/src/mock.rs
  pallets/registrar/src/mock.rs
  pallets/services-payment/src/mock.rs
  runtime/dancebox/Cargo.toml
  runtime/dancebox/src/lib.rs
  runtime/dancebox/src/migrations.rs
  runtime/dancebox/src/xcm_config.rs
  runtime/dancebox/tests/common/xcm/foreign_signed_based_sovereign.rs
  runtime/dancebox/tests/common/xcm/foreign_sovereigns.rs
  runtime/dancebox/tests/common/xcm/mocknets.rs
  runtime/dancebox/tests/integration_test.rs
  test/suites/common/proxy/test-proxy-balances.ts
  test/suites/common/proxy/test-proxy-cancel.ts
  test/suites/common/proxy/test-proxy.ts
  test/suites/common/test-maintenance/test-maintenance-dmp-queue.ts
  test/suites/common/test-maintenance/test-maintenance-mode.ts
  test/suites/common/test-maintenance/test-maintenance-xcm-queue.ts
  test/suites/common/test_basic.ts
  test/suites/common/xcm/test-mock-dmp-transact.ts
  test/suites/common/xcm/test-mock-hrmp-transact.ts
  test/suites/dev-frontier-template/test-balance/test-balance-existential.ts
  test/suites/dev-frontier-template/test-precompiles/test-precompile-erc20.ts
  test/suites/dev-frontier-template/test-precompiles/test-precompile-xcm-utils.ts
  test/suites/dev-tanssi/fees/test_fee_balance_transfer.ts
  test/suites/dev-tanssi/services-payment/test_services_payment.ts
  test/suites/dev-tanssi/session-keys/test_remove_session_key_staking.ts
  test/suites/dev-tanssi/staking/test_staking_rewards_balanced.ts
  test/suites/dev-tanssi/staking/test_staking_rewards_non_balanced.ts
  test/suites/dev-tanssi/staking/test_staking_session.ts
  test/suites/rt-upgrade-chopsticks/test-upgrade-chain.ts
  test/util/xcm.ts
  typescript-api/src/dancebox/interfaces/augment-api-consts.ts
  typescript-api/src/dancebox/interfaces/augment-api-events.ts
  typescript-api/src/dancebox/interfaces/augment-api-query.ts
  typescript-api/src/dancebox/interfaces/augment-api-tx.ts
  typescript-api/src/dancebox/interfaces/lookup.ts
  typescript-api/src/dancebox/interfaces/registry.ts
  typescript-api/src/dancebox/interfaces/types-lookup.ts
Labels: a0-pleasereview, B7-runtimenoteworthy, breaking

#349 Add .gitattributes file to hide typescript-api in diffs
  .gitattributes
Labels: B0-silent

#357 Add TxPause pallet to dancebox runtime
  Cargo.lock
  Cargo.toml
  container-chains/templates/frontier/node/src/chain_spec.rs
  container-chains/templates/frontier/runtime/Cargo.toml
  container-chains/templates/frontier/runtime/src/lib.rs
  container-chains/templates/simple/node/src/chain_spec.rs
  container-chains/templates/simple/runtime/Cargo.toml
  container-chains/templates/simple/runtime/src/lib.rs
  node/src/chain_spec.rs
  runtime/dancebox/Cargo.toml
  runtime/dancebox/src/lib.rs
  test/suites/common/tx-pause/test_maintenance_mode.ts
  test/suites/common/tx-pause/test_pause.ts
  typescript-api/src/dancebox/interfaces/augment-api-consts.ts
  typescript-api/src/dancebox/interfaces/augment-api-errors.ts
  typescript-api/src/dancebox/interfaces/augment-api-events.ts
  typescript-api/src/dancebox/interfaces/augment-api-query.ts
  typescript-api/src/dancebox/interfaces/augment-api-tx.ts
  typescript-api/src/dancebox/interfaces/lookup.ts
  typescript-api/src/dancebox/interfaces/registry.ts
  typescript-api/src/dancebox/interfaces/types-lookup.ts
Labels: B7-runtimenoteworthy, breaking

#359 Ignore invalid bootnodes when starting container chain
  node/src/cli.rs
  node/src/container_chain_spawner.rs
Labels: B5-clientnoteworthy, not-breaking

#341 Implement pallet-data-preservers
  Cargo.lock
  Cargo.toml
  node/src/chain_spec.rs
  pallets/data-preservers/Cargo.toml
  pallets/data-preservers/src/benchmarks.rs
  pallets/data-preservers/src/lib.rs
  pallets/data-preservers/src/mock.rs
  pallets/data-preservers/src/tests.rs
  pallets/data-preservers/src/weights.rs
  pallets/registrar/src/benchmarks.rs
  pallets/registrar/src/lib.rs
  pallets/registrar/src/mock.rs
  pallets/registrar/src/tests.rs
  pallets/registrar/src/weights.rs
  pallets/services-payment/src/mock.rs
  runtime/dancebox/Cargo.toml
  runtime/dancebox/src/lib.rs
  runtime/dancebox/src/migrations.rs
  runtime/dancebox/tests/common/mod.rs
  runtime/dancebox/tests/integration_test.rs
  test/scripts/sudoRegisterPara.ts
  test/suites/dev-tanssi/registrar/test_registrar_deregister.ts
  test/suites/dev-tanssi/registrar/test_registrar_register.ts
  test/suites/para/test_tanssi_containers.ts
  typescript-api/src/dancebox/interfaces/augment-api-errors.ts
  typescript-api/src/dancebox/interfaces/augment-api-events.ts
  typescript-api/src/dancebox/interfaces/augment-api-query.ts
  typescript-api/src/dancebox/interfaces/augment-api-tx.ts
  typescript-api/src/dancebox/interfaces/lookup.ts
  typescript-api/src/dancebox/interfaces/registry.ts
  typescript-api/src/dancebox/interfaces/types-lookup.ts
Labels: B7-runtimenoteworthy, breaking

#362 Force container chains to use paritydb
  node/src/container_chain_spawner.rs
  test/suites/keep-db/test_restart_keep_db.ts
  test/suites/rotation-para/test_rotation.ts
  test/suites/warp-sync/test_warp_sync.ts
Labels: B5-clientnoteworthy, not-breaking

#366 fix frontier template pending
  Cargo.lock
  client/consensus/Cargo.toml
  client/consensus/src/lib.rs
  client/consensus/src/manual_seal.rs
  client/node-common/src/service.rs
  container-chains/templates/frontier/node/Cargo.toml
  container-chains/templates/frontier/node/src/rpc/mod.rs
  container-chains/templates/frontier/node/src/service.rs
  container-chains/templates/simple/node/src/service.rs
  test/suites/dev-frontier-template/test-eth-block/test-eth-block-pending.ts
Labels: B5-clientnoteworthy, not-breaking

#368 Add zepter toml linter to CI
  .cargo/zepter.yaml
  .github/workflows/release.yml
  Cargo.lock
  container-chains/templates/frontier/node/Cargo.toml
  container-chains/templates/frontier/runtime/Cargo.toml
  container-chains/templates/simple/node/Cargo.toml
  container-chains/templates/simple/runtime/Cargo.toml
  node/Cargo.toml
  pallets/author-noting/Cargo.toml
  pallets/authority-assignment/Cargo.toml
  pallets/authority-mapping/Cargo.toml
  pallets/collator-assignment/Cargo.toml
  pallets/collator-assignment/rpc/runtime-api/Cargo.toml
  pallets/configuration/Cargo.toml
  pallets/data-preservers/Cargo.toml
  pallets/inflation-rewards/Cargo.toml
  pallets/initializer/Cargo.toml
  pallets/invulnerables/Cargo.toml
  pallets/pooled-staking/Cargo.toml
  pallets/registrar/Cargo.toml
  pallets/registrar/rpc/runtime-api/Cargo.toml
  pallets/services-payment/Cargo.toml
  primitives/author-noting-inherent/Cargo.toml
  primitives/consensus/Cargo.toml
  primitives/container-chain-genesis-data/Cargo.toml
  primitives/maths/Cargo.toml
  primitives/traits/Cargo.toml
  runtime/dancebox/Cargo.toml
Labels: B0-silent, not-breaking

#358 Add Registrar proxy type
  Cargo.lock
  container-chains/templates/frontier/node/src/rpc/mod.rs
  container-chains/templates/frontier/runtime/src/lib.rs
  container-chains/templates/simple/runtime/src/lib.rs
  pallets/registrar/src/lib.rs
  runtime/dancebox/src/lib.rs
  runtime/dancebox/src/migrations.rs
  runtime/dancebox/tests/common/mod.rs
  runtime/dancebox/tests/integration_test.rs
  test/suites/dev-tanssi/registrar/test_registrar_proxy.ts
  typescript-api/src/dancebox/interfaces/augment-api-tx.ts
  typescript-api/src/dancebox/interfaces/lookup.ts
  typescript-api/src/dancebox/interfaces/types-lookup.ts
Labels: a0-pleasereview, B7-runtimenoteworthy, not-breaking

#369 Add toml-maid to CI and run it
  .github/workflows/release.yml
  Cargo.toml
  container-chains/templates/frontier/node/Cargo.toml
  container-chains/templates/frontier/runtime/Cargo.toml
  container-chains/templates/simple/node/Cargo.toml
  container-chains/templates/simple/runtime/Cargo.toml
  node/Cargo.toml
  pallets/author-noting/Cargo.toml
  pallets/authority-assignment/Cargo.toml
  pallets/authority-mapping/Cargo.toml
  pallets/collator-assignment/Cargo.toml
  pallets/collator-assignment/rpc/runtime-api/Cargo.toml
  pallets/configuration/Cargo.toml
  pallets/data-preservers/Cargo.toml
  pallets/inflation-rewards/Cargo.toml
  pallets/initializer/Cargo.toml
  pallets/invulnerables/Cargo.toml
  pallets/pooled-staking/Cargo.toml
  pallets/registrar/Cargo.toml
  pallets/registrar/rpc/runtime-api/Cargo.toml
  pallets/services-payment/Cargo.toml
  primitives/author-noting-inherent/Cargo.toml
  primitives/consensus/Cargo.toml
  primitives/container-chain-genesis-data/Cargo.toml
  primitives/maths/Cargo.toml
  primitives/traits/Cargo.toml
  runtime/dancebox/Cargo.toml
  toml-maid.toml
Labels: B0-silent, not-breaking

#373 Packages Update
  pnpm-lock.yaml
  test/moonwall.config.json
  test/package.json
  test/suites/keep-db/test_restart_keep_db.ts
  test/suites/rotation-para/test_rotation.ts
  test/suites/rt-upgrade-chopsticks/test-upgrade-chain.ts
  test/suites/rt-upgrade-zombienet/test-upgrade-chain.ts
  test/suites/warp-sync/test_warp_sync.ts
  test/util/ethereum.ts
  typescript-api/package.json
  typescript-api/src/dancebox/interfaces/augment-api-rpc.ts
  typescript-api/src/dancebox/interfaces/augment-types.ts
  typescript-api/src/flashbox/interfaces/augment-api-rpc.ts
  typescript-api/src/flashbox/interfaces/augment-types.ts
Labels: B0-silent, D2-notlive

#374 Moonwall minor fixes
  pnpm-lock.yaml
  test/.gitignore
  test/moonwall.config.json
  test/package.json
  test/pnpm-lock.yaml
Labels: B0-silent, D2-notlive

#354 add only chopsticks for tempalte
  .github/workflows/release.yml
  pnpm-lock.yaml
  test/configs/frontierContainer.yml
  test/moonwall.config.json
  test/suites/rt-upgrade-chopsticks-frontier-template/test-upgrade-chain.ts
  test/suites/rt-upgrade-chopsticks-orchestrator/test-upgrade-chain.ts
Labels: a0-pleasereview, B0-silent, I4-tests 🎯
