Repository moondance-labs/tanssi, pull requests merged in 2024-08, with the labels that each got.

#641 Uncomment westend relay encoder tests
  Cargo.lock
  runtime/relay-encoder/Cargo.toml
  runtime/relay-encoder/src/westend.rs
Labels: B0-silent, D2-notlive, not-breaking

#640 Increase authoring duration to 2s and block weight limit x4
  client/service-container-chain/src/service.rs
  container-chains/runtime-templates/frontier/src/lib.rs
  container-chains/runtime-templates/simple/src/lib.rs
  node/src/service.rs
  runtime/dancebox/src/lib.rs
  runtime/flashbox/src/lib.rs
Labels: B5-clientnoteworthy, B7-runtimenoteworthy, breaking, D3-trivial

#643 Add manual seal support for starlight
  Cargo.lock
  Cargo.toml
  solo-chains/client/cli/Cargo.toml
  solo-chains/client/cli/src/command.rs
  solo-chains/node/tanssi-relay-service/Cargo.toml
  solo-chains/node/tanssi-relay-service/src/dev_service.rs
  solo-chains/node/tanssi-relay-service/src/lib.rs
  test/suites/dev-tanssi-relay/balances/test_balances.ts
  test/suites/dev-tanssi-relay/test-basics.ts
Labels: enhancement, B0-silent, D3-trivial, not-breaking

#646 Fix log upload in case of zombienet test failure
  .github/workflow-templates/zombienet-tests/action.yml
Labels: B0-silent, D2-notlive, not-breaking

#629 Core assignation wired to collatorAssignment
  Cargo.lock
  pallets/registrar/src/lib.rs
  pnpm-lock.yaml
  solo-chains/client/cli/src/cli.rs
  solo-chains/client/cli/src/command.rs
  solo-chains/node/tanssi-relay-service/Cargo.toml
  solo-chains/node/tanssi-relay-service/src/chain_spec.rs
  solo-chains/runtime/starlight/Cargo.toml
  solo-chains/runtime/starlight/src/genesis_config_presets.rs
  solo-chains/runtime/starlight/src/lib.rs
  solo-chains/runtime/starlight/src/tests/collator_assignment_tests.rs
  solo-chains/runtime/starlight/src/tests/common/mod.rs
  solo-chains/runtime/starlight/src/tests/core_scheduling_tests.rs
  solo-chains/runtime/starlight/src/tests/mod.rs
  solo-chains/runtime/starlight/src/tests/session_keys.rs
  test/configs/zombieStarlight.json
  test/moonwall.config.json
  test/package.json
  test/scripts/build-spec-starlight-plus-dancebox-container.sh
Labels: B7-runtimenoteworthy, breaking, D9-needsaudit👮

#650 Bump node and runtime versions to 900
  Cargo.lock
  container-chains/nodes/frontier/Cargo.toml
  container-chains/nodes/simple/Cargo.toml
  container-chains/runtime-templates/frontier/src/lib.rs
  container-chains/runtime-templates/simple/src/lib.rs
  node/Cargo.toml
  runtime/dancebox/src/lib.rs
  runtime/flashbox/src/lib.rs
Labels: B0-silent, D3-trivial, not-breaking

#649 ServicesPayment in Starlight runtime
  Cargo.lock
  solo-chains/runtime/starlight/Cargo.toml
  solo-chains/runtime/starlight/README.md
  solo-chains/runtime/starlight/constants/src/lib.rs
  solo-chains/runtime/starlight/src/genesis_config_presets.rs
  solo-chains/runtime/starlight/src/lib.rs
  solo-chains/runtime/starlight/src/tests/collator_assignment_tests.rs
  solo-chains/runtime/starlight/src/tests/common/mod.rs
  solo-chains/runtime/starlight/src/tests/mod.rs
  solo-chains/runtime/starlight/src/tests/services_payment.rs
Labels: B7-runtimenoteworthy, breaking, D5-nicetohaveaudit⚠️

#651 Update dancebox bootnodes
  specs/dancebox/dancebox-raw-specs.json
Labels: B5-clientnoteworthy, D2-notlive, not-breaking

#655 generate the authorize upgrade hash correctly in releases
  test/moonwall.config.json
  test/scripts/build-spec-single-container.sh
  tools/github/generate-runtimes-body.ts
Labels: B0-silent, D3-trivial, not-breaking

#658 increase timeout for container zombie upgrade tests
  test/moonwall.config.json
Labels: B0-silent, D3-trivial, not-breaking

#657 Fix docker build
  .github/workflows/cancel.yml
  .github/workflows/docker-runtime-draft.yml
  .github/workflows/release.yml
Labels: B0-silent, D3-trivial, not-breaking

#660 Set `npm-publish` to version 3
  .github/workflows/publish-typescript-api.yml
Labels: B0-silent, D3-trivial, not-breaking

#642 Remove without_storage_info from pallets
  pallets/authority-assignment/src/lib.rs
  pallets/authority-mapping/src/lib.rs
  pallets/collator-assignment/src/lib.rs
  pallets/configuration/src/lib.rs
  pallets/data-preservers/src/lib.rs
  pallets/data-preservers/src/mock.rs
  pallets/data-preservers/src/types.rs
  pallets/inflation-rewards/src/lib.rs
  pallets/initializer/src/lib.rs
  pallets/pooled-staking/src/candidate.rs
  pallets/pooled-staking/src/lib.rs
  pallets/pooled-staking/src/traits.rs
  pallets/registrar/src/lib.rs
  pallets/stream-payment/src/lib.rs
  pallets/xcm-core-buyer/src/lib.rs
  primitives/traits/src/lib.rs
  runtime/dancebox/src/lib.rs
  runtime/dancebox/src/xcm_config.rs
  runtime/flashbox/src/lib.rs
  solo-chains/runtime/starlight/src/validator_manager.rs
Labels: B0-silent, D3-trivial, not-breaking

#663 Add force-debug feature to starlight
  Cargo.lock
  solo-chains/runtime/starlight/Cargo.toml
Labels: B0-silent, D3-trivial, not-breaking

#667 Updated PolkadotJS and other dependencies in typescript-api
  .github/workflow-templates/typescript-tests-moonwall/action.yml
  .github/workflow-templates/zombienet-tests/action.yml
  .github/workflows/publish-typescript-api.yml
  .github/workflows/release.yml
  .github/workflows/run-zombienet-tests.yml
  .github/workflows/upgrade-typescript-api.yml
  pnpm-lock.yaml
  typescript-api/README.md
  typescript-api/package.json
  typescript-api/scripts/postbuild.ts
  typescript-api/scripts/runtime-upgrade.ts
  typescript-api/src/dancebox/interfaces/augment-api-consts.ts
  typescript-api/src/dancebox/interfaces/augment-api-errors.ts
  typescript-api/src/dancebox/interfaces/augment-api-events.ts
  typescript-api/src/dancebox/interfaces/augment-api-query.ts
  typescript-api/src/dancebox/interfaces/augment-api-rpc.ts
  typescript-api/src/dancebox/interfaces/augment-api-runtime.ts
  typescript-api/src/dancebox/interfaces/augment-api-tx.ts
  typescript-api/src/dancebox/interfaces/augment-types.ts
  typescript-api/src/dancebox/interfaces/lookup.ts
  typescript-api/src/dancebox/interfaces/types-lookup.ts
  typescript-api/src/dancebox/tsconfig.json
  typescript-api/src/flashbox/interfaces/augment-api-consts.ts
  typescript-api/src/flashbox/interfaces/augment-api-errors.ts
  typescript-api/src/flashbox/interfaces/augment-api-events.ts
  typescript-api/src/flashbox/interfaces/augment-api-query.ts
  typescript-api/src/flashbox/interfaces/augment-api-rpc.ts
  typescript-api/src/flashbox/interfaces/augment-api-tx.ts
  typescript-api/src/flashbox/interfaces/augment-types.ts
  typescript-api/src/flashbox/interfaces/lookup.ts
  typescript-api/src/index.cjs
  typescript-api/tsconfig.base.json
Labels: B0-silent, breaking, D3-trivial

#669 Update polkadot-sdk with non_authority_keys cherry-pick
  Cargo.lock
  client/consensus/src/tests.rs
  node/src/chain_spec/dancebox.rs
  node/src/chain_spec/flashbox.rs
  pallets/invulnerables/src/mock.rs
  primitives/author-noting-inherent/src/tests.rs
  runtime/dancebox/src/tests/common/mod.rs
  runtime/dancebox/src/tests/common/xcm/constants.rs
  runtime/flashbox/src/tests/common/mod.rs
  solo-chains/runtime/starlight/src/genesis_config_presets.rs
  solo-chains/runtime/starlight/src/tests/common/mod.rs
Labels: B0-silent, D3-trivial, not-breaking

#670 increase version typescript api
  pnpm-lock.yaml
  test/package.json
  typescript-api/package.json
Labels: B0-silent, D3-trivial, not-breaking

#668 Starlight collator rotation
  runtime/dancebox/src/lib.rs
  solo-chains/client/cli/src/command.rs
  solo-chains/runtime/starlight/src/lib.rs
  solo-chains/runtime/starlight/src/tests/collator_assignment_tests.rs
  solo-chains/runtime/starlight/src/tests/common/mod.rs
  test/suites/dev-tanssi-relay/collator-assignment/test-collator-assignment.ts
  test/suites/dev-tanssi-relay/pallet-data-preservers/test_pallet_data_preservers.ts
Labels: B7-runtimenoteworthy, breaking, D5-nicetohaveaudit⚠️
