Repository moondance-labs/tanssi, pull requests merged in 2024-07, with the labels that each got.

#615 Starlight CollatorConfiguration pallet and basic integration tests
  Cargo.lock
  solo-chains/runtime/starlight/Cargo.toml
  solo-chains/runtime/starlight/src/genesis_config_presets.rs
  solo-chains/runtime/starlight/src/lib.rs
  solo-chains/runtime/starlight/tests/common/mod.rs
  solo-chains/runtime/starlight/tests/integration_test.rs
Labels: B0-silent, D3-trivial, not-breaking

#613 Add pallet_registrar to Starlight as ContainerRegistrar
  Cargo.lock
  pallets/registrar/Cargo.toml
  solo-chains/runtime/starlight/Cargo.toml
  solo-chains/runtime/starlight/src/lib.rs
  solo-chains/runtime/starlight/tests/common/mod.rs
  solo-chains/runtime/starlight/tests/integration_test.rs
Labels: B0-silent, D3-trivial, not-breaking

#616 Remove unneeded migration pallets from starlight
  Cargo.lock
  solo-chains/runtime/starlight/Cargo.toml
  solo-chains/runtime/starlight/src/impls.rs
  solo-chains/runtime/starlight/src/lib.rs
Labels: B0-silent, D3-trivial, not-breaking

#619 Remove slot-related non-needed pallets in starlight
  solo-chains/runtime/starlight/src/lib.rs
Labels: a0-pleasereview, B7-runtimenoteworthy, breaking, D5-nicetohaveaudit⚠️

#620 removal of even more pallets: Bounties, Claims, NIS
  Cargo.lock
  solo-chains/runtime/starlight/Cargo.toml
  solo-chains/runtime/starlight/src/lib.rs
  solo-chains/runtime/starlight/src/tests.rs
Labels: a0-pleasereview, B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#614 Starlight Collator & Authority Assignments
  Cargo.lock
  pallets/collator-assignment/src/assignment.rs
  pallets/collator-assignment/src/lib.rs
  pallets/collator-assignment/src/mock.rs
  pallets/configuration/src/lib.rs
  pallets/configuration/src/mock.rs
  primitives/traits/src/lib.rs
  runtime/dancebox/src/lib.rs
  runtime/flashbox/src/lib.rs
  solo-chains/runtime/starlight/Cargo.toml
  solo-chains/runtime/starlight/src/genesis_config_presets.rs
  solo-chains/runtime/starlight/src/lib.rs
  solo-chains/runtime/starlight/tests/collator_assignment_tests.rs
  solo-chains/runtime/starlight/tests/common/mod.rs
  solo-chains/runtime/starlight/tests/integration_test.rs
Labels: B7-runtimenoteworthy, breaking, D9-needsaudit👮

#617 More int tests
  solo-chains/runtime/starlight/src/lib.rs
  solo-chains/runtime/starlight/tests/collator_assignment_tests.rs
  solo-chains/runtime/starlight/tests/common/mod.rs
  solo-chains/runtime/starlight/tests/integration_test.rs
  solo-chains/runtime/starlight/tests/relay_configuration.rs
  solo-chains/runtime/starlight/tests/relay_registrar.rs
  solo-chains/runtime/starlight/tests/session_keys.rs
  solo-chains/runtime/starlight/tests/sudo.rs
Labels: B0-silent, D3-trivial, not-breaking

#622 fix bench script
  tools/benchmarking.sh
Labels: B0-silent, D3-trivial, not-breaking

#612 Add support for parathread - part 3
  Cargo.lock
  client/consensus/Cargo.toml
  client/consensus/src/collators.rs
  client/consensus/src/collators/basic.rs
  client/consensus/src/collators/lookahead.rs
  client/consensus/src/consensus_orchestrator.rs
  client/consensus/src/lib.rs
  client/consensus/src/tests.rs
  node/src/container_chain_spawner.rs
  node/src/service.rs
  pallets/xcm-core-buyer/Cargo.toml
  pallets/xcm-core-buyer/runtime-api/Cargo.toml
  pallets/xcm-core-buyer/runtime-api/src/lib.rs
  pallets/xcm-core-buyer/src/benchmarks.rs
  pallets/xcm-core-buyer/src/lib.rs
  pallets/xcm-core-buyer/src/mock.rs
  pallets/xcm-core-buyer/src/tests.rs
  primitives/traits/src/lib.rs
  primitives/xcm-core-buyer/Cargo.toml
  primitives/xcm-core-buyer/src/lib.rs
  runtime/dancebox/Cargo.toml
  runtime/dancebox/src/lib.rs
  runtime/dancebox/src/xcm_config.rs
  test/configs/zombieTanssiParathreads.json
  test/scripts/build-spec-parathreads.sh
  test/suites/dev-tanssi/xcm-core-buyer/test_xcm_core_buyer.ts
  test/suites/parathreads/test_tanssi_parathreads.ts
  typescript-api/src/dancebox/interfaces/augment-api-consts.ts
  typescript-api/src/dancebox/interfaces/augment-api-tx.ts
  typescript-api/src/dancebox/interfaces/lookup.ts
  typescript-api/src/dancebox/interfaces/types-lookup.ts
Labels: B5-clientnoteworthy, B7-runtimenoteworthy, breaking, D9-needsaudit👮

#623 Remove unused dependencies
  Cargo.lock
  Cargo.toml
  client/manual-xcm/Cargo.toml
  client/stream-payment/Cargo.toml
  pallets/inflation-rewards/Cargo.toml
  pallets/pooled-staking/Cargo.toml
  primitives/author-noting-inherent/Cargo.toml
  primitives/container-chain-genesis-data/Cargo.toml
  runtime/relay-encoder/Cargo.toml
  solo-chains/client/cli/Cargo.toml
  solo-chains/node/tanssi-relay/Cargo.toml
  solo-chains/runtime/starlight/constants/Cargo.toml
Labels: B0-silent, D3-trivial, not-breaking

#624 fix master
  runtime/dancebox/tests/common/xcm/core_buyer_common.rs
Labels: B0-silent, D3-trivial, not-breaking

#608 Refactor container_chain_spawner
  client/node-common/src/command.rs
  docs/keep_db_flowchart.dot
  docs/keep_db_flowchart.png
  node/src/container_chain_spawner.rs
  node/src/service.rs
  test/suites/para/test_tanssi_containers.ts
  test/suites/warp-sync/test_warp_sync.ts
Labels: B5-clientnoteworthy, breaking, D5-nicetohaveaudit⚠️

#626 Increase error margin in parathead slot diff check
  test/suites/parathreads/test_tanssi_parathreads.ts
Labels: B0-silent, D2-notlive, not-breaking

#631 Test relay parachain
  solo-chains/client/cli/src/command.rs
  test/configs/zombieStarlight.json
  test/moonwall.config.json
Labels: a0-pleasereview, B0-silent, D3-trivial, not-breaking

#621 Migrations pallets for Starlight
  Cargo.lock
  Cargo.toml
  runtime/common/src/migrations.rs
  solo-chains/runtime/starlight/Cargo.toml
  solo-chains/runtime/starlight/src/lib.rs
Labels: a0-pleasereview, B7-runtimenoteworthy, breaking, D3-trivial

#630 XCM `DryRun` & `LocationToAccount` runtime APIs
  Cargo.lock
  Cargo.toml
  container-chains/runtime-templates/frontier/Cargo.toml
  container-chains/runtime-templates/frontier/src/lib.rs
  container-chains/runtime-templates/frontier/src/xcm_config.rs
  container-chains/runtime-templates/simple/Cargo.toml
  container-chains/runtime-templates/simple/src/lib.rs
  container-chains/runtime-templates/simple/src/xcm_config.rs
  pnpm-lock.yaml
  runtime/dancebox/Cargo.toml
  runtime/dancebox/src/lib.rs
  runtime/dancebox/src/xcm_config.rs
  solo-chains/node/tanssi-relay-service/Cargo.toml
  solo-chains/runtime/starlight/Cargo.toml
  solo-chains/runtime/starlight/src/lib.rs
  solo-chains/runtime/starlight/src/xcm_config.rs
  test/package.json
  test/suites/common-xcm/xcm/test-reserve-transfer-horizontal.ts
  test/suites/common-xcm/xcm/test-reserve-transfer-upward.ts
  test/suites/common-xcm/xcm/test-xcm-dry-run-api.ts
  test/suites/common-xcm/xcm/test-xcm-location-to-address.ts
  test/suites/common-xcm/xcm/test-xcm-send-horizontal.ts
  test/suites/common-xcm/xcm/test-xcm-send-upward.ts
  typescript-api/src/dancebox/interfaces/augment-api-query.ts
Labels: B7-runtimenoteworthy, breaking, D3-trivial

#634 Update polkadot-sdk to revert debug log
  Cargo.lock
Labels: B0-silent, D3-trivial, not-breaking

#606 Change Registrar balances reserves to holds and migration
  pallets/registrar/src/benchmarks.rs
  pallets/registrar/src/lib.rs
  pallets/registrar/src/mock.rs
  pallets/registrar/src/tests.rs
  runtime/common/src/migrations.rs
  runtime/dancebox/src/lib.rs
  runtime/dancebox/tests/integration_test.rs
  runtime/flashbox/src/lib.rs
  runtime/flashbox/tests/integration_test.rs
  solo-chains/runtime/starlight/src/lib.rs
  test/suites/dev-tanssi/register-with-relay-proof/test_deregister_with_relay_proof.ts
  typescript-api/src/dancebox/interfaces/lookup.ts
  typescript-api/src/dancebox/interfaces/registry.ts
  typescript-api/src/dancebox/interfaces/types-lookup.ts
  typescript-api/src/flashbox/interfaces/lookup.ts
  typescript-api/src/flashbox/interfaces/registry.ts
  typescript-api/src/flashbox/interfaces/types-lookup.ts
Labels: a0-pleasereview, B7-runtimenoteworthy, breaking, D5-nicetohaveaudit⚠️

#628 Improve CI: allow build with invalid fmt, add try-runtime to clippy
  .github/workflows/release.yml
Labels: B0-silent, ci, D2-notlive, not-breaking

#638 reflect rpc endpoint change in stagebox
  test/configs/stagenet-dancebox.yml
  test/moonwall.config.json
Labels: B0-silent, D3-trivial, not-breaking

#618 Add author-noting to starlight and make it generic over para/relay
  Cargo.lock
  pallets/author-noting/Cargo.toml
  pallets/author-noting/src/benchmarks.rs
  pallets/author-noting/src/lib.rs
  pallets/author-noting/src/mock.rs
  primitives/traits/Cargo.toml
  primitives/traits/src/lib.rs
  runtime/dancebox/src/lib.rs
  runtime/flashbox/src/lib.rs
  solo-chains/runtime/starlight/Cargo.toml
  solo-chains/runtime/starlight/src/lib.rs
  solo-chains/runtime/starlight/tests/author_noting_tests.rs
  solo-chains/runtime/starlight/tests/common/mod.rs
Labels: B0-silent, D5-nicetohaveaudit⚠️, not-breaking

#635 Add zombie_flashbox moonwall suite, not enabled in CI
  test/configs/zombieFlashbox.json
  test/moonwall.config.json
  test/scripts/build-spec-flashbox.sh
  test/suites/para/test_tanssi_containers.ts
Labels: B0-silent, D2-notlive, not-breaking

#632 Allow registering parathreads in pallet_registrar genesis
  node/src/chain_spec/dancebox.rs
  node/src/chain_spec/flashbox.rs
  pallets/registrar/src/lib.rs
  pallets/registrar/src/mock.rs
  pallets/registrar/src/tests.rs
  runtime/dancebox/src/tests/common/mod.rs
  runtime/dancebox/src/tests/integration_test.rs
  runtime/flashbox/src/tests/common/mod.rs
  runtime/flashbox/src/tests/integration_test.rs
  solo-chains/runtime/starlight/src/tests/author_noting_tests.rs
  solo-chains/runtime/starlight/src/tests/collator_assignment_tests.rs
  solo-chains/runtime/starlight/src/tests/common/mod.rs
  solo-chains/runtime/starlight/src/tests/integration_test.rs
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#636 Allow manual running of all zombienet tests in CI
  .github/workflow-templates/zombienet-tests/action.yml
  .github/workflows/release.yml
  .github/workflows/run-zombienet-tests.yml
  test/moonwall.config.json
Labels: B0-silent, D2-notlive, not-breaking
