Repository moondance-labs/tanssi, pull requests merged in 2024-09, with the labels that each got.

#662 Test lookahead collator
  Cargo.lock
  Cargo.toml
  client/consensus/Cargo.toml
  client/consensus/src/collators.rs
  client/consensus/src/collators/basic.rs
  client/consensus/src/collators/lookahead.rs
  client/consensus/src/consensus_orchestrator.rs
  client/consensus/src/lib.rs
  client/consensus/src/mocks.rs
  client/consensus/src/tests.rs
Labels: B0-silent, D3-trivial, not-breaking

#672 Store collator fullness in collator_assignment pallet
  pallets/collator-assignment/src/lib.rs
  pallets/collator-assignment/src/mock.rs
  pallets/configuration/src/lib.rs
  primitives/traits/src/lib.rs
  test/suites/dev-tanssi/collator-assignment/test-collator-assignment.ts
  test/suites/dev-tanssi/collator-assignment/test-collator-fullness.ts
  typescript-api/src/dancebox/interfaces/augment-api-query.ts
  typescript-api/src/flashbox/interfaces/augment-api-query.ts
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#671 new tools for developers: testing a custom runtime upgrade against released binaries
  runtime/flashbox/src/lib.rs
  test/moonwall.config.json
  test/scripts/download-latest-binaries.sh
Labels: B0-silent, breaking, D3-trivial

#666 [POC] Spawn embeded Container chain node on data preservers assignment
  .github/workflows/release.yml
  Cargo.lock
  Cargo.toml
  client/consensus/src/mocks.rs
  client/orchestrator-chain-rpc-interface/src/lib.rs
  client/service-container-chain/Cargo.toml
  client/service-container-chain/src/data_preservers.rs
  client/service-container-chain/src/lib.rs
  client/service-container-chain/src/spawner.rs
  container-chains/nodes/simple/src/cli.rs
  container-chains/nodes/simple/src/command.rs
  node/Cargo.toml
  node/src/cli.rs
  node/src/service.rs
  pallets/data-preservers/runtime-api/Cargo.toml
  pallets/data-preservers/runtime-api/src/lib.rs
  pnpm-lock.yaml
  runtime/dancebox/Cargo.toml
  runtime/dancebox/src/lib.rs
  runtime/flashbox/Cargo.toml
  runtime/flashbox/src/lib.rs
  test/configs/zombieDataPreservers.json
  test/moonwall.config.json
  test/suites/data-preservers/test_data_preservers.ts
Labels: a0-pleasereview, B5-clientnoteworthy, B7-runtimenoteworthy, breaking, D5-nicetohaveaudit⚠️

#674 create function to calculate the relay prathread tank address in typescript
  test/suites/parathreads/test_tanssi_parathreads.ts
  test/util/xcm.ts
Labels: B0-silent, D3-trivial, not-breaking

#676 Remove should_end_session check in Starlight, it always returns false
  solo-chains/runtime/starlight/src/lib.rs
Labels: B0-silent, D3-trivial, not-breaking

#677 Filter register parathread calls starlight & flashbox
  runtime/flashbox/src/lib.rs
  runtime/flashbox/src/tests/integration_test.rs
  solo-chains/runtime/starlight/src/lib.rs
  solo-chains/runtime/starlight/src/tests/relay_registrar.rs
  test/suites/common-tanssi-parachain/pallet-data-preservers/test_pallet_data_preservers.ts
  test/suites/dev-tanssi-relay/pallet-data-preservers/test_pallet_data_preservers.ts
  test/suites/dev-tanssi-relay/registrar/test_registrars.ts
  test/suites/dev-tanssi/registrar/test_registrar_register_parathread.ts
Labels: B7-runtimenoteworthy, breaking, D5-nicetohaveaudit⚠️

#675 Starlight benchmarking
  .gitignore
  solo-chains/client/cli/src/command.rs
  solo-chains/runtime/starlight/src/lib.rs
  tools/benchmark-all-runtimes.sh
Labels: B0-silent, D2-notlive, not-breaking

#679 Reorder session indices for collators
  pallets/registrar/src/lib.rs
  pallets/registrar/src/mock.rs
  pallets/registrar/src/tests.rs
  solo-chains/runtime/starlight/constants/src/lib.rs
  solo-chains/runtime/starlight/src/genesis_config_presets.rs
  solo-chains/runtime/starlight/src/lib.rs
  solo-chains/runtime/starlight/src/tests/common/mod.rs
  solo-chains/runtime/starlight/src/tests/relay_registrar.rs
  test/configs/zombieStarlight.json
  test/moonwall.config.json
  test/suites/common-tanssi-parachain/registrar/test_registrar_deregister.ts
  test/suites/dev-tanssi-relay/registrar/test_registrars.ts
  test/suites/zombie-tanssi-relay/test-tanssi-relay.ts
Labels: B7-runtimenoteworthy, D9-needsaudit👮, not-breaking

#665 Configurable priority for Bulk Paras
  node/src/chain_spec/dancebox.rs
  node/src/chain_spec/flashbox.rs
  pallets/collator-assignment/src/lib.rs
  pallets/collator-assignment/src/mock.rs
  pallets/collator-assignment/src/tests.rs
  pallets/collator-assignment/src/tests/with_core_config.rs
  pallets/configuration/src/lib.rs
  pnpm-lock.yaml
  primitives/traits/src/lib.rs
  runtime/common/src/migrations.rs
  runtime/dancebox/src/lib.rs
  runtime/flashbox/src/lib.rs
  solo-chains/runtime/starlight/src/genesis_config_presets.rs
  solo-chains/runtime/starlight/src/lib.rs
  solo-chains/runtime/starlight/src/tests/collator_assignment_tests.rs
  solo-chains/runtime/starlight/src/tests/common/mod.rs
  test/suites/dev-tanssi-relay/collator-assignment/test-configurable-priority.ts
  typescript-api/src/dancebox/interfaces/augment-api-tx.ts
  typescript-api/src/dancebox/interfaces/lookup.ts
  typescript-api/src/dancebox/interfaces/types-lookup.ts
  typescript-api/src/flashbox/interfaces/augment-api-tx.ts
  typescript-api/src/flashbox/interfaces/lookup.ts
  typescript-api/src/flashbox/interfaces/types-lookup.ts
Labels: B7-runtimenoteworthy, breaking, D9-needsaudit👮

#685 Add storage migration for parachain percentage
  runtime/common/src/migrations.rs
  runtime/dancebox/src/tests/integration_test.rs
Labels: B7-runtimenoteworthy, D2-notlive, not-breaking

#684 Always use warp sync for container chains
  client/service-container-chain/src/spawner.rs
  container-chains/nodes/simple/src/command.rs
  node/src/service.rs
  test/suites/warp-sync/test_warp_sync.ts
Labels: B5-clientnoteworthy, D3-trivial, not-breaking

#687 Increase timeout for zombie_tanssi_relay test
  test/suites/zombie-tanssi-relay/test-tanssi-relay.ts
Labels: B0-silent, D2-notlive, not-breaking

#689 Starlight: Add `InflationRewards` pallet
  Cargo.lock
  pallets/inflation-rewards/src/lib.rs
  pallets/inflation-rewards/src/mock.rs
  pallets/inflation-rewards/src/tests.rs
  primitives/traits/src/lib.rs
  runtime/dancebox/src/lib.rs
  runtime/flashbox/src/lib.rs
  solo-chains/runtime/starlight/Cargo.toml
  solo-chains/runtime/starlight/src/lib.rs
  solo-chains/runtime/starlight/src/tests/common/mod.rs
  solo-chains/runtime/starlight/src/tests/inflation_rewards.rs
  solo-chains/runtime/starlight/src/tests/mod.rs
  test/suites/dev-tanssi-relay/inflation-rewards/test-rewards.ts
  test/util/constants.ts
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#683 Change solochain flag into subcommand
  Cargo.lock
  Cargo.toml
  client/consensus/src/collators/lookahead.rs
  client/consensus/src/mocks.rs
  client/service-container-chain/Cargo.toml
  client/service-container-chain/src/cli.rs
  client/service-container-chain/src/service.rs
  client/service-container-chain/src/spawner.rs
  container-chains/nodes/simple/src/command.rs
  node/Cargo.toml
  node/src/cli.rs
  node/src/command.rs
  node/src/command/solochain.rs
  node/src/service.rs
  test/configs/zombieStarlight.json
  test/scripts/build-spec-starlight.sh
  test/suites/zombie-tanssi-relay/test-tanssi-relay.ts
Labels: B5-clientnoteworthy, D3-trivial, not-breaking

#695 Benchmark starlight
  solo-chains/runtime/dancelight/src/governance/fellowship.rs
  solo-chains/runtime/dancelight/src/governance/mod.rs
  solo-chains/runtime/dancelight/src/lib.rs
  solo-chains/runtime/dancelight/src/weights/frame_system.rs
  solo-chains/runtime/dancelight/src/weights/mod.rs
  solo-chains/runtime/dancelight/src/weights/pallet_asset_rate.rs
  solo-chains/runtime/dancelight/src/weights/pallet_balances.rs
  solo-chains/runtime/dancelight/src/weights/pallet_conviction_voting.rs
  solo-chains/runtime/dancelight/src/weights/pallet_identity.rs
  solo-chains/runtime/dancelight/src/weights/pallet_message_queue.rs
  solo-chains/runtime/dancelight/src/weights/pallet_multisig.rs
  solo-chains/runtime/dancelight/src/weights/pallet_parameters.rs
  solo-chains/runtime/dancelight/src/weights/pallet_preimage.rs
  solo-chains/runtime/dancelight/src/weights/pallet_proxy.rs
  solo-chains/runtime/dancelight/src/weights/pallet_ranked_collective.rs
  solo-chains/runtime/dancelight/src/weights/pallet_referenda.rs
  solo-chains/runtime/dancelight/src/weights/pallet_scheduler.rs
  solo-chains/runtime/dancelight/src/weights/pallet_services_payment.rs
  solo-chains/runtime/dancelight/src/weights/pallet_sudo.rs
  solo-chains/runtime/dancelight/src/weights/pallet_timestamp.rs
  solo-chains/runtime/dancelight/src/weights/pallet_treasury.rs
  solo-chains/runtime/dancelight/src/weights/pallet_utility.rs
  solo-chains/runtime/dancelight/src/weights/pallet_whitelist.rs
  solo-chains/runtime/dancelight/src/weights/pallet_xcm.rs
  solo-chains/runtime/dancelight/src/weights/runtime_common_paras_registrar.rs
  solo-chains/runtime/dancelight/src/weights/runtime_parachains_assigner_on_demand.rs
  solo-chains/runtime/dancelight/src/weights/runtime_parachains_configuration.rs
  solo-chains/runtime/dancelight/src/weights/runtime_parachains_disputes.rs
  solo-chains/runtime/dancelight/src/weights/runtime_parachains_hrmp.rs
  solo-chains/runtime/dancelight/src/weights/runtime_parachains_inclusion.rs
  solo-chains/runtime/dancelight/src/weights/runtime_parachains_initializer.rs
  solo-chains/runtime/dancelight/src/weights/runtime_parachains_paras.rs
  solo-chains/runtime/dancelight/src/weights/runtime_parachains_paras_inherent.rs
  solo-chains/runtime/dancelight/src/xcm_config.rs
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#697 Add missing std features to fix build with -p tanssi-relay
  Cargo.toml
  solo-chains/client/cli/Cargo.toml
  solo-chains/node/tanssi-relay-service/Cargo.toml
Labels: B0-silent, D2-notlive, not-breaking

#696 Starlight: Add Starlight to CI release jobs
  .github/workflows/prepare-tanssi-relay-binary.yml
  .github/workflows/publish-binary-tannsi-relay.yml
  .github/workflows/publish-docker-tannsi-relay.yml
  .github/workflows/publish-runtime.yml
Labels: B0-silent, D2-notlive, not-breaking

#698 CI: Adding Starlight to Docker
  .github/workflows/prepare-tanssi-relay-binary.yml
  .github/workflows/publish-docker-tannsi-relay.yml
  docker/starlight.Dockerfile
Labels: B0-silent, D2-notlive, not-breaking

#699 Fix runtime release
  scripts/build-runtime-srtool.sh
  tools/github/generate-runtimes-body.ts
Labels: B0-silent, D3-trivial, not-breaking

#700 token name
  solo-chains/node/tanssi-relay-service/src/chain_spec.rs
Labels: B5-clientnoteworthy, D3-trivial, not-breaking

#702 Increase setMaxParachainCoresPercentage in zombie_tanssi_relay
  test/suites/one-node/test_tanssi_one_node.ts
  test/suites/parathreads/test_tanssi_parathreads.ts
  test/suites/rotation-para/test_rotation.ts
  test/suites/zombie-tanssi-relay/test-tanssi-relay.ts
Labels: B0-silent, D3-trivial, not-breaking
