Repository moondance-labs/tanssi, pull requests merged in 2024-04, with the labels that each got.

#483 Fix calculation of Auto compounding delegation of candidate
  test/suites/smoke-test-dancebox/test-staking-consistency.ts
Labels: B0-silent, D2-notlive, D3-trivial, not-breaking

#482 put all pallet constants as constant
  pallets/authority-mapping/src/lib.rs
  pallets/configuration/src/lib.rs
  pallets/data-preservers/src/lib.rs
  pallets/inflation-rewards/src/lib.rs
  pallets/invulnerables/src/lib.rs
  pallets/pooled-staking/src/lib.rs
  pallets/registrar/src/lib.rs
  pallets/services-payment/src/lib.rs
  pallets/xcm-core-buyer/src/lib.rs
  typescript-api/src/dancebox/interfaces/augment-api-consts.ts
  typescript-api/src/flashbox/interfaces/augment-api-consts.ts
Labels: B7-runtimenoteworthy, breaking, D3-trivial

#479 Add delivery fees
  Cargo.lock
  Cargo.toml
  container-chains/templates/frontier/runtime/src/xcm_config.rs
  container-chains/templates/simple/runtime/src/xcm_config.rs
  runtime/dancebox/Cargo.toml
  runtime/dancebox/src/xcm_config.rs
  runtime/dancebox/tests/common/xcm/delivery_fees.rs
  runtime/dancebox/tests/common/xcm/mod.rs
  test/suites/common-xcm/xcm/test-reserve-transfer-horizontal.ts
  test/suites/common-xcm/xcm/test-reserve-transfer-upward.ts
  test/suites/common-xcm/xcm/test-xcm-send-horizontal.ts
  test/suites/common-xcm/xcm/test-xcm-send-upward.ts
  test/util/xcm.ts
Labels: a0-pleasereview, B7-runtimenoteworthy, breaking, D5-nicetohaveaudit⚠️

#476 Allow parathread manager to set max core price
  pallets/services-payment/src/benchmarks.rs
  pallets/services-payment/src/lib.rs
  pallets/services-payment/src/mock.rs
  pallets/services-payment/src/weights.rs
  pallets/xcm-core-buyer/src/lib.rs
  pallets/xcm-core-buyer/src/mock.rs
  runtime/dancebox/src/lib.rs
  runtime/dancebox/src/xcm_config.rs
  runtime/dancebox/tests/common/xcm/core_buyer.rs
  runtime/flashbox/src/lib.rs
  typescript-api/src/dancebox/interfaces/augment-api-events.ts
  typescript-api/src/dancebox/interfaces/augment-api-query.ts
  typescript-api/src/dancebox/interfaces/augment-api-tx.ts
  typescript-api/src/dancebox/interfaces/lookup.ts
  typescript-api/src/dancebox/interfaces/types-lookup.ts
  typescript-api/src/flashbox/interfaces/augment-api-events.ts
  typescript-api/src/flashbox/interfaces/augment-api-query.ts
  typescript-api/src/flashbox/interfaces/augment-api-tx.ts
  typescript-api/src/flashbox/interfaces/lookup.ts
  typescript-api/src/flashbox/interfaces/types-lookup.ts
Labels: B7-runtimenoteworthy, breaking, D5-nicetohaveaudit⚠️

#481 Use cancellation token and exit notifications instead of watch
  Cargo.lock
  Cargo.toml
  client/consensus/Cargo.toml
  client/consensus/src/collators/lookahead.rs
  node/Cargo.toml
  node/src/container_chain_spawner.rs
  node/src/service.rs
Labels: enhancement, B5-clientnoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#487 Fix division by zero in staking inconsistency test
  test/suites/smoke-test-dancebox/test-staking-consistency.ts
Labels: B0-silent, D2-notlive, not-breaking

#484 StreamPayment status Runtime API and RPC
  Cargo.lock
  Cargo.toml
  client/stream-payment/Cargo.toml
  client/stream-payment/src/lib.rs
  container-chains/templates/frontier/runtime/src/xcm_config.rs
  node/Cargo.toml
  node/src/rpc.rs
  pallets/stream-payment/Cargo.toml
  pallets/stream-payment/rpc/runtime-api/Cargo.toml
  pallets/stream-payment/rpc/runtime-api/src/lib.rs
  pallets/stream-payment/src/benchmarking.rs
  pallets/stream-payment/src/lib.rs
  pallets/stream-payment/src/tests.rs
  pallets/xcm-core-buyer/src/lib.rs
  pallets/xcm-core-buyer/src/mock.rs
  runtime/dancebox/Cargo.toml
  runtime/dancebox/src/lib.rs
  runtime/dancebox/tests/common/xcm/constants.rs
  runtime/dancebox/tests/common/xcm/core_buyer.rs
  runtime/dancebox/tests/common/xcm/mod.rs
  runtime/dancebox/tests/integration_test.rs
  runtime/flashbox/Cargo.toml
  runtime/flashbox/src/lib.rs
  runtime/flashbox/tests/integration_test.rs
  runtime/relay-encoder/src/rococo.rs
  runtime/relay-encoder/src/westend.rs
  test/suites/common-tanssi/stream-payment/test_stream_payment.ts
  test/suites/common-tanssi/stream-payment/test_stream_payment_rpc.ts
  typescript-api/src/dancebox/interfaces/augment-api-events.ts
  typescript-api/src/dancebox/interfaces/lookup.ts
  typescript-api/src/dancebox/interfaces/types-lookup.ts
  typescript-api/src/flashbox/interfaces/augment-api-events.ts
  typescript-api/src/flashbox/interfaces/lookup.ts
  typescript-api/src/flashbox/interfaces/types-lookup.ts
Labels: a0-pleasereview, B7-runtimenoteworthy, breaking, D5-nicetohaveaudit⚠️

#491 Avoid executing html in download polkadot script
  test/scripts/download-polkadot.sh
Labels: B0-silent, D2-notlive, not-breaking

#489 Fix compile-wasm script
  test/scripts/compile-wasm.ts
Labels: B0-silent, D2-notlive, not-breaking

#492 Stop orchestrator collator as soon as the node is unassigned
  client/consensus/src/collators/lookahead.rs
  node/src/container_chain_spawner.rs
  node/src/service.rs
  test/suites/para/test_tanssi_containers.ts
Labels: B5-clientnoteworthy, breaking, D5-nicetohaveaudit⚠️

#496 Fix zombienet test by undoing a change
  test/suites/para/test_tanssi_containers.ts
Labels: B0-silent, D2-notlive, not-breaking

#494 Do not panic when container chain fails to start
  node/src/container_chain_spawner.rs
Labels: B5-clientnoteworthy, breaking, D5-nicetohaveaudit⚠️

#497 Improve more timeouts in zombienet tests
  test/suites/keep-db/test_restart_keep_db.ts
  test/suites/metrics/test_metrics_stop.ts
  test/suites/para/test_tanssi_containers.ts
  test/suites/parathreads/test_tanssi_parathreads.ts
  test/suites/rotation-para/test_rotation.ts
  test/suites/warp-sync/test_warp_sync.ts
Labels: B0-silent, D3-trivial, not-breaking

#498 MD325/MD326 - invulnerables
  client/consensus/src/collators/lookahead.rs
  node/src/container_chain_spawner.rs
  pallets/invulnerables/src/benchmarking.rs
  pallets/invulnerables/src/lib.rs
  pallets/invulnerables/src/tests.rs
  pallets/invulnerables/src/weights.rs
  runtime/dancebox/tests/integration_test.rs
  runtime/flashbox/tests/integration_test.rs
  test/suites/dev-tanssi/session-keys/test_remove_session_key_staking.ts
  test/suites/dev-tanssi/staking/test_staking_rewards_balanced.ts
  test/suites/dev-tanssi/staking/test_staking_rewards_non_balanced.ts
  test/suites/warp-sync/test_warp_sync.ts
  test/util/invulnerables.ts
  typescript-api/src/dancebox/interfaces/augment-api-tx.ts
  typescript-api/src/dancebox/interfaces/lookup.ts
  typescript-api/src/dancebox/interfaces/types-lookup.ts
  typescript-api/src/flashbox/interfaces/augment-api-tx.ts
  typescript-api/src/flashbox/interfaces/lookup.ts
  typescript-api/src/flashbox/interfaces/types-lookup.ts
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#493 Stream payment deposit on opening a stream
  pallets/stream-payment/src/lib.rs
  pallets/stream-payment/src/mock.rs
  pallets/stream-payment/src/tests.rs
  runtime/dancebox/src/lib.rs
  runtime/flashbox/src/lib.rs
  test/suites/common-tanssi/stream-payment/test_stream_payment.ts
  typescript-api/src/dancebox/interfaces/augment-api-consts.ts
  typescript-api/src/dancebox/interfaces/lookup.ts
  typescript-api/src/dancebox/interfaces/types-lookup.ts
  typescript-api/src/flashbox/interfaces/augment-api-consts.ts
  typescript-api/src/flashbox/interfaces/lookup.ts
  typescript-api/src/flashbox/interfaces/types-lookup.ts
Labels: B7-runtimenoteworthy, breaking, D5-nicetohaveaudit⚠️

#500 Store tanssi slot number in author noting pallet
  Cargo.lock
  pallets/author-noting/Cargo.toml
  pallets/author-noting/src/lib.rs
  pallets/author-noting/src/mock.rs
  pallets/author-noting/src/tests.rs
  runtime/dancebox/src/lib.rs
  runtime/dancebox/tests/integration_test.rs
  runtime/flashbox/src/lib.rs
  runtime/flashbox/tests/integration_test.rs
Labels: B7-runtimenoteworthy, breaking, D3-trivial

#510 upgrade node and runtime versions to the following
  Cargo.lock
  container-chains/templates/frontier/node/Cargo.toml
  container-chains/templates/frontier/runtime/src/lib.rs
  container-chains/templates/simple/node/Cargo.toml
  container-chains/templates/simple/runtime/src/lib.rs
  node/Cargo.toml
  runtime/dancebox/src/lib.rs
  runtime/flashbox/src/lib.rs
Labels: B0-silent, D3-trivial, not-breaking

#508 Fix actions
  .github/workflows/client-release-issue.yml
  .github/workflows/prepare-binary.yml
  .github/workflows/publish-binary.yml
  .github/workflows/publish-runtime.yml
  .github/workflows/runtime-release-issue.yml
Labels: B0-silent, D3-trivial, not-breaking

#512 Fix S09C02 and S08C03
  test/suites/smoke-test-common/test-inflation-rewards.ts
  test/suites/smoke-test-dancebox/test-randomness-consistency.ts
Labels: B0-silent, D2-notlive, not-breaking

#511 Implement Default for ExtBuilder and simplify integration tests
  runtime/dancebox/tests/common/mod.rs
  runtime/dancebox/tests/integration_test.rs
  runtime/flashbox/tests/common/mod.rs
  runtime/flashbox/tests/integration_test.rs
Labels: B0-silent, D3-trivial, I4-tests 🎯, not-breaking

#514 build_upon implementation in flashbox
  Cargo.lock
  runtime/flashbox/Cargo.toml
  runtime/flashbox/src/lib.rs
Labels: B7-runtimenoteworthy, breaking, D3-trivial

#515 increase maxLenghtParas for flashbox
  runtime/flashbox/src/lib.rs
Labels: B7-runtimenoteworthy, breaking, D3-trivial

#519 Set AllowMultipleBlocksPerSlot = true in flashbox
  runtime/flashbox/src/lib.rs
Labels: B7-runtimenoteworthy, breaking, D5-nicetohaveaudit⚠️

#517 add new runtime publishing possibilities
  .github/workflows/publish-runtime-chevdor.yml
  .github/workflows/publish-runtime.yml
Labels: B0-silent, D3-trivial, not-breaking

#518 Change run_block function in integration tests
  runtime/dancebox/tests/common/mod.rs
  runtime/dancebox/tests/common/xcm/core_buyer.rs
  runtime/dancebox/tests/integration_test.rs
  runtime/flashbox/tests/common/mod.rs
  runtime/flashbox/tests/integration_test.rs
Labels: B0-silent, D2-notlive, not-breaking

#526 remove pallet-hotfix-sufficients from frontier template
  Cargo.lock
  container-chains/runtime-templates/frontier/Cargo.toml
  container-chains/runtime-templates/frontier/src/lib.rs
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#529 make upgrade test more reslitient by detecting session changes
  test/configs/dancebox.yml
  test/configs/frontierContainer.yml
  test/configs/stagenet-dancebox.yml
  test/configs/stagenet-flashbox.yml
  test/suites/rt-upgrade-chopsticks-orchestrator/test-upgrade-chain.ts
Labels: B0-silent, D3-trivial, not-breaking

#527 Frontier template `isBlockFinalized` & `isTxFinalized` RPC methods
  container-chains/nodes/frontier/src/rpc/finality.rs
  container-chains/nodes/frontier/src/rpc/mod.rs
  test/suites/dev-frontier-template/test-eth-asset-address/test-eth-asset-address-creation.ts
  test/suites/dev-frontier-template/test-eth-block/test-eth-block-pending.ts
  test/suites/dev-frontier-template/test-eth-fee/test-eth-fee-history.ts
  test/suites/dev-frontier-template/test-eth-pool/test-eth-pool-discard.ts
  test/suites/dev-frontier-template/test-eth-pool/test-eth-pool-resubmit.ts
  test/suites/dev-frontier-template/test-eth-rpc/test-eth-rpc-constants.ts
  test/suites/dev-frontier-template/test-eth-rpc/test-eth-rpc-index.ts
  test/suites/dev-frontier-template/test-eth-rpc/test-eth-rpc-log-filtering.ts
  test/suites/dev-frontier-template/test-eth-tx/test-eth-tx-nonce.ts
  test/suites/dev-frontier-template/test-evm/test-evm-maintenance-mode.ts
  test/suites/dev-frontier-template/test-evm/test-evm-rpc-block-author.ts
  test/suites/dev-frontier-template/test-evm/test-evm-transfer-origints.ts
  test/suites/dev-frontier-template/test-frnt-rpc/test-frnt-rpc.ts
  test/suites/dev-frontier-template/test-pallet-cc-authorities-noting/test-orchestrator-para-id.ts
  test/suites/dev-frontier-template/test-precompiles/test-precompile-assets-erc20-1.ts
  test/suites/dev-frontier-template/test-precompiles/test-precompile-assets-erc20-2.ts
  test/suites/dev-frontier-template/test-precompiles/test-precompile-assets-erc20-3.ts
  test/suites/dev-frontier-template/test-precompiles/test-precompile-assets-erc20-4.ts
  test/suites/dev-frontier-template/test-precompiles/test-precompile-assets-erc20-5.ts
  test/suites/dev-frontier-template/test-precompiles/test-precompile-assets-erc20-6.ts
  test/suites/dev-frontier-template/test-precompiles/test-precompile-assets-erc20-7.ts
  test/suites/dev-frontier-template/test-precompiles/test-precompile-assets-erc20-low-level.ts
  test/suites/dev-frontier-template/test-precompiles/test-precompile-batch.ts
  test/suites/dev-frontier-template/test-precompiles/test-precompile-call-permit.ts
  test/suites/dev-frontier-template/test-precompiles/test-precompile-erc20.ts
  test/suites/dev-frontier-template/test-precompiles/test-precompile-smart-contract-call.ts
  test/suites/dev-frontier-template/test-precompiles/test-precompile-xcm-utils.ts
  test/suites/dev-frontier-template/weights/test_set_latest_authorities_data.ts
Labels: B5-clientnoteworthy, breaking, D3-trivial

#530 forbid teleports and fix command in templates
  container-chains/nodes/frontier/src/command.rs
  container-chains/runtime-templates/frontier/src/xcm_config.rs
  container-chains/runtime-templates/simple/src/xcm_config.rs
  test/suites/common-xcm/xcm-token-reception/test_dmp_token_reception_teleport.ts
  test/util/xcm.ts
Labels: B7-runtimenoteworthy, breaking, D3-trivial

#533 Add rimraf to devDependencies
  pnpm-lock.yaml
  typescript-api/package.json
Labels: B0-silent, D3-trivial, not-breaking

#523 Add tests to tanssi-node
  Cargo.lock
  Cargo.toml
  node/Cargo.toml
  node/src/main.rs
  node/src/tests/mod.rs
  node/src/tests/panics.rs
Labels: B0-silent, D2-notlive, not-breaking

#531 use the benchmarking code for foreign-assets
  Cargo.lock
  container-chains/runtime-templates/frontier/src/lib.rs
  container-chains/runtime-templates/simple/src/lib.rs
  runtime/dancebox/src/lib.rs
Labels: B0-silent, D3-trivial, not-breaking

#537 reduce validators in zombienet tests to minimum
  test/configs/zombieTanssiParathreads.json
  test/configs/zombieTanssiRotation.json
  test/configs/zombieTanssiWarpSync.json
Labels: B0-silent, D3-trivial, not-breaking

#528 Migrate PendingVerification in pallet_registrar from value to map
  pallets/registrar/src/benchmarks.rs
  pallets/registrar/src/lib.rs
  runtime/common/src/migrations.rs
  runtime/dancebox/tests/integration_test.rs
  typescript-api/src/dancebox/interfaces/augment-api-query.ts
  typescript-api/src/flashbox/interfaces/augment-api-query.ts
Labels: B7-runtimenoteworthy, breaking, D5-nicetohaveaudit⚠️

#534 Fix smoke test when flashbox chain has no credits
  test/suites/smoke-test-common/test-configuration-consistency.ts
  test/suites/smoke-test-common/test-consistency-services-payment.ts
  test/util/payment.ts
Labels: B0-silent, D3-trivial, not-breaking

#538 Add zombie_tanssi_one_node test suite
  test/configs/zombieTanssiOneNode.json
  test/moonwall.config.json
  test/scripts/build-spec-one-node.sh
  test/suites/one-node/test_tanssi_one_node.ts
Labels: B0-silent, D2-notlive, not-breaking
