Repository moondance-labs/tanssi, pull requests merged in 2024-12, with the labels that each got.

#766 Add zombienet suite for unneeded para bug
  test/configs/zombieDancelightUnneededPara.json
  test/moonwall.config.json
  test/suites/zombie-tanssi-relay-unneeded-para/test-tanssi-relay-unneeded-para.ts
Labels: B0-silent, D2-notlive, not-breaking

#771 Rename zombienet config files and test folders to match suite name
  test/configs/zombie_dancebox_upgrade.json
  test/configs/zombie_dancelight_upgrade.json
  test/configs/zombie_data_preservers.json
  test/configs/zombie_flashbox.json
  test/configs/zombie_frontier_template_upgrade.json
  test/configs/zombie_simple_template_offchain.json
  test/configs/zombie_simple_template_upgrade.json
  test/configs/zombie_tanssi.json
  test/configs/zombie_tanssi_keep_db.json
  test/configs/zombie_tanssi_metrics.json
  test/configs/zombie_tanssi_one_node.json
  test/configs/zombie_tanssi_parathreads.json
  test/configs/zombie_tanssi_relay.json
  test/configs/zombie_tanssi_relay_eth_bridge.json
  test/configs/zombie_tanssi_relay_unneeded_para.json
  test/configs/zombie_tanssi_rotation.json
  test/configs/zombie_tanssi_warp_sync.json
  test/moonwall.config.json
  test/suites/zombie_dancebox_upgrade/test_zombie_dancebox_upgrade.ts
  test/suites/zombie_dancelight_upgrade/test_zombie_dancelight_upgrade.ts
  test/suites/zombie_data_preservers/test_zombie_data_preservers.ts
  test/suites/zombie_simple_template_offchain/test_zombie_simple_template_offchain.ts
  test/suites/zombie_simple_template_upgrade/test_zombie_simple_template_upgrade.ts
  test/suites/zombie_tanssi/test_zombie_tanssi.ts
  test/suites/zombie_tanssi_keep_db/test_zombie_tanssi_keep_db.ts
  test/suites/zombie_tanssi_metrics/test_zombie_tanssi_metrics.ts
  test/suites/zombie_tanssi_one_node/test_zombie_tanssi_one_node.ts
  test/suites/zombie_tanssi_parathreads/test_zombie_tanssi_parathreads.ts
  test/suites/zombie_tanssi_relay/test_zombie_tanssi_relay.ts
  test/suites/zombie_tanssi_relay_eth_bridge/test_zombie_tanssi_relay_eth_bridge.ts
  test/suites/zombie_tanssi_relay_unneeded_para/test_zombie_tanssi_relay_unneeded_para.ts
  test/suites/zombie_tanssi_rotation/test_zombie_tanssi_rotation.ts
  test/suites/zombie_tanssi_warp_sync/test_zombie_tanssi_warp_sync.ts
Labels: B0-silent, D2-notlive, not-breaking

#760 add services payment test
  test/suites/dev-tanssi-relay/services-payment/test_services_payment_block_credits.ts
  test/suites/dev-tanssi-relay/services-payment/test_services_payment_collator_credits.ts
Labels: B0-silent, D3-trivial, not-breaking

#776 Fix benchmarking script
  tools/benchmarking.sh
Labels: B0-silent, D2-notlive, not-breaking

#772 Add support for eth to starlight message passing
  test/scripts/bridge/assets/execution-relay.json
  test/scripts/bridge/build-relayer.sh
  test/scripts/bridge/generate-contract-info.sh
  test/scripts/bridge/set-env.sh
  test/scripts/bridge/setup-relayer.sh
  test/scripts/bridge/start-relayer.sh
  test/suites/zombie_tanssi_relay_eth_bridge/test_zombie_tanssi_relay_eth_bridge.ts
Labels: B0-silent, D2-notlive, not-breaking

#777 Test operators appears in pallet session after bridging
  test/suites/zombie_tanssi_relay_eth_bridge/test_zombie_tanssi_relay_eth_bridge.ts
Labels: a0-pleasereview, B0-silent, D2-notlive, not-breaking

#778 Fix bridge e2e test
  test/suites/zombie_tanssi_relay_eth_bridge/test_zombie_tanssi_relay_eth_bridge.ts
Labels: B0-silent, D2-notlive, not-breaking

#761 Starlight <> Ethereum: Rewards mapping
  Cargo.lock
  Cargo.toml
  pallets/external-validators-rewards/Cargo.toml
  pallets/external-validators-rewards/runtime-api/Cargo.toml
  pallets/external-validators-rewards/runtime-api/src/lib.rs
  pallets/external-validators-rewards/src/benchmarking.rs
  pallets/external-validators-rewards/src/lib.rs
  pallets/external-validators-rewards/src/mock.rs
  pallets/external-validators-rewards/src/weights.rs
  pnpm-lock.yaml
  primitives/bridge/src/custom_do_process_message.rs
  primitives/bridge/src/lib.rs
  solo-chains/runtime/dancelight/Cargo.toml
  solo-chains/runtime/dancelight/src/lib.rs
  solo-chains/runtime/dancelight/src/tests/external_validators_tests.rs
  solo-chains/runtime/dancelight/src/weights/mod.rs
  solo-chains/runtime/dancelight/src/weights/pallet_external_validators_rewards.rs
  test/suites/dev-tanssi-relay/external-validators-rewards/test-rewards-runtime-api.ts
  typescript-api/package.json
Labels: B7-runtimenoteworthy, breaking, D5-nicetohaveaudit⚠️

#692 Combine `RemoveParaIdsWithNoCredit` and `CollatorAssignmentHook`
  pallets/collator-assignment/src/benchmarking.rs
  pallets/collator-assignment/src/lib.rs
  pallets/collator-assignment/src/mock.rs
  pallets/collator-assignment/src/tests.rs
  pallets/services-payment/src/lib.rs
  primitives/traits/src/lib.rs
  runtime/dancebox/src/lib.rs
  runtime/flashbox/src/lib.rs
  solo-chains/runtime/dancelight/src/lib.rs
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#769 Fix docker publishing with also workers
  .github/workflows/publish-docker-tannsi-relay.yml
Labels: B0-silent, D3-trivial, not-breaking

#780 Bridge test to work with sha
  .github/workflows/e2e-test-bridge.yml
Labels: a0-pleasereview, B0-silent, D3-trivial, not-breaking

#774 Add pallet_pooled_staking to Dancelight
  Cargo.lock
  runtime/dancebox/src/lib.rs
  solo-chains/runtime/dancelight/Cargo.toml
  solo-chains/runtime/dancelight/src/genesis_config_presets.rs
  solo-chains/runtime/dancelight/src/lib.rs
  solo-chains/runtime/dancelight/src/tests/collator_assignment_tests.rs
  solo-chains/runtime/dancelight/src/tests/mod.rs
  solo-chains/runtime/dancelight/src/tests/staking.rs
  solo-chains/runtime/dancelight/src/weights/mod.rs
  solo-chains/runtime/dancelight/src/weights/pallet_pooled_staking.rs
  test/suites/dev-tanssi-relay/balances/test_balances.ts
  typescript-api/src/dancelight/interfaces/augment-api-consts.ts
  typescript-api/src/dancelight/interfaces/augment-api-errors.ts
  typescript-api/src/dancelight/interfaces/augment-api-events.ts
  typescript-api/src/dancelight/interfaces/augment-api-query.ts
  typescript-api/src/dancelight/interfaces/augment-api-tx.ts
  typescript-api/src/dancelight/interfaces/lookup.ts
  typescript-api/src/dancelight/interfaces/registry.ts
  typescript-api/src/dancelight/interfaces/types-lookup.ts
Labels: B7-runtimenoteworthy, breaking, D5-nicetohaveaudit⚠️

#779 Update moonwall to 5.9.1 and add --bail=1
  pnpm-lock.yaml
  test/moonwall.config.json
  test/package.json
Labels: B0-silent, D2-notlive, D3-trivial, not-breaking

#767 Benchmark for on_container_author_noted only
  pallets/author-noting/src/benchmarks.rs
  pallets/author-noting/src/weights.rs
  pallets/inflation-rewards/src/lib.rs
  pallets/services-payment/src/lib.rs
  pallets/xcm-core-buyer/src/lib.rs
  primitives/traits/src/lib.rs
  runtime/dancebox/src/lib.rs
  runtime/dancebox/src/weights/pallet_author_noting.rs
  runtime/flashbox/src/lib.rs
  runtime/flashbox/src/weights/pallet_author_noting.rs
  solo-chains/runtime/dancelight/src/lib.rs
  solo-chains/runtime/dancelight/src/weights/pallet_author_noting.rs
Labels: a0-pleasereview, B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#785 Test operator from Ethereum bridge produces blocks
  test/configs/zombie_tanssi_relay_eth_bridge.json
  test/moonwall.config.json
  test/suites/zombie_tanssi_relay_eth_bridge/test_zombie_tanssi_relay_eth_bridge.ts
Labels: a0-pleasereview, B0-silent, D2-notlive, not-breaking

#788 change ethereum params
  solo-chains/runtime/dancelight/src/bridge_to_ethereum_config.rs
Labels: B7-runtimenoteworthy, breaking, D3-trivial

#790 Fix off-by-one in inclusion smoke test
  test/suites/smoke-test-dancelight/test-para-inclusion.ts
Labels: B0-silent, D2-notlive, not-breaking

#782 Add pallet staking tests for starlight (typescript)
  test/suites/dev-tanssi-relay/inflation-rewards/test-rewards.ts
  test/suites/dev-tanssi-relay/staking/test_staking_join.ts
  test/suites/dev-tanssi-relay/staking/test_staking_rewards_balanced.ts
  test/suites/dev-tanssi-relay/staking/test_staking_rewards_non_balanced.ts
  test/suites/dev-tanssi-relay/staking/test_staking_session.ts
  test/suites/dev-tanssi-relay/staking/test_staking_swap.ts
Labels: B0-silent, D2-notlive, not-breaking

#775 Add iforgor config and readme
  test/moonwall.config.json
  tools/iforgor/README.md
  tools/iforgor/tanssi.toml
Labels: a0-pleasereview, B0-silent, D2-notlive, not-breaking

#791 Working e2e test with symbiotic
  test/scripts/bridge-build-artifacts.sh
  test/scripts/bridge/assets/execution-relay.json
  test/scripts/bridge/assets/genesis.json
  test/scripts/bridge/build-relayer.sh
  test/scripts/bridge/build-snowbridge-contracts.sh
  test/scripts/bridge/build-symbiotic-contracts.sh
  test/scripts/bridge/deploy-ethereum-contracts.sh
  test/scripts/bridge/generate-contract-info.sh
  test/scripts/bridge/generate-eth-info.sh
  test/scripts/bridge/set-env.sh
  test/scripts/bridge/setup-relayer.sh
  test/scripts/bridge/ts-scripts/package.json
  test/scripts/bridge/ts-scripts/src/generateContractInfo.ts
  test/suites/zombie_tanssi_relay_eth_bridge/test_zombie_tanssi_relay_eth_bridge.ts
Labels: B0-silent, D2-notlive, not-breaking

#770 Allow rotating a subset of collators instead of all of them
  Cargo.lock
  Cargo.toml
  client/manual-randomness/Cargo.toml
  client/manual-randomness/src/lib.rs
  node/Cargo.toml
  node/src/chain_spec/dancebox.rs
  node/src/chain_spec/flashbox.rs
  node/src/rpc.rs
  node/src/service.rs
  pallets/collator-assignment/src/assignment.rs
  pallets/collator-assignment/src/benchmarking.rs
  pallets/collator-assignment/src/lib.rs
  pallets/collator-assignment/src/mock.rs
  pallets/collator-assignment/src/tests.rs
  pallets/collator-assignment/src/tests/keep_collator_subset.rs
  pallets/collator-assignment/src/tests/prioritize_invulnerables.rs
  pallets/collator-assignment/src/tests/select_chains.rs
  pallets/collator-assignment/src/tests/with_core_config.rs
  pallets/configuration/src/lib.rs
  primitives/traits/src/lib.rs
  runtime/common/src/migrations.rs
  runtime/dancebox/src/tests/integration_test.rs
  solo-chains/runtime/dancelight/src/tests/integration_test.rs
  solo-chains/runtime/dancelight/src/tests/mod.rs
  test/suites/dev-tanssi/collator-assignment/test-full-rotation-mode-parathreads.ts
  test/suites/dev-tanssi/collator-assignment/test-full-rotation-mode.ts
  typescript-api/src/dancebox/interfaces/augment-api-events.ts
  typescript-api/src/dancebox/interfaces/augment-api-tx.ts
  typescript-api/src/dancebox/interfaces/lookup.ts
  typescript-api/src/dancebox/interfaces/registry.ts
  typescript-api/src/dancebox/interfaces/types-lookup.ts
  typescript-api/src/dancelight/interfaces/augment-api-events.ts
  typescript-api/src/dancelight/interfaces/augment-api-tx.ts
  typescript-api/src/dancelight/interfaces/lookup.ts
  typescript-api/src/dancelight/interfaces/registry.ts
  typescript-api/src/dancelight/interfaces/types-lookup.ts
  typescript-api/src/flashbox/interfaces/augment-api-events.ts
  typescript-api/src/flashbox/interfaces/augment-api-tx.ts
  typescript-api/src/flashbox/interfaces/lookup.ts
  typescript-api/src/flashbox/interfaces/registry.ts
  typescript-api/src/flashbox/interfaces/types-lookup.ts
Labels: B7-runtimenoteworthy, breaking, D5-nicetohaveaudit⚠️

#786 Restrict governance messages to governance channel id
  primitives/bridge/src/symbiotic_message_processor.rs
  solo-chains/runtime/dancelight/src/tests/inbound_queue_tests/integration_tests.rs
  solo-chains/runtime/dancelight/src/tests/inbound_queue_tests/message_processor_tests.rs
Labels: B7-runtimenoteworthy, breaking, D3-trivial
