Repository moondance-labs/tanssi, pull requests merged in 2024-03, with the labels that each got.

#438 Increase runtime version 600
  container-chains/templates/frontier/runtime/src/lib.rs
  container-chains/templates/simple/runtime/src/lib.rs
  pnpm-lock.yaml
  runtime/dancebox/src/lib.rs
  runtime/flashbox/src/lib.rs
  test/package.json
Labels: B0-silent, D3-trivial, not-breaking

#436 Move clippy lints to Cargo.toml file and deny clippy warnings in CI
  .cargo/config.toml
  .github/scripts/check_toml_lints.sh
  .github/workflows/release.yml
  Cargo.toml
  client/consensus/Cargo.toml
  client/manual-xcm/Cargo.toml
  client/node-common/Cargo.toml
  container-chains/templates/frontier/node/Cargo.toml
  container-chains/templates/frontier/runtime/Cargo.toml
  container-chains/templates/simple/node/Cargo.toml
  container-chains/templates/simple/runtime/Cargo.toml
  node/Cargo.toml
  pallets/author-noting/Cargo.toml
  pallets/author-noting/rpc/runtime-api/Cargo.toml
  pallets/authority-assignment/Cargo.toml
  pallets/authority-mapping/Cargo.toml
  pallets/collator-assignment/Cargo.toml
  pallets/collator-assignment/rpc/runtime-api/Cargo.toml
  pallets/configuration/Cargo.toml
  pallets/data-preservers/Cargo.toml
  pallets/inflation-rewards/Cargo.toml
  pallets/initializer/Cargo.toml
  pallets/invulnerables/Cargo.toml
  pallets/pooled-staking/Cargo.toml
  pallets/registrar/Cargo.toml
  pallets/registrar/rpc/runtime-api/Cargo.toml
  pallets/services-payment/Cargo.toml
  pallets/stream-payment/Cargo.toml
  primitives/author-noting-inherent/Cargo.toml
  primitives/consensus/Cargo.toml
  primitives/container-chain-genesis-data/Cargo.toml
  primitives/impl-tanssi-pallets-config/Cargo.toml
  primitives/maths/Cargo.toml
  primitives/traits/Cargo.toml
  runtime/common/Cargo.toml
  runtime/dancebox/Cargo.toml
  runtime/flashbox/Cargo.toml
  toml-maid.toml
Labels: B0-silent, D2-notlive, not-breaking

#440 Wait for block to be finalized in signAndSendAndInclude
  test/moonwall.config.json
  test/suites/keep-db/test_restart_keep_db.ts
  test/suites/metrics/test_metrics_stop.ts
  test/suites/para/test_tanssi_containers.ts
  test/util/block.ts
Labels: B0-silent, D2-notlive, not-breaking

#437 new smoke tests
  test/configs/dancebox.yml
  test/configs/stagenet-dancebox.yml
  test/configs/stagenet-flashbox.yml
  test/moonwall.config.json
  test/suites/smoke-test-common/test-authority-consistency-assignation.ts
  test/suites/smoke-test-common/test-block-author-logs.ts
  test/suites/smoke-test-common/test-block-finalized.ts
  test/suites/smoke-test-common/test-collator-number-consistency.ts
  test/suites/smoke-test-common/test-configuration-consistency.ts
  test/suites/smoke-test-common/test-consistency-services-payment.ts
  test/suites/smoke-test-common/test-inflation-rewards.ts
  test/suites/smoke-test-common/test-relay-storage-roots-consistency.ts
  test/suites/smoke-test-dancebox/test-invulnerables-priority.ts
  test/suites/smoke-test-dancebox/test-randomness-consistency.ts
  test/suites/smoke-test-dancebox/test-staking-consistency.ts
  test/suites/smoke-test-dancebox/test-staking-session-keys.ts
Labels: B0-silent, D3-trivial, I4-tests 🎯, not-breaking

#441 Fix registration zombienet test
  test/suites/para/test_tanssi_containers.ts
Labels: B0-silent, D3-trivial, I4-tests 🎯, not-breaking

#443 new node published now we just use a different way of modifying invul
  test/scripts/modify-plain-specs.ts
Labels: a0-pleasereview, B0-silent, D3-trivial, I4-tests 🎯, not-breaking

#444 Remove unused bootnodes config from pallet_registrar
  pallets/registrar/src/lib.rs
  pallets/registrar/src/mock.rs
  runtime/dancebox/src/lib.rs
  runtime/flashbox/src/lib.rs
Labels: B0-silent, D3-trivial, not-breaking

#445 Use const syntax in thread local macro
  container-chains/templates/frontier/node/src/service.rs
  container-chains/templates/simple/node/src/service.rs
  node/src/service.rs
  pallets/initializer/src/mock.rs
Labels: B0-silent, D3-trivial, not-breaking

#449 Increase `MaxFreezes` to 10
  runtime/flashbox/src/lib.rs
Labels: B0-silent, D3-trivial, not-breaking

#447 refactor some crates to use dancekit
  Cargo.lock
  Cargo.toml
  client/consensus/Cargo.toml
  client/consensus/src/lib.rs
  client/consensus/src/manual_seal.rs
  client/consensus/src/tests.rs
  container-chains/templates/frontier/runtime/Cargo.toml
  container-chains/templates/frontier/runtime/src/lib.rs
  container-chains/templates/simple/runtime/Cargo.toml
  container-chains/templates/simple/runtime/src/lib.rs
  node/src/service.rs
  primitives/consensus/Cargo.toml
  primitives/consensus/src/lib.rs
  primitives/consensus/src/mock.rs
  primitives/impl-tanssi-pallets-config/Cargo.toml
  primitives/impl-tanssi-pallets-config/src/lib.rs
  runtime/dancebox/Cargo.toml
  runtime/dancebox/src/lib.rs
  runtime/dancebox/tests/common/mod.rs
  runtime/dancebox/tests/integration_test.rs
  runtime/flashbox/Cargo.toml
  runtime/flashbox/src/lib.rs
  runtime/flashbox/tests/common/mod.rs
  runtime/flashbox/tests/integration_test.rs
Labels: B0-silent, D3-trivial, not-breaking

#455 Avoid expect/expect_err in Pooled Staking pallet
  pallets/pooled-staking/src/candidate.rs
Labels: B0-silent, D5-nicetohaveaudit⚠️, not-breaking

#456 Limit block production to one block per slot in basic collator
  client/consensus/src/collators.rs
  client/consensus/src/collators/basic.rs
Labels: B0-silent, D3-trivial, not-breaking

#453 Use `CollatorId` instead of `AccountId` - Part 1 of N
  pallets/invulnerables/src/benchmarking.rs
  pallets/invulnerables/src/lib.rs
  runtime/dancebox/src/lib.rs
  runtime/flashbox/src/lib.rs
  typescript-api/src/dancebox/interfaces/augment-api-errors.ts
  typescript-api/src/dancebox/interfaces/lookup.ts
  typescript-api/src/dancebox/interfaces/types-lookup.ts
  typescript-api/src/flashbox/interfaces/augment-api-errors.ts
  typescript-api/src/flashbox/interfaces/lookup.ts
  typescript-api/src/flashbox/interfaces/types-lookup.ts
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#439 Add more clippy lints
  Cargo.toml
  client/consensus/src/collators.rs
  client/node-common/src/service.rs
  container-chains/templates/frontier/node/src/chain_spec.rs
  container-chains/templates/frontier/node/src/main.rs
  container-chains/templates/frontier/node/src/service.rs
  container-chains/templates/frontier/runtime/src/lib.rs
  container-chains/templates/simple/node/src/main.rs
  container-chains/templates/simple/node/src/service.rs
  container-chains/templates/simple/runtime/src/lib.rs
  docs/clippy.md
  node/src/main.rs
  node/src/service.rs
  pallets/authority-assignment/src/mock.rs
  pallets/registrar/src/mock.rs
  pallets/stream-payment/src/tests.rs
  primitives/author-noting-inherent/src/mock.rs
  runtime/dancebox/src/lib.rs
  runtime/dancebox/tests/common/mod.rs
  runtime/dancebox/tests/common/xcm/constants.rs
  runtime/flashbox/src/lib.rs
  runtime/flashbox/tests/common/mod.rs
Labels: B0-silent, D3-trivial, not-breaking

#451 Set correct FreezeIdentifier in all runtimes
  container-chains/templates/frontier/runtime/src/lib.rs
  container-chains/templates/simple/runtime/src/lib.rs
  runtime/flashbox/src/lib.rs
  typescript-api/src/flashbox/interfaces/augment-api-query.ts
  typescript-api/src/flashbox/interfaces/lookup.ts
  typescript-api/src/flashbox/interfaces/registry.ts
  typescript-api/src/flashbox/interfaces/types-lookup.ts
Labels: B0-silent, D5-nicetohaveaudit⚠️, not-breaking

#460 increase timeouts and remove collators
  test/configs/zombieTanssiParathreads.json
  test/scripts/build-spec-parathreads.sh
  test/suites/parathreads/test_tanssi_parathreads.ts
  test/suites/rotation-para/test_rotation.ts
Labels: B0-silent, D3-trivial, I4-tests 🎯, not-breaking

#446 Store slot number in author-noting
  pallets/author-noting/src/benchmarks.rs
  pallets/author-noting/src/lib.rs
  pallets/author-noting/src/mock.rs
  pallets/author-noting/src/tests.rs
  runtime/dancebox/tests/integration_test.rs
  runtime/flashbox/tests/integration_test.rs
  test/suites/common-tanssi/registrar/test_registrar_deregister.ts
  typescript-api/src/dancebox/interfaces/augment-api-events.ts
  typescript-api/src/dancebox/interfaces/augment-api-tx.ts
  typescript-api/src/dancebox/interfaces/lookup.ts
  typescript-api/src/dancebox/interfaces/types-lookup.ts
  typescript-api/src/flashbox/interfaces/augment-api-events.ts
  typescript-api/src/flashbox/interfaces/augment-api-tx.ts
  typescript-api/src/flashbox/interfaces/lookup.ts
  typescript-api/src/flashbox/interfaces/types-lookup.ts
Labels: B7-runtimenoteworthy, breaking, D5-nicetohaveaudit⚠️

#461 Push whole version as docker image tag to dockerhub
  .github/workflows/publish-docker.yml
Labels: B0-silent, ci, D3-trivial

#462 Fix smoke-tests with respect to collator assignment
  test/suites/smoke-test-common/test-configuration-consistency.ts
  test/suites/smoke-test-common/test-consistency-services-payment.ts
  test/util/payment.ts
Labels: B0-silent, D3-trivial, I4-tests 🎯, not-breaking

#464 Rename Parachain Collator Template
  container-chains/templates/frontier/node/src/command.rs
  container-chains/templates/simple/node/src/command.rs
  node/src/command.rs
Labels: B0-silent, C1-low, D3-trivial

#459 Move some logs to debug level
  pallets/collator-assignment/src/lib.rs
  runtime/dancebox/src/lib.rs
Labels: B0-silent, D3-trivial, not-breaking

#467 Update Moonkit fork Reference
  Cargo.lock
  container-chains/templates/frontier/runtime/src/lib.rs
  container-chains/templates/frontier/runtime/src/xcm_config.rs
  container-chains/templates/simple/runtime/src/lib.rs
  container-chains/templates/simple/runtime/src/xcm_config.rs
  runtime/dancebox/src/lib.rs
  runtime/dancebox/src/xcm_config.rs
  runtime/flashbox/src/lib.rs
  typescript-api/src/dancebox/interfaces/augment-api-consts.ts
  typescript-api/src/flashbox/interfaces/augment-api-consts.ts
Labels: B0-silent, D3-trivial

#465 MD364 - Adds session key management proxy type
  runtime/dancebox/src/lib.rs
  runtime/dancebox/tests/integration_test.rs
  test/suites/dev-tanssi/proxy/test-session-keys-management.ts
  typescript-api/src/dancebox/interfaces/augment-api-tx.ts
  typescript-api/src/dancebox/interfaces/lookup.ts
  typescript-api/src/dancebox/interfaces/types-lookup.ts
Labels: a0-pleasereview, B7-runtimenoteworthy, breaking, D5-nicetohaveaudit⚠️

#448 Add lookahead collator and enable async backing in all runtimes
  Cargo.lock
  Cargo.toml
  client/consensus/Cargo.toml
  client/consensus/src/collators.rs
  client/consensus/src/collators/lookahead.rs
  container-chains/templates/frontier/node/src/service.rs
  container-chains/templates/frontier/runtime/Cargo.toml
  container-chains/templates/frontier/runtime/src/lib.rs
  container-chains/templates/simple/node/src/service.rs
  container-chains/templates/simple/runtime/Cargo.toml
  container-chains/templates/simple/runtime/src/lib.rs
  node/Cargo.toml
  node/src/container_chain_spawner.rs
  node/src/service.rs
  pnpm-lock.yaml
  runtime/dancebox/Cargo.toml
  runtime/dancebox/src/lib.rs
  runtime/dancebox/tests/common/mod.rs
  runtime/flashbox/src/lib.rs
  test/configs/zombieDanceboxUpgrade.json
  test/configs/zombieTanssi.json
  test/configs/zombieTanssiKeepDb.json
  test/configs/zombieTanssiMetrics.json
  test/configs/zombieTanssiParathreads.json
  test/configs/zombieTanssiRotation.json
  test/configs/zombieTanssiWarpSync.json
  test/package.json
  test/suites/common-tanssi/services-payment/test_service_payment_removes_tank_money_and_burns.ts
  test/suites/common-tanssi/services-payment/test_service_payment_removes_tank_money_and_refunds.ts
  test/suites/common-tanssi/services-payment/test_services_payment_block_credit_buying_free_combined.ts
  test/suites/common-tanssi/services-payment/test_services_payment_block_credits.ts
  test/suites/common-tanssi/services-payment/test_services_payment_no_free_credits.ts
  test/suites/dev-tanssi/staking/test_staking_join.ts
  test/suites/dev-tanssi/staking/test_staking_rewards_balanced.ts
  test/suites/dev-tanssi/staking/test_staking_rewards_non_balanced.ts
  test/suites/dev-tanssi/staking/test_staking_session.ts
  test/suites/dev-tanssi/staking/test_staking_swap.ts
  test/suites/para/test_tanssi_containers.ts
  test/suites/rotation-para/test_rotation.ts
Labels: a0-pleasereview, B7-runtimenoteworthy, breaking, D9-needsaudit👮

#468 Update Packages
  .github/workflow-templates/cargo-build/action.yml
  .github/workflow-templates/typescript-tests-moonwall/action.yml
  .github/workflows/client-release-issue.yml
  .github/workflows/coverage.yml
  .github/workflows/prepare-binary.yml
  .github/workflows/publish-binary.yml
  .github/workflows/publish-docker-runtime-containers.yml
  .github/workflows/publish-docker-runtime-tanssi.yml
  .github/workflows/publish-docker.yml
  .github/workflows/publish-runtime-chevdor.yml
  .github/workflows/publish-runtime.yml
  .github/workflows/publish-typescript-api.yml
  .github/workflows/release.yml
  .github/workflows/runtime-release-issue.yml
  .github/workflows/upgrade-typescript-api.yml
  .github/workflows/version-bump.yml
  pnpm-lock.yaml
  test/package.json
Labels: B0-silent, D2-notlive

#469 chore(ci): improve dev test duration by not compiling wasm on startup
  test/moonwall.config.json
  test/scripts/compile-wasm.ts
Labels: B0-silent, D3-trivial, not-breaking

#470 Implement custom slot duration runtime api for runtimes
  Cargo.lock
  Cargo.toml
  container-chains/templates/frontier/runtime/Cargo.toml
  container-chains/templates/frontier/runtime/src/lib.rs
  container-chains/templates/simple/runtime/Cargo.toml
  container-chains/templates/simple/runtime/src/lib.rs
  node/Cargo.toml
  node/src/service.rs
  runtime/dancebox/Cargo.toml
  runtime/dancebox/src/lib.rs
  runtime/flashbox/Cargo.toml
  runtime/flashbox/src/lib.rs
Labels: B5-clientnoteworthy, B7-runtimenoteworthy, breaking, D3-trivial

#473 make basic collator aware of last included block [Backport to 0.5.2]
  Cargo.lock
  client/consensus/src/collators/basic.rs
  container-chains/templates/frontier/node/Cargo.toml
  container-chains/templates/simple/node/Cargo.toml
  node/Cargo.toml
Labels: B5-clientnoteworthy, D3-trivial, not-breaking

#472 make basic collator aware of last included block
  client/consensus/src/collators/basic.rs
Labels: B5-clientnoteworthy, D3-trivial, not-breaking

#471 Shuffle only top N collators to respect staking priority
  pallets/collator-assignment/src/assignment.rs
  pallets/collator-assignment/src/lib.rs
  pallets/collator-assignment/src/tests.rs
  pallets/collator-assignment/src/tests/assign_full.rs
Labels: B7-runtimenoteworthy, breaking, D5-nicetohaveaudit⚠️

#477 Fix use of current max_collators instead of pending
  pallets/collator-assignment/src/lib.rs
  pallets/collator-assignment/src/mock.rs
  pallets/configuration/src/lib.rs
  primitives/traits/src/lib.rs
  runtime/dancebox/src/lib.rs
  runtime/dancebox/tests/integration_test.rs
  runtime/flashbox/src/lib.rs
  runtime/flashbox/tests/integration_test.rs
Labels: B7-runtimenoteworthy, breaking, D5-nicetohaveaudit⚠️

#480 Fix flashbox and dancebox smoke test
  test/suites/smoke-test-common/test-configuration-consistency.ts
  test/suites/smoke-test-dancebox/test-invulnerables-priority.ts
  test/suites/smoke-test-dancebox/test-staking-consistency.ts
Labels: bug, B0-silent, D2-notlive, D3-trivial, not-breaking

#463 Use `SlowAdjustingFeeUpdate` instead of `ConstFeeMultiplier`
  container-chains/templates/frontier/runtime/src/lib.rs
  container-chains/templates/simple/runtime/src/lib.rs
  runtime/dancebox/src/lib.rs
  runtime/dancebox/tests/common/mod.rs
  runtime/dancebox/tests/integration_test.rs
  runtime/flashbox/src/lib.rs
  runtime/flashbox/tests/common/mod.rs
  runtime/flashbox/tests/integration_test.rs
  test/suites/common-all/fee_balance_transfer/test_fee_balance_transfer.ts
  test/suites/common-tanssi/fees/test_fee_burning.ts
  test/suites/dev-tanssi/staking/test_staking_rewards_balanced.ts
  test/suites/dev-tanssi/staking/test_staking_rewards_non_balanced.ts
  test/util/block.ts
Labels: B7-runtimenoteworthy, breaking, D3-breaksconsensus, D3-trivial

#466 Tests reserve transfers
  Cargo.lock
  runtime/dancebox/tests/common/xcm/mocknets.rs
  runtime/dancebox/tests/common/xcm/mod.rs
  runtime/dancebox/tests/common/xcm/reserver_transfers_polkadot_xcm.rs
Labels: a0-pleasereview, B0-silent, D3-trivial, I4-tests 🎯, not-breaking
