Repository moondance-labs/tanssi, pull requests merged in 2024-01, with the labels that each got.

#376 Prepare runtimes and dev services for future async backing support
  Cargo.lock
  Cargo.toml
  container-chains/templates/frontier/node/Cargo.toml
  container-chains/templates/frontier/node/src/service.rs
  container-chains/templates/frontier/runtime/Cargo.toml
  container-chains/templates/frontier/runtime/src/lib.rs
  container-chains/templates/simple/node/Cargo.toml
  container-chains/templates/simple/node/src/service.rs
  container-chains/templates/simple/runtime/Cargo.toml
  container-chains/templates/simple/runtime/src/lib.rs
  node/Cargo.toml
  node/src/service.rs
  primitives/consensus/src/lib.rs
  runtime/dancebox/Cargo.toml
  runtime/dancebox/src/lib.rs
  runtime/dancebox/tests/common/mod.rs
  runtime/dancebox/tests/common/xcm/mocknets.rs
  runtime/dancebox/tests/integration_test.rs
  runtime/flashbox/Cargo.toml
  runtime/flashbox/src/lib.rs
  runtime/flashbox/tests/common/mod.rs
  typescript-api/src/dancebox/interfaces/augment-api-query.ts
  typescript-api/src/dancebox/interfaces/lookup.ts
  typescript-api/src/dancebox/interfaces/types-lookup.ts
  typescript-api/src/flashbox/interfaces/augment-api-query.ts
  typescript-api/src/flashbox/interfaces/lookup.ts
  typescript-api/src/flashbox/interfaces/types-lookup.ts
Labels: B7-runtimenoteworthy, not-breaking

#379 release flashbox job
  .github/workflows/publish-runtime.yml
  tools/github/generate-runtimes-body.ts
Labels: a0-pleasereview, B0-silent, not-breaking

#380 Flashbox migrations
  runtime/flashbox/src/lib.rs
  runtime/flashbox/src/migrations.rs
Labels: B7-runtimenoteworthy, not-breaking

#383 MD258 - add pallet identity
  Cargo.lock
  Cargo.toml
  runtime/dancebox/Cargo.toml
  runtime/dancebox/src/lib.rs
  runtime/flashbox/Cargo.toml
  runtime/flashbox/src/lib.rs
  test/suites/common-tanssi/pallet-identity/test_pallet_identity.ts
  typescript-api/src/dancebox/interfaces/augment-api-consts.ts
  typescript-api/src/dancebox/interfaces/augment-api-errors.ts
  typescript-api/src/dancebox/interfaces/augment-api-events.ts
  typescript-api/src/dancebox/interfaces/augment-api-query.ts
  typescript-api/src/dancebox/interfaces/augment-api-tx.ts
  typescript-api/src/dancebox/interfaces/lookup.ts
  typescript-api/src/dancebox/interfaces/registry.ts
  typescript-api/src/dancebox/interfaces/types-lookup.ts
  typescript-api/src/flashbox/interfaces/augment-api-consts.ts
  typescript-api/src/flashbox/interfaces/augment-api-errors.ts
  typescript-api/src/flashbox/interfaces/augment-api-events.ts
  typescript-api/src/flashbox/interfaces/augment-api-query.ts
  typescript-api/src/flashbox/interfaces/augment-api-tx.ts
  typescript-api/src/flashbox/interfaces/lookup.ts
  typescript-api/src/flashbox/interfaces/registry.ts
  typescript-api/src/flashbox/interfaces/types-lookup.ts
Labels: a0-pleasereview, B7-runtimenoteworthy, not-breaking

#384 Change default para id for templates
  container-chains/templates/frontier/node/src/command.rs
  container-chains/templates/simple/node/src/command.rs
  test/moonwall.config.json
Labels: B0-silent, D3-trivial, not-breaking

#370 Add pallet relay storage roots
  Cargo.lock
  Cargo.toml
  runtime/dancebox/Cargo.toml
  runtime/dancebox/src/lib.rs
  runtime/flashbox/Cargo.toml
  runtime/flashbox/src/lib.rs
  test/suites/common-tanssi/relay-storage-roots/test_pallet_storage_roots.ts
  typescript-api/src/dancebox/interfaces/augment-api-consts.ts
  typescript-api/src/dancebox/interfaces/augment-api-query.ts
  typescript-api/src/dancebox/interfaces/lookup.ts
  typescript-api/src/dancebox/interfaces/types-lookup.ts
  typescript-api/src/flashbox/interfaces/augment-api-consts.ts
  typescript-api/src/flashbox/interfaces/augment-api-query.ts
  typescript-api/src/flashbox/interfaces/lookup.ts
  typescript-api/src/flashbox/interfaces/types-lookup.ts
Labels: B7-runtimenoteworthy, breaking

#360 Assets xcm
  Cargo.lock
  Cargo.toml
  runtime/dancebox/Cargo.toml
  runtime/dancebox/src/lib.rs
  runtime/dancebox/src/xcm_config.rs
  runtime/dancebox/tests/common/mod.rs
  runtime/dancebox/tests/common/xcm/mocknets.rs
  runtime/dancebox/tests/common/xcm/mod.rs
  runtime/dancebox/tests/common/xcm/token_derivative_reception_container.rs
  runtime/dancebox/tests/common/xcm/token_derivative_reception_relay.rs
  runtime/dancebox/tests/integration_test.rs
  test/suites/dev-tanssi/xcm-token-reception/test_dmp_token_reception.ts
  test/suites/dev-tanssi/xcm-token-reception/test_dmp_token_reception_appendix.ts
  test/suites/dev-tanssi/xcm-token-reception/test_dmp_token_reception_appendix_2.ts
  test/suites/dev-tanssi/xcm-token-reception/test_dmp_token_reception_error_handler.ts
  test/suites/dev-tanssi/xcm-token-reception/test_dmp_token_reception_error_handler_2.ts
  test/suites/dev-tanssi/xcm-token-reception/test_hrmp_token_reception.ts
  test/suites/dev-tanssi/xcm-token-reception/test_hrmp_token_reception_2.ts
  test/util/constants.ts
  typescript-api/src/dancebox/interfaces/augment-api-consts.ts
  typescript-api/src/dancebox/interfaces/augment-api-errors.ts
  typescript-api/src/dancebox/interfaces/augment-api-events.ts
  typescript-api/src/dancebox/interfaces/augment-api-query.ts
  typescript-api/src/dancebox/interfaces/augment-api-tx.ts
  typescript-api/src/dancebox/interfaces/lookup.ts
  typescript-api/src/dancebox/interfaces/registry.ts
  typescript-api/src/dancebox/interfaces/types-lookup.ts
Labels: a0-pleasereview, B7-runtimenoteworthy, breaking

#389 Refactor of benchmarks to run all pallets for all runtimes
  Cargo.lock
  container-chains/templates/frontier/runtime/Cargo.toml
  container-chains/templates/frontier/runtime/src/lib.rs
  container-chains/templates/simple/runtime/Cargo.toml
  container-chains/templates/simple/runtime/src/lib.rs
  primitives/consensus/Cargo.toml
  primitives/consensus/src/lib.rs
  runtime/dancebox/Cargo.toml
  runtime/dancebox/src/lib.rs
  runtime/flashbox/Cargo.toml
  runtime/flashbox/src/lib.rs
  tools/benchmarking-template-simple.sh
  tools/benchmarking.sh
Labels: a0-pleasereview, B7-runtimenoteworthy, breaking

#390 Add new params to configuration: parathreads and target_fullness
  node/src/chain_spec/dancebox.rs
  node/src/chain_spec/flashbox.rs
  pallets/configuration/src/lib.rs
  pallets/configuration/src/tests.rs
  runtime/dancebox/src/migrations.rs
  runtime/dancebox/tests/integration_test.rs
  runtime/flashbox/src/lib.rs
  runtime/flashbox/src/migrations.rs
  runtime/flashbox/tests/integration_test.rs
  test/suites/common-tanssi/pallet-configuration/test-active-config-target-fullness.ts
  typescript-api/src/dancebox/interfaces/augment-api-tx.ts
  typescript-api/src/dancebox/interfaces/lookup.ts
  typescript-api/src/dancebox/interfaces/types-lookup.ts
  typescript-api/src/flashbox/interfaces/augment-api-tx.ts
  typescript-api/src/flashbox/interfaces/lookup.ts
  typescript-api/src/flashbox/interfaces/types-lookup.ts
Labels: B7-runtimenoteworthy, breaking

#385 Rewrite collator assignment to support parathreads
  pallets/collator-assignment/src/assignment.rs
  pallets/collator-assignment/src/lib.rs
  pallets/collator-assignment/src/mock.rs
  pallets/collator-assignment/src/tests.rs
  pallets/collator-assignment/src/tests/assign_full.rs
  pallets/collator-assignment/src/tests/prioritize_invulnerables.rs
  pallets/collator-assignment/src/tests/select_chains.rs
  pallets/configuration/src/lib.rs
  pallets/registrar/src/lib.rs
  primitives/traits/src/lib.rs
  runtime/dancebox/tests/integration_test.rs
  runtime/flashbox/tests/integration_test.rs
  test/scripts/build-spec-warp-sync.sh
  test/scripts/build-spec.sh
  test/suites/dev-tanssi/session-keys/test_remove_session_key_staking.ts
  test/suites/dev-tanssi/staking/test_staking_rewards_balanced.ts
  test/suites/dev-tanssi/staking/test_staking_rewards_non_balanced.ts
Labels: B7-runtimenoteworthy, breaking

#394 Avoid error log "ZeroCollators" when running cargo test
  Cargo.lock
  Cargo.toml
  pallets/collator-assignment/Cargo.toml
  pallets/collator-assignment/src/mock.rs
  pallets/collator-assignment/src/tests.rs
Labels: B0-silent, D2-notlive, not-breaking

#397 update runtimes to 500
  container-chains/templates/frontier/runtime/src/lib.rs
  container-chains/templates/simple/runtime/src/lib.rs
  runtime/dancebox/src/lib.rs
  runtime/flashbox/src/lib.rs
Labels: B0-silent, not-breaking
