Repository moondance-labs/tanssi, pull requests merged in 2024-02, with the labels that each got.

#393 Support parathread registration and collator assignment
  Cargo.lock
  pallets/collator-assignment/src/lib.rs
  pallets/collator-assignment/src/mock.rs
  pallets/collator-assignment/src/tests.rs
  pallets/configuration/src/lib.rs
  pallets/registrar/src/benchmarks.rs
  pallets/registrar/src/lib.rs
  pallets/registrar/src/tests.rs
  pallets/registrar/src/weights.rs
  primitives/traits/Cargo.toml
  primitives/traits/src/lib.rs
  runtime/dancebox/src/lib.rs
  runtime/dancebox/tests/integration_test.rs
  runtime/flashbox/src/lib.rs
  runtime/flashbox/tests/integration_test.rs
  test/suites/common-tanssi/registrar/test_registrar_deregister.ts
  test/suites/common-tanssi/registrar/test_registrar_register_parathread.ts
  typescript-api/src/dancebox/interfaces/augment-api-errors.ts
  typescript-api/src/dancebox/interfaces/augment-api-events.ts
  typescript-api/src/dancebox/interfaces/augment-api-query.ts
  typescript-api/src/dancebox/interfaces/augment-api-tx.ts
  typescript-api/src/dancebox/interfaces/lookup.ts
  typescript-api/src/dancebox/interfaces/registry.ts
  typescript-api/src/dancebox/interfaces/types-lookup.ts
  typescript-api/src/flashbox/interfaces/augment-api-errors.ts
  typescript-api/src/flashbox/interfaces/augment-api-events.ts
  typescript-api/src/flashbox/interfaces/augment-api-query.ts
  typescript-api/src/flashbox/interfaces/augment-api-tx.ts
  typescript-api/src/flashbox/interfaces/lookup.ts
  typescript-api/src/flashbox/interfaces/registry.ts
  typescript-api/src/flashbox/interfaces/types-lookup.ts
Labels: B7-runtimenoteworthy, breaking

#392 Girazoki change payment to tank model
  pallets/services-payment/Cargo.toml
  pallets/services-payment/src/benchmarks.rs
  pallets/services-payment/src/lib.rs
  pallets/services-payment/src/mock.rs
  pallets/services-payment/src/tests.rs
  pallets/services-payment/src/weights.rs
  runtime/dancebox/src/lib.rs
  runtime/dancebox/tests/common/mod.rs
  runtime/dancebox/tests/integration_test.rs
  runtime/flashbox/src/lib.rs
  runtime/flashbox/tests/common/mod.rs
  runtime/flashbox/tests/integration_test.rs
  test/suites/common-tanssi/services-payment/test_service_payment_removes_tank_money.ts
  test/suites/common-tanssi/services-payment/test_services_pament_credit_buying_free_combined.ts
  test/suites/common-tanssi/services-payment/test_services_payment.ts
  test/suites/dev-tanssi/weights/test_set_latest_author_data_weight.ts
  test/suites/para/test_tanssi_containers.ts
  test/util/payment.ts
  typescript-api/src/dancebox/interfaces/augment-api-events.ts
  typescript-api/src/dancebox/interfaces/augment-api-tx.ts
  typescript-api/src/dancebox/interfaces/lookup.ts
  typescript-api/src/dancebox/interfaces/types-lookup.ts
  typescript-api/src/flashbox/interfaces/augment-api-events.ts
  typescript-api/src/flashbox/interfaces/augment-api-tx.ts
  typescript-api/src/flashbox/interfaces/lookup.ts
  typescript-api/src/flashbox/interfaces/types-lookup.ts
Labels: B7-runtimenoteworthy, breaking

#403 Remove Pallet DynamicFee from Frontier Template
  Cargo.lock
  Cargo.toml
  container-chains/templates/frontier/node/src/chain_spec.rs
  container-chains/templates/frontier/runtime/Cargo.toml
  container-chains/templates/frontier/runtime/src/lib.rs
Labels: a0-pleasereview, B7-runtimenoteworthy, not-breaking

#404 use chopsticks 0.9.9.1
  pnpm-lock.yaml
  test/package.json
Labels: B0-silent, not-breaking

#400 MD 306 - add pallet treasury
  Cargo.lock
  Cargo.toml
  node/src/chain_spec/dancebox.rs
  node/src/chain_spec/flashbox.rs
  pallets/collator-assignment/src/tests.rs
  pallets/collator-assignment/src/tests/assign_full.rs
  runtime/dancebox/Cargo.toml
  runtime/dancebox/src/lib.rs
  runtime/dancebox/src/xcm_config.rs
  runtime/flashbox/Cargo.toml
  runtime/flashbox/src/lib.rs
  test/suites/common-tanssi/fees/test_fee_balance_transfer.ts
  test/suites/common-tanssi/pallet-treasury/test_pallet_treasury.ts
  typescript-api/src/dancebox/interfaces/augment-api-consts.ts
  typescript-api/src/dancebox/interfaces/augment-api-errors.ts
  typescript-api/src/dancebox/interfaces/augment-api-events.ts
  typescript-api/src/dancebox/interfaces/augment-api-query.ts
  typescript-api/src/dancebox/interfaces/augment-api-tx.ts
  typescript-api/src/dancebox/interfaces/lookup.ts
  typescript-api/src/dancebox/interfaces/registry.ts
  typescript-api/src/dancebox/interfaces/types-lookup.ts
  typescript-api/src/flashbox/interfaces/augment-api-consts.ts
  typescript-api/src/flashbox/interfaces/augment-api-errors.ts
  typescript-api/src/flashbox/interfaces/augment-api-events.ts
  typescript-api/src/flashbox/interfaces/augment-api-query.ts
  typescript-api/src/flashbox/interfaces/augment-api-tx.ts
  typescript-api/src/flashbox/interfaces/lookup.ts
  typescript-api/src/flashbox/interfaces/registry.ts
  typescript-api/src/flashbox/interfaces/types-lookup.ts
Labels: B7-runtimenoteworthy, breaking

#405 check keys registered in add_invulnerable too
  pallets/invulnerables/src/benchmarking.rs
  pallets/invulnerables/src/lib.rs
  pallets/invulnerables/src/tests.rs
  pallets/invulnerables/src/weights.rs
  typescript-api/src/dancebox/interfaces/augment-api-errors.ts
  typescript-api/src/dancebox/interfaces/lookup.ts
  typescript-api/src/dancebox/interfaces/types-lookup.ts
  typescript-api/src/flashbox/interfaces/augment-api-errors.ts
  typescript-api/src/flashbox/interfaces/lookup.ts
  typescript-api/src/flashbox/interfaces/types-lookup.ts
Labels: B7-runtimenoteworthy, not-breaking

#407 Re-work client tests
  Cargo.lock
  Cargo.toml
  client/consensus/Cargo.toml
  client/consensus/src/collators.rs
  client/consensus/src/collators/basic.rs
  client/consensus/src/tests.rs
Labels: B0-silent, not-breaking

#409 remove start relay chain tasks duplicated
  node/src/service.rs
Labels: B5-clientnoteworthy, not-breaking

#410 start_relay_chain_tasks for full nodes as well
  node/src/service.rs
Labels: B5-clientnoteworthy, not-breaking

#402 Implement on demand block production
  .github/workflows/release.yml
  Cargo.lock
  client/consensus/Cargo.toml
  client/consensus/src/collators.rs
  client/consensus/src/collators/basic.rs
  client/consensus/src/consensus_orchestrator.rs
  client/consensus/src/lib.rs
  client/consensus/src/tests.rs
  node/src/service.rs
  pallets/registrar/rpc/runtime-api/src/lib.rs
  runtime/dancebox/src/lib.rs
  test/configs/zombieTanssiParathreads.json
  test/moonwall.config.json
  test/scripts/build-spec-parathreads.sh
  test/scripts/sudoRegisterPara.ts
  test/suites/parathreads/test_tanssi_parathreads.ts
Labels: B5-clientnoteworthy, B7-runtimenoteworthy, breaking

#406 Refund address to services-payment
  pallets/services-payment/src/benchmarks.rs
  pallets/services-payment/src/lib.rs
  pallets/services-payment/src/mock.rs
  pallets/services-payment/src/tests.rs
  pallets/services-payment/src/weights.rs
  runtime/dancebox/src/lib.rs
  runtime/flashbox/src/lib.rs
  test/suites/common-tanssi/services-payment/test_service_payment_removes_tank_money_and_burns.ts
  test/suites/common-tanssi/services-payment/test_service_payment_removes_tank_money_and_refunds.ts
  test/suites/parathreads/test_tanssi_parathreads.ts
  typescript-api/src/dancebox/interfaces/augment-api-events.ts
  typescript-api/src/dancebox/interfaces/augment-api-query.ts
  typescript-api/src/dancebox/interfaces/augment-api-tx.ts
  typescript-api/src/dancebox/interfaces/lookup.ts
  typescript-api/src/dancebox/interfaces/types-lookup.ts
  typescript-api/src/flashbox/interfaces/augment-api-events.ts
  typescript-api/src/flashbox/interfaces/augment-api-query.ts
  typescript-api/src/flashbox/interfaces/augment-api-tx.ts
  typescript-api/src/flashbox/interfaces/lookup.ts
  typescript-api/src/flashbox/interfaces/types-lookup.ts
Labels: B7-runtimenoteworthy, breaking

#412 Always use wasm executor in container collators
  client/node-common/src/service.rs
  container-chains/templates/frontier/node/src/service.rs
  container-chains/templates/simple/node/src/service.rs
  node/src/container_chain_monitor.rs
  node/src/service.rs
Labels: B5-clientnoteworthy, breaking

#391 Stream Payment pallet
  Cargo.lock
  Cargo.toml
  client/consensus/src/collators.rs
  client/consensus/src/collators/basic.rs
  client/consensus/src/consensus_orchestrator.rs
  client/consensus/src/lib.rs
  pallets/collator-assignment/src/assignment.rs
  pallets/registrar/src/lib.rs
  pallets/stream-payment/Cargo.toml
  pallets/stream-payment/README.md
  pallets/stream-payment/src/benchmarking.rs
  pallets/stream-payment/src/lib.rs
  pallets/stream-payment/src/mock.rs
  pallets/stream-payment/src/tests.rs
  pallets/stream-payment/src/weights.rs
  runtime/dancebox/Cargo.toml
  runtime/dancebox/src/lib.rs
  runtime/dancebox/tests/integration_test.rs
  runtime/flashbox/Cargo.toml
  runtime/flashbox/src/lib.rs
  test/suites/dev-tanssi/stream-payment/test_stream_payment.ts
  typescript-api/src/dancebox/interfaces/augment-api-errors.ts
  typescript-api/src/dancebox/interfaces/augment-api-events.ts
  typescript-api/src/dancebox/interfaces/augment-api-query.ts
  typescript-api/src/dancebox/interfaces/augment-api-tx.ts
  typescript-api/src/dancebox/interfaces/lookup.ts
  typescript-api/src/dancebox/interfaces/registry.ts
  typescript-api/src/dancebox/interfaces/types-lookup.ts
  typescript-api/src/flashbox/interfaces/augment-api-errors.ts
  typescript-api/src/flashbox/interfaces/augment-api-events.ts
  typescript-api/src/flashbox/interfaces/augment-api-query.ts
  typescript-api/src/flashbox/interfaces/augment-api-tx.ts
  typescript-api/src/flashbox/interfaces/lookup.ts
  typescript-api/src/flashbox/interfaces/registry.ts
  typescript-api/src/flashbox/interfaces/types-lookup.ts
Labels: B7-runtimenoteworthy, not-breaking

#401 Add collator assignment payment
  Cargo.lock
  Cargo.toml
  node/src/chain_spec/dancebox.rs
  node/src/chain_spec/flashbox.rs
  pallets/collator-assignment/src/lib.rs
  pallets/collator-assignment/src/mock.rs
  pallets/services-payment/Cargo.toml
  pallets/services-payment/src/benchmarks.rs
  pallets/services-payment/src/lib.rs
  pallets/services-payment/src/mock.rs
  pallets/services-payment/src/tests.rs
  pallets/services-payment/src/weights.rs
  primitives/traits/src/lib.rs
  runtime/common/Cargo.toml
  runtime/common/src/lib.rs
  runtime/common/src/migrations.rs
  runtime/dancebox/Cargo.toml
  runtime/dancebox/src/lib.rs
  runtime/dancebox/tests/common/mod.rs
  runtime/dancebox/tests/integration_test.rs
  runtime/flashbox/Cargo.toml
  runtime/flashbox/src/lib.rs
  runtime/flashbox/src/migrations.rs
  runtime/flashbox/tests/common/mod.rs
  runtime/flashbox/tests/integration_test.rs
  test/suites/common-tanssi/services-payment/test_service_payment_removes_tank_money_and_burns.ts
  test/suites/common-tanssi/services-payment/test_service_payment_removes_tank_money_and_refunds.ts
  test/suites/common-tanssi/services-payment/test_services_payment_block_credit_buying_free_combined.ts
  test/suites/common-tanssi/services-payment/test_services_payment_block_credits.ts
  test/suites/common-tanssi/services-payment/test_services_payment_collator_credit_buying_free_combined.ts
  test/suites/common-tanssi/services-payment/test_services_payment_collator_credits.ts
  test/suites/common-tanssi/services-payment/test_services_payment_no_free_credits.ts
  typescript-api/src/dancebox/interfaces/augment-api-events.ts
  typescript-api/src/dancebox/interfaces/augment-api-query.ts
  typescript-api/src/dancebox/interfaces/augment-api-tx.ts
  typescript-api/src/dancebox/interfaces/lookup.ts
  typescript-api/src/dancebox/interfaces/types-lookup.ts
  typescript-api/src/flashbox/interfaces/augment-api-events.ts
  typescript-api/src/flashbox/interfaces/augment-api-query.ts
  typescript-api/src/flashbox/interfaces/augment-api-tx.ts
  typescript-api/src/flashbox/interfaces/lookup.ts
  typescript-api/src/flashbox/interfaces/types-lookup.ts
Labels: B7-runtimenoteworthy, breaking

#416 `impl_tanssi_pallets_config!` macro for container chains
  Cargo.lock
  Cargo.toml
  container-chains/templates/frontier/runtime/Cargo.toml
  container-chains/templates/frontier/runtime/src/lib.rs
  container-chains/templates/simple/runtime/Cargo.toml
  container-chains/templates/simple/runtime/src/lib.rs
  primitives/impl-tanssi-pallets-config/Cargo.toml
  primitives/impl-tanssi-pallets-config/src/lib.rs
Labels: B7-runtimenoteworthy, not-breaking

#421 upgrade moonwall to 5.0.0
  pnpm-lock.yaml
  test/package.json
  test/suites/rt-upgrade-chopsticks-frontier-template/test-upgrade-chain.ts
  test/suites/rt-upgrade-chopsticks-orchestrator/test-upgrade-chain.ts
Labels: a0-pleasereview, B0-silent, not-breaking

#411 Xcm assets into container runtimes
  Cargo.lock
  container-chains/templates/frontier/runtime/Cargo.toml
  container-chains/templates/frontier/runtime/src/lib.rs
  container-chains/templates/frontier/runtime/src/xcm_config.rs
  container-chains/templates/simple/runtime/Cargo.toml
  container-chains/templates/simple/runtime/src/lib.rs
  container-chains/templates/simple/runtime/src/xcm_config.rs
  runtime/dancebox/Cargo.toml
  runtime/dancebox/src/lib.rs
  runtime/dancebox/src/xcm_config.rs
  runtime/dancebox/tests/common/xcm/mocknets.rs
  runtime/dancebox/tests/common/xcm/mod.rs
  runtime/dancebox/tests/common/xcm/token_derivative_reception_container_dancebox.rs
  runtime/dancebox/tests/common/xcm/token_derivative_reception_dancebox_frontier_container.rs
  runtime/dancebox/tests/common/xcm/token_derivative_reception_dancebox_simple_container.rs
  runtime/dancebox/tests/common/xcm/token_derivative_reception_relay_dancebox.rs
  runtime/dancebox/tests/common/xcm/token_derivative_reception_relay_frontier_container.rs
  runtime/dancebox/tests/common/xcm/token_derivative_reception_relay_simple_container.rs
  runtime/dancebox/tests/integration_test.rs
  test/suites/common-xcm/xcm-token-reception/test_dmp_token_reception.ts
  test/suites/common-xcm/xcm-token-reception/test_dmp_token_reception_appendix.ts
  test/suites/common-xcm/xcm-token-reception/test_dmp_token_reception_appendix_2.ts
  test/suites/common-xcm/xcm-token-reception/test_dmp_token_reception_error_handler.ts
  test/suites/common-xcm/xcm-token-reception/test_dmp_token_reception_error_handler_2.ts
  test/suites/common-xcm/xcm-token-reception/test_hrmp_token_reception.ts
  test/suites/common-xcm/xcm-token-reception/test_hrmp_token_reception_2.ts
  typescript-api/src/dancebox/interfaces/augment-api-errors.ts
  typescript-api/src/dancebox/interfaces/lookup.ts
  typescript-api/src/dancebox/interfaces/types-lookup.ts
Labels: B7-runtimenoteworthy, breaking

#414 Refactor collate_on_tanssi closure, make it not async
  node/src/container_chain_spawner.rs
  node/src/service.rs
Labels: B5-clientnoteworthy, not-breaking

#426 Use precompiled wasm in dev tests
  Cargo.lock
  client/node-common/src/service.rs
  container-chains/templates/frontier/node/src/cli.rs
  container-chains/templates/frontier/node/src/command.rs
  container-chains/templates/simple/node/src/cli.rs
  container-chains/templates/simple/node/src/command.rs
  node/src/cli.rs
  node/src/command.rs
  test/.gitignore
  test/moonwall.config.json
  test/scripts/compile-wasm.ts
Labels: B5-clientnoteworthy, breaking

#428 Use wasmtime-precompiled in zombienet tests
  node/src/service.rs
  test/configs/zombieTanssi.json
  test/configs/zombieTanssiKeepDb.json
  test/configs/zombieTanssiMetrics.json
  test/configs/zombieTanssiParathreads.json
  test/configs/zombieTanssiRotation.json
  test/configs/zombieTanssiWarpSync.json
  test/moonwall.config.json
Labels: B5-clientnoteworthy, breaking

#424 MD335 - adds pallet multisig to dancebox/flashbox
  Cargo.lock
  Cargo.toml
  container-chains/templates/frontier/runtime/Cargo.toml
  container-chains/templates/frontier/runtime/src/lib.rs
  container-chains/templates/simple/runtime/Cargo.toml
  container-chains/templates/simple/runtime/src/lib.rs
  runtime/dancebox/Cargo.toml
  runtime/dancebox/src/lib.rs
  runtime/flashbox/Cargo.toml
  runtime/flashbox/src/lib.rs
  test/suites/common-all/pallet-multisig/test_pallet_multisig.ts
  typescript-api/src/dancebox/interfaces/augment-api-consts.ts
  typescript-api/src/dancebox/interfaces/augment-api-errors.ts
  typescript-api/src/dancebox/interfaces/augment-api-events.ts
  typescript-api/src/dancebox/interfaces/augment-api-query.ts
  typescript-api/src/dancebox/interfaces/augment-api-tx.ts
  typescript-api/src/dancebox/interfaces/lookup.ts
  typescript-api/src/dancebox/interfaces/registry.ts
  typescript-api/src/dancebox/interfaces/types-lookup.ts
  typescript-api/src/flashbox/interfaces/augment-api-consts.ts
  typescript-api/src/flashbox/interfaces/augment-api-errors.ts
  typescript-api/src/flashbox/interfaces/augment-api-events.ts
  typescript-api/src/flashbox/interfaces/augment-api-query.ts
  typescript-api/src/flashbox/interfaces/augment-api-tx.ts
  typescript-api/src/flashbox/interfaces/lookup.ts
  typescript-api/src/flashbox/interfaces/registry.ts
  typescript-api/src/flashbox/interfaces/types-lookup.ts
Labels: B7-runtimenoteworthy, breaking

#429 checks on min_orchestrator_collators
  pallets/configuration/src/lib.rs
  pallets/configuration/src/tests.rs
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#422 Add support for assets-erc20 precompile
  Cargo.lock
  Cargo.toml
  container-chains/templates/frontier/runtime/Cargo.toml
  container-chains/templates/frontier/runtime/src/precompiles.rs
  container-chains/templates/frontier/runtime/src/xcm_config.rs
  test/contracts/solidity/ERC20Instance.sol
  test/helpers/assets.ts
  test/suites/dev-frontier-template/test-precompiles/test-precompile-assets-erc20-1.ts
  test/suites/dev-frontier-template/test-precompiles/test-precompile-assets-erc20-2.ts
  test/suites/dev-frontier-template/test-precompiles/test-precompile-assets-erc20-3.ts
  test/suites/dev-frontier-template/test-precompiles/test-precompile-assets-erc20-4.ts
  test/suites/dev-frontier-template/test-precompiles/test-precompile-assets-erc20-5.ts
  test/suites/dev-frontier-template/test-precompiles/test-precompile-assets-erc20-6.ts
  test/suites/dev-frontier-template/test-precompiles/test-precompile-assets-erc20-7.ts
  test/suites/dev-frontier-template/test-precompiles/test-precompile-assets-erc20-low-level.ts
Labels: B7-runtimenoteworthy, breaking

#430 copy all binaries to docker image
  docker/container-chain-evm-template.Dockerfile
  docker/container-chain-simple-template.Dockerfile
  docker/tanssi.Dockerfile
Labels: B0-silent, not-breaking

#427 XcmExecutorUtils pallet to container chains templates
  Cargo.lock
  Cargo.toml
  container-chains/templates/frontier/runtime/Cargo.toml
  container-chains/templates/frontier/runtime/src/lib.rs
  container-chains/templates/frontier/runtime/src/xcm_config.rs
  container-chains/templates/simple/runtime/Cargo.toml
  container-chains/templates/simple/runtime/src/lib.rs
  container-chains/templates/simple/runtime/src/xcm_config.rs
  test/moonwall.config.json
  test/suites/common-container-chains/test-pallet-xcm-executor-utils/test-custom-policy.ts
  test/suites/common-container-chains/test-pallet-xcm-executor-utils/test-default-policy.ts
Labels: B7-runtimenoteworthy, breaking

#431 enforce auditability
  .github/workflows/enforce-pr-labels.yml
Labels: B0-silent, D3-trivial, not-breaking

#417 Apply current clippy lints
  client/consensus/src/collators.rs
  client/consensus/src/collators/basic.rs
  client/node-common/src/command.rs
  client/node-common/src/service.rs
  container-chains/templates/frontier/node/src/chain_spec.rs
  container-chains/templates/frontier/node/src/command.rs
  container-chains/templates/frontier/node/src/rpc/mod.rs
  container-chains/templates/frontier/runtime/src/lib.rs
  container-chains/templates/simple/node/src/chain_spec.rs
  container-chains/templates/simple/node/src/command.rs
  container-chains/templates/simple/runtime/src/lib.rs
  node/src/chain_spec/dancebox.rs
  node/src/chain_spec/flashbox.rs
  node/src/cli.rs
  node/src/command.rs
  node/src/container_chain_monitor.rs
  node/src/container_chain_spawner.rs
  pallets/author-noting/src/mock.rs
  pallets/author-noting/src/tests.rs
  pallets/collator-assignment/src/assignment.rs
  pallets/collator-assignment/src/benchmarking.rs
  pallets/collator-assignment/src/mock.rs
  pallets/collator-assignment/src/tests/prioritize_invulnerables.rs
  pallets/data-preservers/src/benchmarks.rs
  pallets/pooled-staking/src/calls.rs
  pallets/pooled-staking/src/candidate.rs
  pallets/pooled-staking/src/pools.rs
  pallets/pooled-staking/src/tests/mod.rs
  pallets/registrar/src/benchmarks.rs
  pallets/registrar/src/lib.rs
  pallets/services-payment/src/benchmarks.rs
  pallets/services-payment/src/lib.rs
  pallets/stream-payment/src/benchmarking.rs
  pallets/stream-payment/src/lib.rs
  primitives/author-noting-inherent/src/tests.rs
  primitives/container-chain-genesis-data/src/json.rs
  runtime/dancebox/src/lib.rs
  runtime/dancebox/src/weights/xcm/mod.rs
  runtime/dancebox/tests/common/mod.rs
  runtime/dancebox/tests/common/xcm/foreign_signed_based_sovereign.rs
  runtime/dancebox/tests/common/xcm/foreign_sovereigns.rs
  runtime/dancebox/tests/common/xcm/transact.rs
  runtime/dancebox/tests/common/xcm/trap.rs
  runtime/dancebox/tests/integration_test.rs
  runtime/flashbox/src/lib.rs
  runtime/flashbox/tests/common/mod.rs
  runtime/flashbox/tests/integration_test.rs
Labels: a0-pleasereview, B0-silent, D5-nicetohaveaudit⚠️, not-breaking
