Repository moondance-labs/tanssi, pull requests merged in 2024-11, with the labels that each got.

#739 Fix hardware benchmarks always running
  container-chains/nodes/frontier/src/command.rs
  container-chains/nodes/simple/src/command.rs
  node/src/command.rs
  solo-chains/client/cli/src/command.rs
Labels: B0-silent, D3-trivial, not-breaking

#737 Add bridge testing environment
  .prettierignore
  test/configs/zombieDancelightBridge.json
  test/moonwall.config.json
  test/scripts/bridge-build-artifacts.sh
  test/scripts/bridge/assets/beacon-relay.json
  test/scripts/bridge/assets/beefy-relay.json
  test/scripts/bridge/assets/genesis.json
  test/scripts/bridge/assets/jwtsecret
  test/scripts/bridge/build-eth-contracts.sh
  test/scripts/bridge/build-ethereum-node.sh
  test/scripts/bridge/build-relayer.sh
  test/scripts/bridge/cleanup.sh
  test/scripts/bridge/deploy-ethereum-contracts.sh
  test/scripts/bridge/generate-beefy-checkpoint.sh
  test/scripts/bridge/generate-contract-info.sh
  test/scripts/bridge/set-env.sh
  test/scripts/bridge/setup-relayer.sh
  test/scripts/bridge/start-ethereum-node.sh
  test/scripts/bridge/start-relayer.sh
  test/suites/zombie-tanssi-relay-eth-bridge/test-consensus-bridge.ts
Labels: B0-silent, ci, D2-notlive, not-breaking

#740 use node version 22 in all our jobs
  .github/workflow-templates/typescript-tests-moonwall/action.yml
  .github/workflow-templates/zombienet-tests/action.yml
  .github/workflows/client-release-issue.yml
  .github/workflows/publish-binary-tannsi-relay.yml
  .github/workflows/publish-binary.yml
  .github/workflows/publish-runtime-chevdor.yml
  .github/workflows/publish-runtime.yml
  .github/workflows/publish-typescript-api.yml
  .github/workflows/release.yml
  .github/workflows/run-zombienet-tests.yml
  .github/workflows/runtime-release-issue.yml
  .github/workflows/upgrade-typescript-api.yml
  .github/workflows/version-bump.yml
Labels: B0-silent, D3-trivial, not-breaking

#727 External operator slashes info pallet
  Cargo.lock
  Cargo.toml
  pallets/external-validator-slashes/Cargo.toml
  pallets/external-validator-slashes/src/benchmarking.rs
  pallets/external-validator-slashes/src/lib.rs
  pallets/external-validator-slashes/src/mock.rs
  pallets/external-validator-slashes/src/tests.rs
  pallets/external-validator-slashes/src/weights.rs
  solo-chains/runtime/dancelight/Cargo.toml
  solo-chains/runtime/dancelight/src/lib.rs
  solo-chains/runtime/dancelight/src/tests/common/mod.rs
  solo-chains/runtime/dancelight/src/tests/mod.rs
  solo-chains/runtime/dancelight/src/tests/slashes.rs
  solo-chains/runtime/dancelight/src/weights/mod.rs
  solo-chains/runtime/dancelight/src/weights/pallet_external_validator_slashes.rs
  test/suites/dev-tanssi-relay/slashes/test_slashes_are_confirmed_after_defer_period.ts
  test/suites/dev-tanssi-relay/slashes/test_slashes_are_not_applicable_to_invulnerables.ts
  test/suites/dev-tanssi-relay/slashes/test_slashes_are_removed_after_bonding_period.ts
  test/suites/dev-tanssi-relay/slashes/test_slashes_babe.ts
  test/suites/dev-tanssi-relay/slashes/test_slashes_can_be_cancelled.ts
  test/suites/dev-tanssi-relay/slashes/test_slashes_grandpa.ts
  test/util/slashes.ts
  typescript-api/src/dancelight/interfaces/augment-api-consts.ts
  typescript-api/src/dancelight/interfaces/augment-api-errors.ts
  typescript-api/src/dancelight/interfaces/augment-api-events.ts
  typescript-api/src/dancelight/interfaces/augment-api-query.ts
  typescript-api/src/dancelight/interfaces/augment-api-tx.ts
  typescript-api/src/dancelight/interfaces/lookup.ts
  typescript-api/src/dancelight/interfaces/registry.ts
  typescript-api/src/dancelight/interfaces/types-lookup.ts
Labels: B7-runtimenoteworthy, breaking, D9-needsaudit👮

#741 Add e2e bridge tooling installation to CI
  .github/workflows/e2e-test-bridge.yml
Labels: B0-silent, D3-trivial, not-breaking

#723 Test: Offchain workers disabled by default for container chains
  .github/workflows/run-zombienet-tests.yml
  Cargo.lock
  Cargo.toml
  container-chains/runtime-templates/simple/Cargo.toml
  container-chains/runtime-templates/simple/src/lib.rs
  pallets/ocw-testing/Cargo.toml
  pallets/ocw-testing/src/lib.rs
  test/configs/zombieDancelightSingleContainer.json
  test/moonwall.config.json
  test/scripts/build-spec-dancelight-single-container.sh
  test/suites/para/test_tanssi_containers.ts
  test/suites/warp-sync/test_warp_sync.ts
  test/suites/zombie-offchain/test-simple-template-offchain.ts
  test/suites/zombie-tanssi-relay/test-tanssi-relay.ts
  test/util/block.ts
Labels: B7-runtimenoteworthy, breaking, D5-nicetohaveaudit⚠️

#743 add workflow trigger for bridge e2e tests
  .github/workflow-templates/zombienet-tests/action.yml
  .github/workflows/e2e-test-bridge.yml
  .github/workflows/release.yml
  .github/workflows/run-zombienet-tests.yml
  test/configs/zombieDancelightBridge.json
Labels: B0-silent, D3-trivial, not-breaking

#736 External Validators Rewards pallet
  Cargo.lock
  Cargo.toml
  pallets/external-validators-rewards/Cargo.toml
  pallets/external-validators-rewards/src/lib.rs
  pallets/external-validators-rewards/src/mock.rs
  pallets/external-validators-rewards/src/tests.rs
  pallets/external-validators/src/benchmarking.rs
  primitives/traits/src/lib.rs
  solo-chains/runtime/dancelight/Cargo.toml
  solo-chains/runtime/dancelight/src/lib.rs
  solo-chains/runtime/dancelight/src/tests/external_validators_tests.rs
  test/suites/zombie-tanssi-relay/test-tanssi-relay.ts
  typescript-api/src/dancelight/interfaces/augment-api-consts.ts
  typescript-api/src/dancelight/interfaces/augment-api-query.ts
  typescript-api/src/dancelight/interfaces/lookup.ts
  typescript-api/src/dancelight/interfaces/registry.ts
  typescript-api/src/dancelight/interfaces/types-lookup.ts
Labels: a0-pleasereview, B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#744 chore: :package: update packages
  pnpm-lock.yaml
  test/configs/zombieDancelightUpgrade.json
  test/package.json
  test/suites/data-preservers/test_data_preservers.ts
Labels: B0-silent, D2-notlive

#746 Implement container db folder cleanup on startup
  client/service-container-chain/src/spawner.rs
  container-chains/nodes/frontier/src/command.rs
  container-chains/nodes/simple/src/command.rs
  node/src/service.rs
Labels: B5-clientnoteworthy, breaking, D3-trivial

#745 Starlight: add smoke test for BEEFY and MMR digests
  test/suites/smoke-test-common-all/test-consistency-services-payment.ts
  test/suites/smoke-test-dancelight/test-beefy-mmr-digests.ts
  test/suites/smoke-test-dancelight/test-configuration-consistency.ts
Labels: B0-silent, D2-notlive, not-breaking

#753 Prevent std feature injection in runtime-benchmarks feature
  pallets/external-validator-slashes/Cargo.toml
Labels: B0-silent, D3-trivial, not-breaking

#754 remove SKIP_WASM_BUILD=1 environment variable
  .github/workflows/release.yml
Labels: B0-silent, D2-notlive, not-breaking

#755 Bump node and runtime versions to 0.11.0 and 1100
  Cargo.lock
  container-chains/nodes/frontier/Cargo.toml
  container-chains/nodes/simple/Cargo.toml
  container-chains/runtime-templates/frontier/src/lib.rs
  container-chains/runtime-templates/simple/src/lib.rs
  node/Cargo.toml
  runtime/dancebox/src/lib.rs
  runtime/flashbox/src/lib.rs
  solo-chains/node/tanssi-relay-service/Cargo.toml
  solo-chains/node/tanssi-relay/Cargo.toml
  solo-chains/runtime/dancelight/src/lib.rs
Labels: B0-silent, D3-trivial, not-breaking

#758 Remove RawGenesisConfig
  client/service-container-chain/src/chain_spec.rs
  client/service-container-chain/src/cli.rs
Labels: B0-silent, D2-notlive, D3-trivial, not-breaking

#757 Fix invulnerables benchmark for dancelight
  pallets/external-validators/src/benchmarking.rs
  pallets/invulnerables/src/benchmarking.rs
  solo-chains/runtime/dancelight/src/lib.rs
  solo-chains/runtime/dancelight/src/weights/mod.rs
  solo-chains/runtime/dancelight/src/weights/pallet_invulnerables.rs
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#747 Container candidates in dev service
  Cargo.lock
  solo-chains/node/tanssi-relay-service/Cargo.toml
  solo-chains/node/tanssi-relay-service/src/dev_rpcs.rs
  solo-chains/node/tanssi-relay-service/src/dev_service.rs
  solo-chains/node/tanssi-relay-service/src/lib.rs
  test/suites/dev-tanssi-relay/external-validators-rewards/test_external_validator_rewards.ts
  test/suites/dev-tanssi-relay/paras-candidate-inherent/test_paras_candidate_inherent.ts
  test/suites/dev-tanssi-relay/slashes/test_slashes_are_removed_after_bonding_period.ts
  test/util/relayInterface.ts
Labels: B0-silent, D3-trivial, not-breaking

#742 Add eth outbound queue and system pallets
  Cargo.lock
  Cargo.toml
  pallets/external-validator-slashes/Cargo.toml
  pallets/external-validator-slashes/src/benchmarking.rs
  pallets/external-validator-slashes/src/lib.rs
  pallets/external-validator-slashes/src/mock.rs
  pallets/external-validator-slashes/src/weights.rs
  primitives/bridge/Cargo.toml
  primitives/bridge/src/custom_do_process_message.rs
  primitives/bridge/src/custom_send_message.rs
  primitives/bridge/src/lib.rs
  solo-chains/runtime/dancelight/Cargo.toml
  solo-chains/runtime/dancelight/constants/Cargo.toml
  solo-chains/runtime/dancelight/constants/src/lib.rs
  solo-chains/runtime/dancelight/src/bridge_to_ethereum_config.rs
  solo-chains/runtime/dancelight/src/lib.rs
  solo-chains/runtime/dancelight/src/weights/mod.rs
  solo-chains/runtime/dancelight/src/weights/pallet_external_validator_slashes.rs
  solo-chains/runtime/dancelight/src/weights/snowbridge_pallet_outbound_queue.rs
  solo-chains/runtime/dancelight/src/weights/snowbridge_pallet_system.rs
  test/suites/dev-tanssi-relay/slashes/test_slashes_eth.ts
  typescript-api/src/dancelight/interfaces/augment-api-consts.ts
  typescript-api/src/dancelight/interfaces/augment-api-errors.ts
  typescript-api/src/dancelight/interfaces/augment-api-events.ts
  typescript-api/src/dancelight/interfaces/augment-api-query.ts
  typescript-api/src/dancelight/interfaces/augment-api-tx.ts
  typescript-api/src/dancelight/interfaces/lookup.ts
  typescript-api/src/dancelight/interfaces/registry.ts
  typescript-api/src/dancelight/interfaces/types-lookup.ts
Labels: B7-runtimenoteworthy, breaking, D5-nicetohaveaudit⚠️

#764 Add smoke test for External Validators Rewards pallet
  test/suites/smoke-test-dancelight/test-external-validators-rewards.ts
Labels: a0-pleasereview, B0-silent, D2-notlive, not-breaking

#750 Add inbound queue
  Cargo.lock
  Cargo.toml
  primitives/bridge/Cargo.toml
  primitives/bridge/src/lib.rs
  primitives/bridge/src/symbiotic_message_processor.rs
  solo-chains/runtime/dancelight/Cargo.toml
  solo-chains/runtime/dancelight/src/bridge_to_ethereum_config.rs
  solo-chains/runtime/dancelight/src/lib.rs
  solo-chains/runtime/dancelight/src/tests/inbound_queue_tests/integration_tests.rs
  solo-chains/runtime/dancelight/src/tests/inbound_queue_tests/message_processor_tests.rs
  solo-chains/runtime/dancelight/src/tests/inbound_queue_tests/mod.rs
  solo-chains/runtime/dancelight/src/tests/mod.rs
  solo-chains/runtime/dancelight/src/weights/mod.rs
  solo-chains/runtime/dancelight/src/weights/snowbridge_pallet_inbound_queue.rs
  typescript-api/src/dancelight/interfaces/augment-api-consts.ts
  typescript-api/src/dancelight/interfaces/augment-api-errors.ts
  typescript-api/src/dancelight/interfaces/augment-api-events.ts
  typescript-api/src/dancelight/interfaces/augment-api-query.ts
  typescript-api/src/dancelight/interfaces/augment-api-tx.ts
  typescript-api/src/dancelight/interfaces/lookup.ts
  typescript-api/src/dancelight/interfaces/registry.ts
  typescript-api/src/dancelight/interfaces/types-lookup.ts
Labels: B7-runtimenoteworthy, breaking, D9-needsaudit👮

#768 publish fix for workers
  .github/workflows/publish-binary-tannsi-relay.yml
Labels: B0-silent, D3-trivial, not-breaking
