Repository moondance-labs/tanssi, pull requests merged in 2024-05, with the labels that each got.

#532 Fix BuildSpec for all configs
  node/src/cli.rs
  node/src/command.rs
  test/moonwall.config.json
  test/scripts/compile-wasm.ts
Labels: B0-silent, breaking, D3-trivial

#539 increase collator num for flashbox
  runtime/flashbox/src/lib.rs
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#541 Remove `expect` which was checking `supplyAfter == supplyBefore + issuance`
  test/suites/smoke-test-common/test-inflation-rewards.ts
Labels: B0-silent, D2-notlive, D3-trivial, not-breaking

#543 Fixing lint error
  test/suites/smoke-test-common/test-inflation-rewards.ts
Labels: B0-silent, D2-notlive, D3-trivial, not-breaking

#544 deprecate at least in container-chain nodes, native executor
  container-chains/nodes/frontier/src/client.rs
  container-chains/nodes/frontier/src/service.rs
  container-chains/nodes/simple/src/service.rs
Labels: B5-clientnoteworthy, breaking, D3-trivial

#545 Services payment RPC
  Cargo.lock
  Cargo.toml
  client/services-payment/Cargo.toml
  client/services-payment/src/lib.rs
  node/Cargo.toml
  node/src/rpc.rs
  pallets/services-payment/rpc/runtime-api/Cargo.toml
  pallets/services-payment/rpc/runtime-api/src/lib.rs
  runtime/dancebox/Cargo.toml
  runtime/dancebox/src/lib.rs
  runtime/flashbox/Cargo.toml
  runtime/flashbox/src/lib.rs
  test/suites/common-tanssi/services-payment/test_services_payment_rpc.ts
Labels: B5-clientnoteworthy, breaking, D3-trivial

#548 Remove runtime-benchmark cargo check on CI
  .github/workflows/release.yml
Labels: B0-silent, D3-trivial, not-breaking

#549 Make some smoke tests more consistent
  test/suites/smoke-test-common/test-inflation-rewards.ts
  test/suites/smoke-test-dancebox/test-invulnerables-priority.ts
  test/suites/smoke-test-dancebox/test-randomness-consistency.ts
  test/util/block.ts
Labels: B0-silent, D3-trivial, I4-tests 🎯, not-breaking

#516 Modifying xcm-core-buyer to add reporting of the core purchase
  Cargo.lock
  pallets/xcm-core-buyer/Cargo.toml
  pallets/xcm-core-buyer/src/benchmarks.rs
  pallets/xcm-core-buyer/src/lib.rs
  pallets/xcm-core-buyer/src/mock.rs
  pallets/xcm-core-buyer/src/tests.rs
  pallets/xcm-core-buyer/src/weights.rs
  runtime/dancebox/src/lib.rs
  runtime/dancebox/src/weights/pallet_xcm_core_buyer.rs
  runtime/dancebox/src/xcm_config.rs
  runtime/dancebox/tests/common/xcm/core_buyer.rs
  runtime/dancebox/tests/common/xcm/delivery_fees.rs
  runtime/dancebox/tests/common/xcm/expected_event_checker.rs
  runtime/dancebox/tests/common/xcm/foreign_signed_based_sovereign.rs
  runtime/dancebox/tests/common/xcm/foreign_sovereigns.rs
  runtime/dancebox/tests/common/xcm/mod.rs
  runtime/dancebox/tests/common/xcm/reserver_transfers_polkadot_xcm.rs
  runtime/dancebox/tests/common/xcm/token_derivative_reception_container_dancebox.rs
  runtime/dancebox/tests/common/xcm/token_derivative_reception_dancebox_frontier_container.rs
  runtime/dancebox/tests/common/xcm/token_derivative_reception_dancebox_simple_container.rs
  runtime/dancebox/tests/common/xcm/token_derivative_reception_relay_dancebox.rs
  runtime/dancebox/tests/common/xcm/token_derivative_reception_relay_frontier_container.rs
  runtime/dancebox/tests/common/xcm/token_derivative_reception_relay_simple_container.rs
  runtime/dancebox/tests/common/xcm/transact.rs
  runtime/dancebox/tests/common/xcm/trap.rs
  test/suites/dev-tanssi/weights/test_set_latest_author_data_weight.ts
  typescript-api/src/dancebox/interfaces/augment-api-consts.ts
  typescript-api/src/dancebox/interfaces/augment-api-errors.ts
  typescript-api/src/dancebox/interfaces/augment-api-events.ts
  typescript-api/src/dancebox/interfaces/augment-api-query.ts
  typescript-api/src/dancebox/interfaces/augment-api-tx.ts
  typescript-api/src/dancebox/interfaces/lookup.ts
  typescript-api/src/dancebox/interfaces/registry.ts
  typescript-api/src/dancebox/interfaces/types-lookup.ts
Labels: B7-runtimenoteworthy, breaking, D3-breaksconsensus, D9-needsaudit👮

#552 Docs: polish chopsticks docs
  test/README.md
Labels: documentation, B0-silent, D3-trivial, not-breaking

#550 Fix: do not shuffle collators before applying priority
  pallets/collator-assignment/src/lib.rs
  pallets/collator-assignment/src/tests.rs
Labels: B7-runtimenoteworthy, breaking, D5-nicetohaveaudit⚠️

#546 Allow additional account as container chain manager
  pallets/registrar/src/benchmarks.rs
  pallets/registrar/src/lib.rs
  pallets/registrar/src/weights.rs
  runtime/common/src/migrations.rs
  runtime/dancebox/src/weights/pallet_registrar.rs
  runtime/flashbox/src/weights/pallet_registrar.rs
  test/suites/common-tanssi/registrar/test_registrar_para_manager.ts
  test/suites/common-tanssi/registrar/test_registrar_pause.ts
  test/suites/common-tanssi/registrar/test_registrar_proxy.ts
  test/suites/common-tanssi/registrar/test_registrar_register.ts
  test/suites/common-tanssi/registrar/test_registrar_register_parathread.ts
  test/suites/common-tanssi/registrar/test_utils_rpc.ts
  typescript-api/src/dancebox/interfaces/augment-api-errors.ts
  typescript-api/src/dancebox/interfaces/augment-api-events.ts
  typescript-api/src/dancebox/interfaces/augment-api-query.ts
  typescript-api/src/dancebox/interfaces/augment-api-tx.ts
  typescript-api/src/dancebox/interfaces/lookup.ts
  typescript-api/src/dancebox/interfaces/types-lookup.ts
  typescript-api/src/flashbox/interfaces/augment-api-errors.ts
  typescript-api/src/flashbox/interfaces/augment-api-events.ts
  typescript-api/src/flashbox/interfaces/augment-api-query.ts
  typescript-api/src/flashbox/interfaces/augment-api-tx.ts
  typescript-api/src/flashbox/interfaces/lookup.ts
  typescript-api/src/flashbox/interfaces/types-lookup.ts
Labels: B7-runtimenoteworthy, breaking, D3-trivial

#556 Remove empty folders after removing container db folder
  node/src/container_chain_spawner.rs
Labels: B5-clientnoteworthy, breaking, D3-trivial

#555 Wait for lock file in container chain restart
  Cargo.lock
  Cargo.toml
  node/Cargo.toml
  node/src/container_chain_spawner.rs
Labels: B5-clientnoteworthy, breaking, D3-trivial

#536 Add more smoke tests
  test/suites/smoke-test-common/test-configuration-consistency.ts
  test/suites/smoke-test-common/test-consistency-services-payment.ts
  test/suites/smoke-test-common/test-proxy.ts
  test/suites/smoke-test-common/test-supply-variance.ts
  test/suites/smoke-test-dancebox/test-treasury.ts
  test/util/block.ts
  test/util/payment.ts
Labels: B0-silent, D3-trivial, not-breaking

#557 Script benchmarking all runtimes
  tools/benchmark-all-runtimes.sh
Labels: B0-silent, D3-trivial, not-breaking

#551 Data Preservers Profiles
  container-chains/nodes/frontier/src/rpc/finality.rs
  container-chains/nodes/frontier/src/rpc/mod.rs
  container-chains/runtime-templates/frontier/src/xcm_config.rs
  container-chains/runtime-templates/simple/src/xcm_config.rs
  pallets/data-preservers/src/benchmarks.rs
  pallets/data-preservers/src/lib.rs
  pallets/data-preservers/src/mock.rs
  pallets/data-preservers/src/tests.rs
  pallets/data-preservers/src/weights.rs
  pallets/xcm-core-buyer/src/benchmarks.rs
  pallets/xcm-core-buyer/src/lib.rs
  pallets/xcm-core-buyer/src/mock.rs
  pallets/xcm-core-buyer/src/tests.rs
  runtime/common/src/benchmarking.rs
  runtime/dancebox/src/lib.rs
  runtime/dancebox/src/weights/pallet_data_preservers.rs
  runtime/dancebox/src/xcm_config.rs
  runtime/dancebox/tests/common/xcm/core_buyer.rs
  runtime/dancebox/tests/common/xcm/delivery_fees.rs
  runtime/dancebox/tests/common/xcm/foreign_signed_based_sovereign.rs
  runtime/dancebox/tests/common/xcm/foreign_sovereigns.rs
  runtime/dancebox/tests/common/xcm/reserver_transfers_polkadot_xcm.rs
  runtime/dancebox/tests/common/xcm/token_derivative_reception_container_dancebox.rs
  runtime/dancebox/tests/common/xcm/token_derivative_reception_dancebox_frontier_container.rs
  runtime/dancebox/tests/common/xcm/token_derivative_reception_dancebox_simple_container.rs
  runtime/dancebox/tests/common/xcm/token_derivative_reception_relay_dancebox.rs
  runtime/dancebox/tests/common/xcm/token_derivative_reception_relay_frontier_container.rs
  runtime/dancebox/tests/common/xcm/token_derivative_reception_relay_simple_container.rs
  runtime/dancebox/tests/common/xcm/transact.rs
  runtime/dancebox/tests/common/xcm/trap.rs
  runtime/flashbox/src/lib.rs
  runtime/flashbox/src/weights/pallet_data_preservers.rs
  test/suites/common-tanssi/pallet-data-preservers/test_pallet_data_preservers.ts
  typescript-api/src/dancebox/interfaces/augment-api-consts.ts
  typescript-api/src/dancebox/interfaces/augment-api-errors.ts
  typescript-api/src/dancebox/interfaces/augment-api-events.ts
  typescript-api/src/dancebox/interfaces/augment-api-query.ts
  typescript-api/src/dancebox/interfaces/augment-api-tx.ts
  typescript-api/src/dancebox/interfaces/lookup.ts
  typescript-api/src/dancebox/interfaces/registry.ts
  typescript-api/src/dancebox/interfaces/types-lookup.ts
  typescript-api/src/flashbox/interfaces/augment-api-consts.ts
  typescript-api/src/flashbox/interfaces/augment-api-errors.ts
  typescript-api/src/flashbox/interfaces/augment-api-events.ts
  typescript-api/src/flashbox/interfaces/augment-api-query.ts
  typescript-api/src/flashbox/interfaces/augment-api-tx.ts
  typescript-api/src/flashbox/interfaces/lookup.ts
  typescript-api/src/flashbox/interfaces/registry.ts
  typescript-api/src/flashbox/interfaces/types-lookup.ts
Labels: a0-pleasereview, B7-runtimenoteworthy, breaking, D5-nicetohaveaudit⚠️

#562 Move pallets runtime-apis outside rpc dir
  Cargo.toml
  pallets/author-noting/runtime-api/Cargo.toml
  pallets/author-noting/runtime-api/src/lib.rs
  pallets/collator-assignment/runtime-api/Cargo.toml
  pallets/collator-assignment/runtime-api/src/lib.rs
  pallets/registrar/runtime-api/Cargo.toml
  pallets/registrar/runtime-api/src/lib.rs
  pallets/services-payment/runtime-api/Cargo.toml
  pallets/services-payment/runtime-api/src/lib.rs
  pallets/stream-payment/runtime-api/Cargo.toml
  pallets/stream-payment/runtime-api/src/lib.rs
Labels: B0-silent, D3-trivial, not-breaking
