Repository moondance-labs/tanssi, pull requests merged in 2024-06, with the labels that each got.

#565 add weight to migrations for registrar
  runtime/common/src/migrations.rs
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#569 Add tanssi full node to zombienet tests
  test/configs/zombieTanssi.json
  test/configs/zombieTanssiKeepDb.json
  test/configs/zombieTanssiMetrics.json
  test/configs/zombieTanssiOneNode.json
  test/configs/zombieTanssiParathreads.json
  test/configs/zombieTanssiRotation.json
  test/configs/zombieTanssiWarpSync.json
Labels: B0-silent, D2-notlive, D3-trivial, not-breaking

#567 increase moonwall and zombienet
  pnpm-lock.yaml
  test/package.json
Labels: B0-silent, D3-trivial, not-breaking

#581 Add migration for ForeignAssetCreator
  Cargo.lock
  container-chains/runtime-templates/simple/src/migrations.rs
  runtime/common/Cargo.toml
  runtime/common/src/migrations.rs
  runtime/dancebox/tests/integration_test.rs
Labels: B7-runtimenoteworthy, breaking, D5-nicetohaveaudit⚠️

#570 Proxy precompile in Frontier container chain runtime
  Cargo.lock
  Cargo.toml
  container-chains/runtime-templates/frontier/Cargo.toml
  container-chains/runtime-templates/frontier/src/lib.rs
  container-chains/runtime-templates/frontier/src/migrations.rs
  container-chains/runtime-templates/frontier/src/precompiles.rs
  test/contracts/solidity/Proxy.sol
  test/suites/dev-frontier-template/test-precompiles/test-precompile-proxy.ts
  test/suites/dev-frontier-template/test-precompiles/test-precompile-smart-contract-call.ts
  test/suites/dev-frontier-template/test-precompiles/test-precompile-xcm-utils.ts
Labels: B7-runtimenoteworthy, breaking, D3-trivial

#571 Contract deployment customization in frontier template
  Cargo.lock
  Cargo.toml
  container-chains/runtime-templates/frontier/Cargo.toml
  container-chains/runtime-templates/frontier/src/lib.rs
  container-chains/runtime-templates/frontier/src/migrations.rs
  container-chains/runtime-templates/frontier/src/weights/mod.rs
  container-chains/runtime-templates/frontier/src/weights/pallet_parameters.rs
  container-chains/runtime-templates/frontier/src/xcm_config.rs
  test/contracts/solidity/FooBarCreator.sol
  test/suites/dev-frontier-template/test-contract/test-contract-deploy-filter.ts
Labels: B7-runtimenoteworthy, breaking, D5-nicetohaveaudit⚠️

#564 Add support for pallet-xcm precompile in frontier template
  Cargo.lock
  Cargo.toml
  container-chains/runtime-templates/frontier/Cargo.toml
  container-chains/runtime-templates/frontier/src/migrations.rs
  container-chains/runtime-templates/frontier/src/precompiles.rs
  test/contracts/solidity/XcmInterface.sol
  test/suites/dev-frontier-template/test-precompiles/test-precompile-pallet-xcm.ts
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#585 Rename runtime-common to tanssi-runtime-common
  Cargo.lock
  Cargo.toml
  container-chains/runtime-templates/frontier/Cargo.toml
  container-chains/runtime-templates/frontier/src/migrations.rs
  container-chains/runtime-templates/simple/Cargo.toml
  container-chains/runtime-templates/simple/src/migrations.rs
  runtime/common/Cargo.toml
  runtime/dancebox/Cargo.toml
  runtime/dancebox/src/lib.rs
  runtime/dancebox/tests/integration_test.rs
  runtime/flashbox/Cargo.toml
  runtime/flashbox/src/lib.rs
  runtime/flashbox/tests/integration_test.rs
Labels: B0-silent, D3-trivial, not-breaking

#586 fix, hopefully for all, tests regarding consistency payment
  test/suites/smoke-test-common/test-configuration-consistency.ts
  test/suites/smoke-test-common/test-consistency-services-payment.ts
Labels: B0-silent, D3-trivial, not-breaking

#593 Bump node and runtime versions to 800
  Cargo.lock
  container-chains/nodes/frontier/Cargo.toml
  container-chains/nodes/simple/Cargo.toml
  container-chains/runtime-templates/frontier/src/lib.rs
  container-chains/runtime-templates/simple/src/lib.rs
  node/Cargo.toml
  runtime/dancebox/src/lib.rs
  runtime/flashbox/src/lib.rs
Labels: B0-silent, D3-trivial, not-breaking

#591 Fix publish runtime job
  .github/workflows/publish-runtime-chevdor.yml
  .github/workflows/publish-runtime.yml
  scripts/build-runtime-srtool.sh
  tools/github/generate-runtimes-body.ts
Labels: B0-silent, D3-trivial, not-breaking

#588 Enable PoV reclaim in all runtimes
  Cargo.lock
  Cargo.toml
  client/node-common/src/service.rs
  container-chains/runtime-templates/frontier/Cargo.toml
  container-chains/runtime-templates/frontier/src/lib.rs
  container-chains/runtime-templates/simple/Cargo.toml
  container-chains/runtime-templates/simple/src/lib.rs
  runtime/dancebox/Cargo.toml
  runtime/dancebox/src/lib.rs
  runtime/flashbox/Cargo.toml
  runtime/flashbox/src/lib.rs
  typescript-api/src/dancebox/interfaces/lookup.ts
  typescript-api/src/dancebox/interfaces/registry.ts
  typescript-api/src/dancebox/interfaces/types-lookup.ts
  typescript-api/src/flashbox/interfaces/lookup.ts
  typescript-api/src/flashbox/interfaces/registry.ts
  typescript-api/src/flashbox/interfaces/types-lookup.ts
Labels: B7-runtimenoteworthy, breaking, D5-nicetohaveaudit⚠️

#594 Add script to automatically bump all runtimes and clients to a new version
  scripts/bump-runtime-versions.sh
Labels: B0-silent, D2-notlive, not-breaking

#598 Stream payment: Prevent making a request with a past deadline
  pallets/stream-payment/src/lib.rs
  pallets/stream-payment/src/tests.rs
  test/suites/common-tanssi/stream-payment/test_stream_payment.ts
  test/suites/common-tanssi/stream-payment/test_stream_payment_rpc.ts
  typescript-api/src/dancebox/interfaces/augment-api-errors.ts
  typescript-api/src/dancebox/interfaces/lookup.ts
  typescript-api/src/dancebox/interfaces/types-lookup.ts
  typescript-api/src/flashbox/interfaces/augment-api-errors.ts
  typescript-api/src/flashbox/interfaces/lookup.ts
  typescript-api/src/flashbox/interfaces/types-lookup.ts
Labels: a0-pleasereview, B7-runtimenoteworthy, breaking, D9-needsaudit👮

#592 Add XcmPaymentApi to all runtimes
  .gitattributes
  Cargo.lock
  Cargo.toml
  container-chains/runtime-templates/frontier/Cargo.toml
  container-chains/runtime-templates/frontier/src/lib.rs
  container-chains/runtime-templates/simple/Cargo.toml
  container-chains/runtime-templates/simple/src/lib.rs
  runtime/dancebox/Cargo.toml
  runtime/dancebox/src/lib.rs
  test/suites/common-xcm/xcm/test-xcm-payment-api.ts
Labels: B7-runtimenoteworthy, breaking, D5-nicetohaveaudit⚠️

#587 Add runtime - Starlight
  Cargo.lock
  Cargo.toml
  solo-chains/client/cli/Cargo.toml
  solo-chains/client/cli/build.rs
  solo-chains/client/cli/src/cli.rs
  solo-chains/client/cli/src/command.rs
  solo-chains/client/cli/src/error.rs
  solo-chains/client/cli/src/lib.rs
  solo-chains/node/tanssi-relay-service/Cargo.toml
  solo-chains/node/tanssi-relay-service/chain-specs/.gitignore
  solo-chains/node/tanssi-relay-service/chain-specs/rococo.json
  solo-chains/node/tanssi-relay-service/src/chain_spec.rs
  solo-chains/node/tanssi-relay-service/src/lib.rs
  solo-chains/node/tanssi-relay/Cargo.toml
  solo-chains/node/tanssi-relay/build.rs
  solo-chains/node/tanssi-relay/src/main.rs
  solo-chains/runtime/starlight/Cargo.toml
  solo-chains/runtime/starlight/README.md
  solo-chains/runtime/starlight/build.rs
  solo-chains/runtime/starlight/constants/Cargo.toml
  solo-chains/runtime/starlight/constants/src/lib.rs
  solo-chains/runtime/starlight/constants/src/weights/block_weights.rs
  solo-chains/runtime/starlight/constants/src/weights/extrinsic_weights.rs
  solo-chains/runtime/starlight/constants/src/weights/mod.rs
  solo-chains/runtime/starlight/constants/src/weights/paritydb_weights.rs
  solo-chains/runtime/starlight/constants/src/weights/rocksdb_weights.rs
  solo-chains/runtime/starlight/src/genesis_config_presets.rs
  solo-chains/runtime/starlight/src/governance/fellowship.rs
  solo-chains/runtime/starlight/src/governance/mod.rs
  solo-chains/runtime/starlight/src/governance/origins.rs
  solo-chains/runtime/starlight/src/governance/tracks.rs
  solo-chains/runtime/starlight/src/impls.rs
  solo-chains/runtime/starlight/src/lib.rs
  solo-chains/runtime/starlight/src/tests.rs
  solo-chains/runtime/starlight/src/validator_manager.rs
  solo-chains/runtime/starlight/src/xcm_config.rs
  test/configs/zombieStarlight.json
  test/moonwall.config.json
  test/suites/dev-tanssi-relay/balances/test_balances.ts
  test/suites/dev-tanssi-relay/chain-spec/test_chain_spec.ts
  test/suites/zombie-tanssi-relay/test-tanssi-relay.ts
Labels: B0-silent, breaking, D5-nicetohaveaudit⚠️

#602 Run zombienet tests for starlight in CI
  .github/workflows/release.yml
  Cargo.lock
  Cargo.toml
  solo-chains/node/tanssi-relay/Cargo.toml
  solo-chains/node/tanssi-relay/src/bin/execute-worker.rs
  solo-chains/node/tanssi-relay/src/bin/prepare-worker.rs
  test/moonwall.config.json
Labels: B0-silent, D3-trivial, not-breaking

#609 Add dev starlight moonwall test suite to CI
  .github/workflows/release.yml
Labels: B0-silent, D3-trivial, not-breaking

#597 Cleanup code
  Cargo.lock
  Cargo.toml
  client/consensus/src/collators/lookahead.rs
  container-chains/runtime-templates/frontier/Cargo.toml
  container-chains/runtime-templates/frontier/src/lib.rs
  container-chains/runtime-templates/simple/Cargo.toml
  container-chains/runtime-templates/simple/src/lib.rs
  pallets/author-noting/Cargo.toml
  pallets/author-noting/src/lib.rs
  pallets/author-noting/src/mock.rs
  pallets/authority-assignment/Cargo.toml
  pallets/authority-assignment/src/lib.rs
  pallets/authority-assignment/src/mock.rs
  pallets/authority-mapping/src/lib.rs
  pallets/collator-assignment/Cargo.toml
  pallets/collator-assignment/src/lib.rs
  pallets/collator-assignment/src/mock.rs
  pallets/configuration/src/lib.rs
  pallets/data-preservers/src/mock.rs
  pallets/data-preservers/src/types.rs
  pallets/inflation-rewards/Cargo.toml
  pallets/inflation-rewards/src/lib.rs
  pallets/inflation-rewards/src/mock.rs
  pallets/invulnerables/src/lib.rs
  pallets/pooled-staking/Cargo.toml
  pallets/pooled-staking/src/candidate.rs
  pallets/pooled-staking/src/lib.rs
  pallets/registrar/src/lib.rs
  pallets/registrar/src/mock.rs
  pallets/registrar/src/tests.rs
  pallets/services-payment/src/lib.rs
  pallets/stream-payment/Cargo.toml
  pallets/stream-payment/runtime-api/Cargo.toml
  pallets/stream-payment/runtime-api/src/lib.rs
  pallets/stream-payment/src/lib.rs
  pallets/xcm-core-buyer/Cargo.toml
  pallets/xcm-core-buyer/src/lib.rs
  pallets/xcm-core-buyer/src/mock.rs
  pallets/xcm-core-buyer/src/tests.rs
  primitives/traits/Cargo.toml
  primitives/traits/src/alias.rs
  primitives/traits/src/lib.rs
  runtime/common/src/migrations.rs
  runtime/dancebox/src/lib.rs
  runtime/flashbox/src/lib.rs
Labels: a0-pleasereview, B0-silent, D3-trivial

#610 Add `pallet_initializer` to `starlight` runtime
  Cargo.lock
  solo-chains/runtime/starlight/Cargo.toml
  solo-chains/runtime/starlight/src/lib.rs
Labels: B0-silent, breaking, D5-nicetohaveaudit⚠️
