Repository moondance-labs/tanssi, pull requests merged in 2024-10, with the labels that each got.

#703 fix author noting bench
  pallets/author-noting/src/benchmarks.rs
  solo-chains/runtime/dancelight/src/lib.rs
  solo-chains/runtime/dancelight/src/weights/mod.rs
  solo-chains/runtime/dancelight/src/weights/pallet_author_noting.rs
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#706 Improved display of startup errors in node binaries
  Cargo.lock
  container-chains/nodes/frontier/Cargo.toml
  container-chains/nodes/frontier/src/main.rs
  container-chains/nodes/simple/Cargo.toml
  container-chains/nodes/simple/src/main.rs
  node/Cargo.toml
  node/src/main.rs
Labels: B0-silent, D3-trivial, not-breaking

#707 Remove default invulnerables from dancelight-local
  solo-chains/client/cli/src/command.rs
Labels: B5-clientnoteworthy, D3-trivial, not-breaking

#709 Move core assignment logs to debug
  solo-chains/runtime/dancelight/src/lib.rs
Labels: B0-silent, D3-trivial, not-breaking

#708 Avoid ZeroCollators error in solochains
  pallets/collator-assignment/src/assignment.rs
  pallets/collator-assignment/src/tests/assign_full.rs
  pallets/collator-assignment/src/tests/select_chains.rs
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#710 fix a few ci jobs related to starlight and publishing docker
  .github/workflows/docker-runtime-draft.yml
  .github/workflows/release.yml
Labels: B0-silent, D3-trivial, not-breaking

#711 Generate typescript api dancelight
  .github/workflows/release.yml
  solo-chains/client/cli/src/cli.rs
  solo-chains/client/cli/src/command.rs
  typescript-api/package.json
  typescript-api/scripts/runtime-upgrade.ts
  typescript-api/src/dancelight/index.ts
  typescript-api/src/dancelight/interfaces/augment-api-consts.ts
  typescript-api/src/dancelight/interfaces/augment-api-errors.ts
  typescript-api/src/dancelight/interfaces/augment-api-events.ts
  typescript-api/src/dancelight/interfaces/augment-api-query.ts
  typescript-api/src/dancelight/interfaces/augment-api-rpc.ts
  typescript-api/src/dancelight/interfaces/augment-api-runtime.ts
  typescript-api/src/dancelight/interfaces/augment-api-tx.ts
  typescript-api/src/dancelight/interfaces/augment-api.ts
  typescript-api/src/dancelight/interfaces/augment-types.ts
  typescript-api/src/dancelight/interfaces/definitions.ts
  typescript-api/src/dancelight/interfaces/index.ts
  typescript-api/src/dancelight/interfaces/lookup.ts
  typescript-api/src/dancelight/interfaces/registry.ts
  typescript-api/src/dancelight/interfaces/starlight/definitions.ts
  typescript-api/src/dancelight/interfaces/starlight/index.ts
  typescript-api/src/dancelight/interfaces/starlight/types.ts
  typescript-api/src/dancelight/interfaces/types-lookup.ts
  typescript-api/src/dancelight/interfaces/types.ts
  typescript-api/src/dancelight/tsconfig.json
  typescript-api/tsconfig.base.json
  typescript-api/tsconfig.json
Labels: B5-clientnoteworthy, breaking, D3-trivial

#691 Bump Rust version to 1.81.0
  .github/workflows/coverage.yml
  Cargo.lock
  Cargo.toml
  client/consensus/src/mocks.rs
  client/consensus/src/tests.rs
  client/service-container-chain/src/spawner.rs
  container-chains/nodes/frontier/src/cli.rs
  container-chains/nodes/frontier/src/command.rs
  container-chains/nodes/frontier/src/rpc/mod.rs
  node/src/command/solochain.rs
  node/src/service.rs
  pallets/author-noting/src/lib.rs
  pallets/collator-assignment/src/assignment.rs
  pallets/collator-assignment/src/benchmarking.rs
  pallets/collator-assignment/src/tests/with_core_config.rs
  pallets/inflation-rewards/src/lib.rs
  pallets/initializer/src/lib.rs
  pallets/invulnerables/src/benchmarking.rs
  pallets/pooled-staking/src/benchmarking.rs
  pallets/pooled-staking/src/traits.rs
  pallets/registrar/src/lib.rs
  runtime/common/src/migrations.rs
  runtime/dancebox/src/tests/common/xcm/core_buyer_common.rs
  runtime/dancebox/src/tests/common/xcm/foreign_signed_based_sovereign.rs
  runtime/dancebox/src/tests/integration_test.rs
  runtime/flashbox/src/tests/integration_test.rs
  rust-toolchain
  solo-chains/client/cli/src/command.rs
  solo-chains/client/cli/src/lib.rs
  solo-chains/node/tanssi-relay-service/src/chain_spec.rs
  solo-chains/node/tanssi-relay-service/src/dev_service.rs
  solo-chains/node/tanssi-relay/src/main.rs
  solo-chains/runtime/dancelight/src/genesis_config_presets.rs
  solo-chains/runtime/dancelight/src/lib.rs
  solo-chains/runtime/dancelight/src/tests/author_noting_tests.rs
  solo-chains/runtime/dancelight/src/tests/collator_assignment_tests.rs
  solo-chains/runtime/dancelight/src/tests/common/mod.rs
  solo-chains/runtime/dancelight/src/tests/inflation_rewards.rs
  solo-chains/runtime/dancelight/src/tests/integration_test.rs
  solo-chains/runtime/dancelight/src/tests/relay_configuration.rs
  solo-chains/runtime/dancelight/src/tests/services_payment.rs
  solo-chains/runtime/dancelight/src/tests/sudo.rs
  solo-chains/runtime/dancelight/src/validator_manager.rs
Labels: a0-pleasereview, B0-silent, D3-trivial

#714 more visual symbols for ups and downs
  .github/scripts/coverage-report.py
Labels: B0-silent, D3-trivial, not-breaking

#680 Ethereum RPC Data Providers
  Cargo.lock
  client/node-common/Cargo.toml
  client/node-common/src/service.rs
  client/service-container-chain/Cargo.toml
  client/service-container-chain/src/monitor.rs
  client/service-container-chain/src/rpc.rs
  client/service-container-chain/src/service.rs
  client/service-container-chain/src/spawner.rs
  container-chains/nodes/frontier/Cargo.toml
  container-chains/nodes/frontier/src/cli.rs
  container-chains/nodes/frontier/src/command.rs
  container-chains/nodes/frontier/src/rpc/mod.rs
  container-chains/nodes/simple/src/command.rs
  node/src/service.rs
  pallets/author-noting/src/benchmarks.rs
  pnpm-lock.yaml
  primitives/traits/src/alias.rs
  test/configs/zombieDataPreservers.json
  test/moonwall.config.json
  test/package.json
  test/scripts/build-spec-data-preservers.sh
  test/suites/data-preservers/test_data_preservers.ts
Labels: a0-pleasereview, B5-clientnoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#712 docs related to altair > Solochain
  solo-chains/docs/bridge/etbereum-to-solo-chain.md
  solo-chains/docs/bridge/images/beacon_chain_altair.drawio.png
  solo-chains/docs/bridge/images/relayer_proof_starlight.drawio.png
Labels: B0-silent, D3-trivial, not-breaking

#718 Add docs related to Starlight > Ethereum sync using BEEFY
  solo-chains/docs/bridge/images/starlight_ethereum_beefy_sync.drawio.png
  solo-chains/docs/bridge/solo-chain-to-ethereum.md
Labels: B0-silent, D3-trivial, not-breaking

#716 Frontier Template: PoV Handling
  Cargo.lock
  client/consensus/src/manual_seal.rs
  client/node-common/src/service.rs
  container-chains/runtime-templates/frontier/src/lib.rs
  solo-chains/node/tanssi-relay-service/src/dev_service.rs
  test/contracts/solidity/CallForwarder.sol
  test/helpers/contracts.ts
  test/helpers/index.ts
  test/suites/dev-frontier-template/test-pov/test-evm-over-pov.ts
  test/suites/dev-frontier-template/test-pov/test-evm-over-pov2.ts
  test/suites/dev-frontier-template/test-pov/test-precompile-over-pov.ts
  test/suites/dev-frontier-template/test-pov/test-precompile-over-pov2.ts
  test/suites/dev-frontier-template/test-precompiles/test-precompile-pallet-xcm.ts
  test/suites/dev-frontier-template/test-precompiles/test-precompile-proxy.ts
Labels: B7-runtimenoteworthy, breaking, D3-trivial

#713 Check that para id has been reserved
  solo-chains/runtime/dancelight/src/genesis_config_presets.rs
  solo-chains/runtime/dancelight/src/lib.rs
  solo-chains/runtime/dancelight/src/tests/collator_assignment_tests.rs
  solo-chains/runtime/dancelight/src/tests/core_scheduling_tests.rs
  solo-chains/runtime/dancelight/src/tests/integration_test.rs
  solo-chains/runtime/dancelight/src/tests/relay_registrar.rs
  solo-chains/runtime/dancelight/src/tests/services_payment.rs
  test/suites/dev-tanssi-relay/collator-assignment/test-configurable-priority.ts
  test/suites/dev-tanssi-relay/pallet-data-preservers/test_pallet_data_preservers.ts
  test/suites/dev-tanssi-relay/registrar/test_registrars.ts
  test/suites/zombie-tanssi-relay/test-tanssi-relay.ts
Labels: B7-runtimenoteworthy, breaking, D3-trivial

#721 Add pallet_registrar benchmarks to starlight
  pallets/registrar/src/benchmarks.rs
  pallets/registrar/src/lib.rs
  pallets/registrar/src/weights.rs
  primitives/traits/src/lib.rs
  solo-chains/runtime/dancelight/src/lib.rs
  solo-chains/runtime/dancelight/src/weights/mod.rs
  solo-chains/runtime/dancelight/src/weights/pallet_registrar.rs
  tools/benchmark-all-runtimes.sh
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#720 Support Stream Payment for Data Preservers assignement
  client/consensus/src/manual_seal.rs
  client/service-container-chain/src/data_preservers.rs
  pallets/registrar/src/lib.rs
  pallets/stream-payment/src/lib.rs
  runtime/dancebox/src/lib.rs
  runtime/flashbox/src/lib.rs
  solo-chains/runtime/dancelight/src/tests/core_scheduling_tests.rs
  solo-chains/runtime/dancelight/src/tests/integration_test.rs
  solo-chains/runtime/dancelight/src/tests/relay_registrar.rs
  solo-chains/runtime/dancelight/src/tests/services_payment.rs
  test/configs/zombieDataPreservers.json
  test/moonwall.config.json
  test/suites/common-tanssi-parachain/pallet-data-preservers/test_pallet_data_preservers.ts
  test/suites/data-preservers/test_data_preservers.ts
  typescript-api/src/dancebox/interfaces/augment-api-tx.ts
  typescript-api/src/dancebox/interfaces/lookup.ts
  typescript-api/src/dancebox/interfaces/types-lookup.ts
  typescript-api/src/flashbox/interfaces/augment-api-tx.ts
  typescript-api/src/flashbox/interfaces/lookup.ts
  typescript-api/src/flashbox/interfaces/types-lookup.ts
Labels: a0-pleasereview, B5-clientnoteworthy, B7-runtimenoteworthy, D9-needsaudit👮, not-breaking

#725 Add wasm-precompiled feature to tanssi-relay binary
  solo-chains/client/cli/src/cli.rs
  solo-chains/client/cli/src/command.rs
  solo-chains/node/tanssi-relay-service/src/dev_service.rs
  test/configs/zombieDancelight.json
  test/moonwall.config.json
Labels: B5-clientnoteworthy, D3-trivial, not-breaking

#724 BEEFY Testing
  Cargo.lock
  pnpm-lock.yaml
  solo-chains/runtime/dancelight/Cargo.toml
  solo-chains/runtime/dancelight/src/lib.rs
  solo-chains/runtime/dancelight/src/tests/beefy.rs
  solo-chains/runtime/dancelight/src/tests/common/mod.rs
  solo-chains/runtime/dancelight/src/tests/mod.rs
  test/package.json
  test/suites/common-all/fee_balance_transfer/test_fee_balance_transfer.ts
  test/suites/common-xcm-parachain/xcm/test-xcm-dry-run-api.ts
  test/suites/dev-tanssi-relay/beefy/test-beefy-digests.ts
  test/suites/dev-tanssi-relay/beefy/test-double-voting-proofs.ts
  test/suites/dev-tanssi-relay/beefy/test-future-voting-proofs.ts
  test/suites/dev-tanssi-relay/beefy/test-set-new-genesis.ts
  typescript-api/package.json
  typescript-api/src/dancebox/interfaces/augment-api-runtime.ts
  typescript-api/src/dancebox/interfaces/augment-types.ts
  typescript-api/src/dancelight/interfaces/augment-types.ts
  typescript-api/src/flashbox/interfaces/augment-types.ts
Labels: B0-silent, D2-notlive, not-breaking

#728 Fix pallet_collator_assignment benchmarks for Dancelight
  pallets/collator-assignment/src/benchmarking.rs
  solo-chains/runtime/dancelight/src/genesis_config_presets.rs
  solo-chains/runtime/dancelight/src/lib.rs
  solo-chains/runtime/dancelight/src/weights/mod.rs
  solo-chains/runtime/dancelight/src/weights/pallet_collator_assignment.rs
  test/configs/zombieDancelight.json
Labels: a0-pleasereview, B7-runtimenoteworthy, D3-trivial, not-breaking

#731 add first job for testing starliht ugrade through zombie
  .github/workflows/release.yml
  test/configs/zombieDancelightUpgrade.json
  test/moonwall.config.json
  test/scripts/build-spec-dancelight-single.sh
  test/scripts/download-latest-rt-binaries-starlight.sh
  test/scripts/download-latest-rt-binaries.sh
  test/suites/rt-upgrade-parachain-zombienet/test-upgrade-chain.ts
  test/suites/rt-upgrade-relay-zombienet/test-upgrade-chain.ts
Labels: B0-silent, breaking, D3-trivial

#730 Update polkadot-sdk to include metrics fix
  Cargo.lock
Labels: B0-silent, D3-trivial, not-breaking

#729 Fix zombie_tanssi_one_node test
  test/suites/one-node/test_tanssi_one_node.ts
Labels: B0-silent, D3-trivial, not-breaking

#732 Add starlight support to version bump script
  runtime/flashbox/src/lib.rs
  scripts/bump-runtime-versions.sh
Labels: B0-silent, D3-trivial, not-breaking

#726 MD603 - add SudoRegistrar proxy
  pallets/registrar/src/benchmarks.rs
  solo-chains/runtime/dancelight/src/bridge_to_ethereum_config.rs
  solo-chains/runtime/dancelight/src/lib.rs
  solo-chains/runtime/dancelight/src/tests/ethereum_client.rs
  test/suites/dev-tanssi-relay/proxy/test-proxy-registrar.ts
  typescript-api/src/dancelight/interfaces/augment-api-tx.ts
  typescript-api/src/dancelight/interfaces/lookup.ts
  typescript-api/src/dancelight/interfaces/types-lookup.ts
Labels: a0-pleasereview, B7-runtimenoteworthy, breaking, D5-nicetohaveaudit⚠️

#734 Runtime change required for bridge to work
  Cargo.lock
  Cargo.toml
  runtime/common/Cargo.toml
  runtime/common/src/migrations.rs
  solo-chains/runtime/dancelight/Cargo.toml
  solo-chains/runtime/dancelight/src/lib.rs
  solo-chains/runtime/dancelight/src/tests/common/mod.rs
  solo-chains/runtime/dancelight/src/tests/migrations_test.rs
  solo-chains/runtime/dancelight/src/tests/mod.rs
  test/suites/dev-tanssi-relay/chain-spec/test_chain_spec.ts
  typescript-api/src/dancelight/interfaces/augment-api-query.ts
  typescript-api/src/dancelight/interfaces/lookup.ts
  typescript-api/src/dancelight/interfaces/registry.ts
  typescript-api/src/dancelight/interfaces/types-lookup.ts
Labels: B7-runtimenoteworthy, breaking, D1-runtime-migration, D5-nicetohaveaudit⚠️

#735 Starlight: smoke tests setup
  test/moonwall.config.json
  test/suites/smoke-test-common-all/test-block-finalized.ts
  test/suites/smoke-test-common-all/test-collator-number-consistency.ts
  test/suites/smoke-test-common-all/test-consistency-services-payment.ts
  test/suites/smoke-test-common-all/test-proxy.ts
  test/suites/smoke-test-common-all/test-supply-variance.ts
  test/suites/smoke-test-common-parachain/test-authority-consistency-assignation.ts
  test/suites/smoke-test-common-parachain/test-block-author-logs.ts
  test/suites/smoke-test-common-parachain/test-configuration-consistency.ts
  test/suites/smoke-test-common-parachain/test-inflation-rewards.ts
  test/suites/smoke-test-common-parachain/test-relay-storage-roots-consistency.ts
  test/suites/smoke-test-dancebox/test-invulnerables-priority.ts
  test/suites/smoke-test-dancebox/test-randomness-consistency.ts
  test/suites/smoke-test-dancebox/test-staking-consistency.ts
  test/suites/smoke-test-dancebox/test-staking-session-keys.ts
  test/suites/smoke-test-dancebox/test-treasury.ts
  test/suites/smoke-test-dancelight/test-authority-consistency-assignation.ts
  test/suites/smoke-test-dancelight/test-configuration-consistency.ts
  test/suites/smoke-test-dancelight/test-inflation-rewards.ts
Labels: B0-silent, D2-notlive, not-breaking
