Repository moondance-labs/tanssi, pull requests merged in 2025-04, with the labels that each got.

#940 [MD-884] Automatic typescript-api in PRs
  .github/workflows/cancel.yml
  .github/workflows/cmd.yml
  .github/workflows/release.yml
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#953 Test TS api generate command
  .github/workflows/cmd.yml
  .github/workflows/release.yml
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#958 update release instructions for runtimes
  .github/workflows/publish-runtime.yml
  tools/github/print-runtime-release-issue.ts
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#967 Fix swapped inflation rates in dancelight
  chains/orchestrator-relays/runtime/dancelight/src/lib.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/inflation_rates.rs
Labels: bug, a0-pleasereview, A8-mergeoncegreen, B7-runtimenoteworthy, D9-needsaudit👮, not-breaking

#943 Refactor typescript functions into utils + more lints
  biome.jsonc
  test/package.json
  test/scripts/duplicateFunctionFinder.ts
  test/suites/common-xcm-parachain/xcm/test-xcm-payment-api.ts
  test/suites/dev-tanssi-relay/beefy/test-beefy-digests.ts
  test/suites/dev-tanssi-relay/ethereum-token-transfers/test_transfer_native_token.ts
  test/suites/dev-tanssi-relay/inflation-rewards/test-rewards.ts
  test/suites/dev-tanssi-relay/staking/test_staking_rewards_balanced.ts
  test/suites/dev-tanssi-relay/staking/test_staking_rewards_non_balanced.ts
  test/suites/zombie_data_preservers/test_zombie_data_preservers.ts
  test/suites/zombie_tanssi_keep_db/test_zombie_tanssi_keep_db.ts
  test/suites/zombie_tanssi_one_node/test_zombie_tanssi_one_node.ts
  test/suites/zombie_tanssi_parathreads/test_zombie_tanssi_parathreads.ts
  test/suites/zombie_tanssi_relay_unneeded_para/test_zombie_tanssi_relay_unneeded_para.ts
  test/suites/zombie_tanssi_rotation/test_zombie_tanssi_rotation.ts
  test/suites/zombie_tanssi_warp_sync/test_zombie_tanssi_warp_sync.ts
  test/utils/block.ts
  test/utils/ethereum.ts
  test/utils/keys.ts
  test/utils/zombie.ts
Labels: A8-mergeoncegreen, B0-silent, D2-notlive, not-breaking

#965 Improve node release template
  .github/workflows/client-release-issue.yml
  tools/github/print-client-release-issue.ts
Labels: A8-mergeoncegreen, B0-silent, ci, D2-notlive, not-breaking

#971 [ExternalValidatorSlashes] Proper weight calculation inside `on_offence`
  pallets/external-validator-slashes/src/lib.rs
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#970 unhash-key script
  test/package.json
  test/scripts/unhashKey.ts
  test/scripts/utils/network.ts
Labels: A8-mergeoncegreen, B0-silent, D2-notlive, not-breaking

#972 Add xcm versioning test to chopsticks upgrade
  Cargo.lock
  test/configs/dancebox.yml
  test/configs/frontierContainer.yml
  test/configs/stagenet-dancebox.yml
  test/suites/rt-upgrade-chopsticks-frontier-template/test-upgrade-chain.ts
  test/suites/rt-upgrade-chopsticks-orchestrator/test-upgrade-chain.ts
  test/utils/block.ts
  typescript-api/src/dancebox/interfaces/augment-api-consts.ts
  typescript-api/src/dancelight/interfaces/augment-api-consts.ts
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#978 - Fix validator rewards smoke test.
  test/suites/smoke-test-dancelight/test-external-validators-rewards.ts
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#976 Test pallet versions after a migration
  .github/workflows/release.yml
  test/polkadotReleaseMapping.json
  test/suites/rt-upgrade-chopsticks-frontier-template/test-upgrade-chain.ts
  test/suites/rt-upgrade-chopsticks-orchestrator/test-upgrade-chain.ts
  test/suites/zombie_dancebox_upgrade/test_zombie_dancebox_upgrade.ts
  test/suites/zombie_dancelight_upgrade/test_zombie_dancelight_upgrade.ts
  test/suites/zombie_simple_template_upgrade/test_zombie_simple_template_upgrade.ts
  test/utils/index.ts
  test/utils/migrations.ts
Labels: A8-mergeoncegreen, B0-silent, D2-notlive, not-breaking

#983 [MD-883] Simplify running `zombie_dancebox_upgrade` locally
  .github/workflows/release.yml
  test/configs/zombie_dancebox_upgrade.json
  test/moonwall.config.json
  test/scripts/build-spec-dancebox.sh
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#985 [MD-1013] Added missing XCM Dry Run API to the dancelight runtime
  .nvmrc
  chains/orchestrator-relays/runtime/dancelight/src/lib.rs
  typescript-api/src/dancelight/interfaces/augment-api-runtime.ts
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#987 fix weights for enact candidate
  chains/orchestrator-relays/runtime/dancelight/src/weights/runtime_parachains_inclusion.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, breaking, D3-trivial

#977 Rewards utils CLI tool
  Cargo.lock
  Cargo.toml
  bin/utils/tanssi-utils/Cargo.toml
  bin/utils/tanssi-utils/README.md
  bin/utils/tanssi-utils/src/main.rs
  bin/utils/tanssi-utils/src/test-values.json
  chains/orchestrator-relays/runtime/dancelight/src/tests/external_validators_tests.rs
  pallets/external-validators-rewards/src/lib.rs
  pallets/external-validators-rewards/src/tests.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#991 Fixed smoke test for Inbound channel validator reception
  test/suites/smoke-test-dancelight/test-inbound-channel-validation-reception.ts
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#981 Updated release job to publish starlight runtime artifacts for the release
  .github/workflow-templates/cargo-build/action.yml
  .github/workflows/publish-runtime.yml
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#993 Explicitly add force-debug feature to tanssi-relay
  Cargo.lock
  chains/orchestrator-relays/node/tanssi-relay/Cargo.toml
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#990 [MD-925] Improve the ETH fork versions config
  chains/orchestrator-relays/runtime/dancelight/src/bridge_to_ethereum_config.rs
  chains/orchestrator-relays/runtime/dancelight/src/eth_chain_config.rs
  chains/orchestrator-relays/runtime/dancelight/src/lib.rs
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#996 point to latest main commit in tanssi-symbiotic
  test/scripts/bridge/assets/genesis.json
  test/scripts/bridge/set-env.sh
  test/scripts/bridge/start-ethereum-node.sh
  test/scripts/bridge/ts-scripts/src/generateContractInfo.ts
  test/suites/zombie_tanssi_relay_eth_bridge/test_zombie_tanssi_relay_eth_bridge.ts
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#992 Add script to print biggest weights according to regex
  .github/workflows/release.yml
  tools/show-me-the-weights.py
Labels: A8-mergeoncegreen, B0-silent, D2-notlive, not-breaking

#969 fix: unsafe math operations
  chains/orchestrator-relays/runtime/dancelight/src/lib.rs
  pallets/author-noting/src/lib.rs
  pallets/collator-assignment/src/assignment.rs
  pallets/collator-assignment/src/lib.rs
  pallets/external-validator-slashes/src/lib.rs
  pallets/external-validators-rewards/src/lib.rs
  pallets/external-validators/src/lib.rs
  pallets/inflation-rewards/src/lib.rs
  pallets/invulnerables/src/lib.rs
  pallets/registrar/src/lib.rs
  pallets/services-payment/src/lib.rs
  pallets/xcm-core-buyer/src/lib.rs
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#986 Limit params accepted by root_test_send_msg_to_eth
  pallets/external-validator-slashes/src/benchmarking.rs
  pallets/external-validator-slashes/src/lib.rs
  typescript-api/src/dancelight/interfaces/augment-api-errors.ts
  typescript-api/src/dancelight/interfaces/lookup.ts
  typescript-api/src/dancelight/interfaces/types-lookup.ts
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1002 unsafe math leftover in pallet registrar
  pallets/registrar/src/lib.rs
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#998 [Starlight] Add dev-test suite and adapt existing TS tests
  .github/workflows/coverage.yml
  .github/workflows/release.yml
  Cargo.lock
  chains/orchestrator-relays/client/cli/Cargo.toml
  chains/orchestrator-relays/client/cli/src/command.rs
  chains/orchestrator-relays/node/tanssi-relay-service/Cargo.toml
  chains/orchestrator-relays/node/tanssi-relay-service/src/chain_spec.rs
  chains/orchestrator-relays/node/tanssi-relay/Cargo.toml
  test/README.md
  test/helpers/events.ts
  test/helpers/index.ts
  test/helpers/starlightVersions.ts
  test/moonwall.config.json
  test/suites/common-all/fee_balance_transfer/test_fee_balance_transfer.ts
  test/suites/common-all/pallet-multisig/test_pallet_multisig.ts
  test/suites/common-all/proxy/test-proxy-cancel.ts
  test/suites/common-all/proxy/test-proxy-pure.ts
  test/suites/common-all/proxy/test-proxy.ts
  test/suites/common-all/test_basic.ts
  test/suites/common-tanssi/pallet-treasury/test_pallet_treasury.ts
  test/suites/common-tanssi/registrar/test_registrar_extrinsic_permissions.ts
  test/suites/common-tanssi/services-payment/test_service_payment_removes_tank_money_and_burns.ts
  test/suites/common-tanssi/services-payment/test_service_payment_removes_tank_money_and_refunds.ts
  test/suites/common-tanssi/services-payment/test_services_payment_block_credit_buying_free_combined.ts
  test/suites/common-tanssi/services-payment/test_services_payment_collator_credit_buying_free_combined.ts
  test/suites/common-tanssi/services-payment/test_services_payment_no_free_credits.ts
  test/suites/dev-tanssi-relay/chain-spec/test_chain_spec.ts
  test/suites/dev-tanssi-relay/collator-assignment/test-configurable-priority.ts
  test/suites/dev-tanssi-relay/eth-client/test-eth-ciient-initial-checkpoint.ts
  test/suites/dev-tanssi-relay/eth-client/test-eth-ciient-submit-update-for-next-period-without-committee.ts
  test/suites/dev-tanssi-relay/eth-client/test-eth-ciient-submit-update-same-period.ts
  test/suites/dev-tanssi-relay/eth-client/test-eth-client-submit-update-cannot-be-done-without-injecting-new-committee.ts
  test/suites/dev-tanssi-relay/eth-client/test-eth-client-submit-update-next-period-with-proper-committees.ts
  test/suites/dev-tanssi-relay/ethereum-token-transfers/test_set_token_transfer_channel.ts
  test/suites/dev-tanssi-relay/ethereum-token-transfers/test_transfer_native_token.ts
  test/suites/dev-tanssi-relay/external-validators-rewards/test_external_validator_rewards.ts
  test/suites/dev-tanssi-relay/inactivity-tracking/test-inactivity-tracking.ts
  test/suites/dev-tanssi-relay/pallet-data-preservers/test_pallet_data_preservers.ts
  test/suites/dev-tanssi-relay/pallet-identity/test_pallet_identity.ts
  test/suites/dev-tanssi-relay/proxy/test-proxy-registrar.ts
  test/suites/dev-tanssi-relay/proxy/test-proxy-validator-management.ts
  test/suites/dev-tanssi-relay/proxy/test-session-keys-management.ts
  test/suites/dev-tanssi-relay/registrar/test_registrars.ts
  test/suites/dev-tanssi-relay/services-payment/test_services_payment_block_credits.ts
  test/suites/dev-tanssi-relay/services-payment/test_services_payment_collator_credits.ts
  test/suites/dev-tanssi-relay/services-payment/test_services_payment_collator_tip.ts
  test/suites/dev-tanssi-relay/staking/test_staking_join.ts
  test/suites/dev-tanssi-relay/staking/test_staking_rewards_balanced.ts
  test/suites/dev-tanssi-relay/staking/test_staking_rewards_non_balanced.ts
  test/suites/dev-tanssi-relay/staking/test_staking_session.ts
  test/suites/dev-tanssi-relay/staking/test_staking_summaries.ts
  test/suites/dev-tanssi-relay/staking/test_staking_swap.ts
  test/suites/dev-tanssi-relay/xcm/test-reserve-transfer-downwards.ts
  test/suites/dev-tanssi-relay/xcm/test-xcm-send-downward.ts
  test/suites/dev-tanssi-relay/xcm/test-xcm-send-upward.ts
  test/utils/constants.ts
Labels: A8-mergeoncegreen, B5-clientnoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#1004 Fix on_offence weight when slashing is disabled
  pallets/external-validator-slashes/src/lib.rs
  pallets/external-validator-slashes/src/mock.rs
  pallets/external-validator-slashes/src/tests.rs
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1001 Add starlight bench
  .github/workflows/merge-when-ready.yml
  tools/benchmark-all-runtimes.sh
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1005 Pass fast-runtime feature to nextest
  .config/nextest.toml
  .github/workflows/release.yml
  chains/orchestrator-relays/runtime/dancelight/src/tests/slashes.rs
  chains/orchestrator-relays/runtime/starlight/src/tests/slashes.rs
Labels: A8-mergeoncegreen, B0-silent, D2-notlive, not-breaking

#1007 Add missing log in external-validators-rewards
  pallets/external-validators-rewards/src/lib.rs
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking
