Repository moondance-labs/tanssi, pull requests merged in 2025-03, with the labels that each got.

#878 More StreamPayment config
  Cargo.lock
  chains/orchestrator-paras/runtime/common/Cargo.toml
  chains/orchestrator-paras/runtime/common/src/migrations.rs
  chains/orchestrator-paras/runtime/dancebox/src/tests/integration_test.rs
  chains/orchestrator-paras/runtime/flashbox/src/tests/integration_test.rs
  pallets/stream-payment/Cargo.toml
  pallets/stream-payment/src/benchmarking.rs
  pallets/stream-payment/src/lib.rs
  pallets/stream-payment/src/migrations.rs
  pallets/stream-payment/src/tests.rs
  test/suites/zombie_data_preservers/test_zombie_data_preservers.ts
  tools/iforgor/tanssi.toml
  typescript-api/src/dancebox/interfaces/augment-api-errors.ts
  typescript-api/src/dancebox/interfaces/augment-api-tx.ts
  typescript-api/src/dancebox/interfaces/lookup.ts
  typescript-api/src/dancebox/interfaces/types-lookup.ts
  typescript-api/src/flashbox/interfaces/augment-api-errors.ts
  typescript-api/src/flashbox/interfaces/augment-api-tx.ts
  typescript-api/src/flashbox/interfaces/lookup.ts
  typescript-api/src/flashbox/interfaces/types-lookup.ts
Labels: a0-pleasereview, A8-mergeoncegreen, B7-runtimenoteworthy, breaking, D9-needsaudit👮

#897 fix docker comp
  .github/workflows/release.yml
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#898 In case of fresh chain, we don't have enough history to check the RewardPointsForEra
  test/suites/smoke-test-dancelight/test-external-validators-rewards.ts
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#874 MD867 - Enable/Disable Slashing
  .github/workflows/merge-when-ready.yml
  .github/workflows/release.yml
  chains/container-chains/runtime-templates/simple/src/lib.rs
  chains/orchestrator-paras/node/src/command/solochain.rs
  chains/orchestrator-paras/node/src/service.rs
  chains/orchestrator-paras/runtime/dancebox/src/lib.rs
  chains/orchestrator-paras/runtime/flashbox/src/lib.rs
  chains/orchestrator-relays/node/tanssi-relay-service/src/dev_rpcs.rs
  chains/orchestrator-relays/node/tanssi-relay-service/src/dev_service.rs
  chains/orchestrator-relays/runtime/dancelight/constants/src/lib.rs
  chains/orchestrator-relays/runtime/dancelight/src/bridge_to_ethereum_config.rs
  chains/orchestrator-relays/runtime/dancelight/src/lib.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/common/mod.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/common/xcm/mocknets.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/external_validators_tests.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/inbound_queue_tests/integration_tests.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/inbound_queue_tests/message_processor_tests.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/migrations_test.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/slashes.rs
  chains/orchestrator-relays/runtime/dancelight/src/weights/pallet_external_validator_slashes.rs
  chains/orchestrator-relays/runtime/dancelight/src/xcm_config.rs
  client/manual-randomness/src/lib.rs
  client/node-common/src/service.rs
  client/service-container-chain/src/data_preservers.rs
  pallets/configuration/src/lib.rs
  pallets/external-validator-slashes/src/benchmarking.rs
  pallets/external-validator-slashes/src/lib.rs
  pallets/external-validator-slashes/src/weights.rs
  pallets/external-validators-rewards/src/lib.rs
  pallets/external-validators/src/lib.rs
  pallets/ocw-testing/src/lib.rs
  pallets/services-payment/src/tests.rs
  primitives/bridge/src/benchmarks.rs
  primitives/bridge/src/lib.rs
  primitives/bridge/src/symbiotic_message_processor.rs
  primitives/bridge/src/tests.rs
  primitives/traits/src/lib.rs
  test/suites/dev-tanssi-relay/slashes/test_slashingmodes.ts
  typescript-api/src/dancelight/interfaces/augment-api-query.ts
  typescript-api/src/dancelight/interfaces/augment-api-tx.ts
  typescript-api/src/dancelight/interfaces/lookup.ts
  typescript-api/src/dancelight/interfaces/registry.ts
  typescript-api/src/dancelight/interfaces/types-lookup.ts
Labels: a0-pleasereview, A8-mergeoncegreen, B7-runtimenoteworthy, breaking, D5-nicetohaveaudit⚠️

#892 Removed runtime build with fast-runtime feature
  chains/orchestrator-relays/node/tanssi-relay-service/src/chain_spec.rs
  chains/orchestrator-relays/runtime/dancelight/build.rs
  chains/orchestrator-relays/runtime/dancelight/src/lib.rs
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#884 AuthorNoting should only deal with parachains with assigned collators (instead of all)
  chains/orchestrator-paras/node/src/service.rs
  chains/orchestrator-paras/runtime/dancebox/src/lib.rs
  chains/orchestrator-paras/runtime/flashbox/src/lib.rs
  chains/orchestrator-relays/runtime/dancelight/src/lib.rs
  pallets/author-noting/src/benchmarks.rs
  pallets/author-noting/src/lib.rs
  pallets/author-noting/src/mock.rs
  pallets/author-noting/src/tests.rs
  pallets/collator-assignment/runtime-api/src/lib.rs
  pallets/collator-assignment/src/lib.rs
  primitives/traits/src/lib.rs
  test/suites/dev-tanssi/weights/test_set_latest_author_data_weight.ts
  typescript-api/src/dancebox/interfaces/augment-api-consts.ts
  typescript-api/src/dancelight/interfaces/augment-api-consts.ts
  typescript-api/src/flashbox/interfaces/augment-api-consts.ts
Labels: A8-mergeoncegreen, B3-apinoteworthy, B5-clientnoteworthy, B7-runtimenoteworthy, D9-needsaudit👮, not-breaking

#902 fix check wasm size
  .github/workflows/release.yml
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#901 New smoke test for slahes
  test/suites/smoke-test-dancelight/test-external-validator-slashes.ts
  test/utils/block.ts
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#906 Add weights for pallet_transaction_payment and frame_system::extensions
  benchmarking/frame-weight-runtime-template.hbs
  chains/container-chains/runtime-templates/frontier/src/lib.rs
  chains/container-chains/runtime-templates/frontier/src/weights/frame_system_extensions.rs
  chains/container-chains/runtime-templates/frontier/src/weights/mod.rs
  chains/container-chains/runtime-templates/simple/src/lib.rs
  chains/container-chains/runtime-templates/simple/src/weights/frame_system_extensions.rs
  chains/container-chains/runtime-templates/simple/src/weights/mod.rs
  chains/container-chains/runtime-templates/simple/src/weights/pallet_transaction_payment.rs
  chains/orchestrator-paras/runtime/dancebox/src/lib.rs
  chains/orchestrator-paras/runtime/dancebox/src/weights/frame_system_extensions.rs
  chains/orchestrator-paras/runtime/dancebox/src/weights/mod.rs
  chains/orchestrator-paras/runtime/dancebox/src/weights/pallet_transaction_payment.rs
  chains/orchestrator-paras/runtime/flashbox/src/lib.rs
  chains/orchestrator-paras/runtime/flashbox/src/weights/frame_system_extensions.rs
  chains/orchestrator-paras/runtime/flashbox/src/weights/mod.rs
  chains/orchestrator-paras/runtime/flashbox/src/weights/pallet_transaction_payment.rs
  chains/orchestrator-relays/runtime/dancelight/src/lib.rs
  chains/orchestrator-relays/runtime/dancelight/src/weights/frame_system_extensions.rs
  chains/orchestrator-relays/runtime/dancelight/src/weights/mod.rs
  chains/orchestrator-relays/runtime/dancelight/src/weights/pallet_transaction_payment.rs
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#908 Add sepolia
  chains/orchestrator-relays/runtime/dancelight/src/bridge_to_ethereum_config.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, breaking, D9-needsaudit👮

#909 add new chain id for sovereign account
  chains/orchestrator-relays/runtime/dancelight/constants/src/lib.rs
  chains/orchestrator-relays/runtime/dancelight/src/lib.rs
  test/suites/dev-tanssi-relay/ethereum-token-transfers/test_transfer_native_token.ts
  test/suites/dev-tanssi-relay/external-validators-rewards/test_external_validator_rewards.ts
  test/suites/smoke-test-dancelight/test-external-validators-rewards.ts
  test/utils/constants.ts
  test/utils/ethereum.ts
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, breaking, D9-needsaudit👮

#907 [MD-920] Refactor get_account_id_from_seed / get_from_seed to one common place
  Cargo.lock
  chains/container-chains/nodes/simple/Cargo.toml
  chains/container-chains/nodes/simple/src/chain_spec.rs
  chains/orchestrator-paras/node/Cargo.toml
  chains/orchestrator-paras/node/src/chain_spec/dancebox.rs
  chains/orchestrator-paras/node/src/chain_spec/flashbox.rs
  chains/orchestrator-paras/node/src/chain_spec/mod.rs
  chains/orchestrator-paras/runtime/dancebox/Cargo.toml
  chains/orchestrator-paras/runtime/dancebox/src/tests/common/xcm/constants.rs
  chains/orchestrator-relays/node/tanssi-relay-service/src/chain_spec.rs
  chains/orchestrator-relays/runtime/dancelight/Cargo.toml
  chains/orchestrator-relays/runtime/dancelight/src/genesis_config_presets.rs
  chains/orchestrator-relays/runtime/dancelight/src/lib.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/beefy.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/collator_assignment_tests.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/common/mod.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/common/xcm/bridge_to_eth.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/common/xcm/constants.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/core_scheduling_tests.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/external_validators_tests.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/inbound_queue_tests/integration_tests.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/inbound_queue_tests/message_processor_tests.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/session_keys.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/staking.rs
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#903 [MD-933] RegistrarOrigin is configured to EnsureRoot in dancelight
  chains/orchestrator-paras/runtime/dancebox/src/lib.rs
  chains/orchestrator-paras/runtime/dancebox/src/tests/integration_test.rs
  chains/orchestrator-paras/runtime/flashbox/src/lib.rs
  chains/orchestrator-paras/runtime/flashbox/src/tests/integration_test.rs
  chains/orchestrator-relays/runtime/dancelight/src/lib.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/integration_test.rs
  pallets/registrar/src/lib.rs
  test/suites/common-tanssi/registrar/test_registrar_extrinsic_permissions.ts
Labels: A8-mergeoncegreen, B0-silent, breaking, D5-nicetohaveaudit⚠️

#905 Add StreamPayment to Dancelight and wire it to DataPreservers
  Cargo.lock
  chains/orchestrator-paras/node/src/chain_spec/dancebox.rs
  chains/orchestrator-paras/node/src/chain_spec/flashbox.rs
  chains/orchestrator-paras/runtime/dancebox/src/lib.rs
  chains/orchestrator-paras/runtime/dancebox/src/tests/common/mod.rs
  chains/orchestrator-paras/runtime/dancebox/src/tests/integration_test.rs
  chains/orchestrator-paras/runtime/flashbox/src/lib.rs
  chains/orchestrator-paras/runtime/flashbox/src/tests/integration_test.rs
  chains/orchestrator-relays/runtime/dancelight/Cargo.toml
  chains/orchestrator-relays/runtime/dancelight/src/lib.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/integration_test.rs
  chains/orchestrator-relays/runtime/dancelight/src/weights/mod.rs
  chains/orchestrator-relays/runtime/dancelight/src/weights/pallet_stream_payment.rs
  test/suites/dev-tanssi-relay/pallet-data-preservers/test_pallet_data_preservers.ts
  test/suites/dev-tanssi-relay/proxy/test-proxy-registrar.ts
  typescript-api/src/dancebox/interfaces/augment-api-tx.ts
  typescript-api/src/dancebox/interfaces/lookup.ts
  typescript-api/src/dancebox/interfaces/registry.ts
  typescript-api/src/dancebox/interfaces/types-lookup.ts
  typescript-api/src/dancelight/interfaces/augment-api-consts.ts
  typescript-api/src/dancelight/interfaces/augment-api-errors.ts
  typescript-api/src/dancelight/interfaces/augment-api-events.ts
  typescript-api/src/dancelight/interfaces/augment-api-query.ts
  typescript-api/src/dancelight/interfaces/augment-api-tx.ts
  typescript-api/src/dancelight/interfaces/lookup.ts
  typescript-api/src/dancelight/interfaces/registry.ts
  typescript-api/src/dancelight/interfaces/types-lookup.ts
  typescript-api/src/flashbox/interfaces/augment-api-tx.ts
  typescript-api/src/flashbox/interfaces/lookup.ts
  typescript-api/src/flashbox/interfaces/registry.ts
  typescript-api/src/flashbox/interfaces/types-lookup.ts
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, breaking, D9-needsaudit👮

#893 CI: ⚙️ Improve E2E Setup
  .github/workflow-templates/bridge-e2e/action.yml
  .github/workflow-templates/zombienet-tests/action.yml
  .github/workflows/merge-when-ready.yml
  test/.gitignore
  test/README.md
  test/scripts/bridge/build-ethereum-node.sh
  test/scripts/bridge/cleanup.sh
  test/scripts/bridge/set-env.sh
  test/scripts/bridge/start-ethereum-node.sh
Labels: A8-mergeoncegreen, B0-silent, D2-notlive, D3-trivial

#824 Add CODEOWNERS to .github folder
  .github/CODEOWNERS
Labels: A8-mergeoncegreen, B0-silent, D2-notlive, not-breaking

#915 Add benchmark pallet transaction payment to frontier
  Cargo.lock
  chains/container-chains/runtime-templates/frontier/src/lib.rs
  chains/container-chains/runtime-templates/frontier/src/weights/mod.rs
  chains/container-chains/runtime-templates/frontier/src/weights/pallet_transaction_payment.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, D3-trivial, not-breaking

#916 Use middleware v2 in e2e test
  test/scripts/bridge/deploy-ethereum-contracts.sh
  test/scripts/bridge/set-env.sh
  test/suites/zombie_tanssi_relay_eth_bridge/test_zombie_tanssi_relay_eth_bridge.ts
Labels: A8-mergeoncegreen, B0-silent, ci, D2-notlive

#912 Add e2e test for token transfers
  pallets/ethereum-token-transfers/src/lib.rs
  test/scripts/bridge/set-env.sh
  test/scripts/bridge/setup-relayer.sh
  test/scripts/bridge/start-relayer.sh
  test/suites/zombie_tanssi_relay_eth_bridge/test_zombie_tanssi_relay_eth_bridge.ts
  test/utils/constants.ts
Labels: A8-mergeoncegreen, B0-silent, D2-notlive, not-breaking

#918 Update e2e test to be compatible with latest middleware version
  test/scripts/bridge/set-env.sh
  test/suites/zombie_tanssi_relay_eth_bridge/test_zombie_tanssi_relay_eth_bridge.ts
Labels: A8-mergeoncegreen, B0-silent, ci, D2-notlive

#920 Fix Dockerfile maintainer label
  docker/container-chain-evm-template.Dockerfile
  docker/container-chain-simple-template.Dockerfile
  docker/starlight.Dockerfile
  docker/tanssi.Dockerfile
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#914 Update StreamPayment storage deposit
  chains/orchestrator-paras/runtime/dancebox/src/lib.rs
  chains/orchestrator-paras/runtime/flashbox/src/lib.rs
  chains/orchestrator-relays/runtime/dancelight/src/lib.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/integration_test.rs
  test/suites/common-tanssi-parachain/stream-payment/test_stream_payment.ts
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, D3-trivial, not-breaking

#910 Fix inflation rates in dancelight
  Cargo.lock
  chains/orchestrator-relays/runtime/dancelight/constants/Cargo.toml
  chains/orchestrator-relays/runtime/dancelight/constants/src/lib.rs
  chains/orchestrator-relays/runtime/dancelight/src/lib.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/inflation_rates.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/mod.rs
  primitives/traits/src/lib.rs
  primitives/traits/src/prod_or_fast.rs
  test/suites/dev-tanssi-relay/inflation-rewards/test-rewards.ts
  test/suites/dev-tanssi-relay/staking/test_staking_rewards_balanced.ts
  test/suites/dev-tanssi-relay/staking/test_staking_rewards_non_balanced.ts
  tools/iforgor/tanssi.toml
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, breaking, D9-needsaudit👮

#919 Remove some clones from block seal function
  client/consensus/src/collators.rs
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#923 StreamPayment/DataPreservers common types for all runtimes
  Cargo.lock
  Cargo.toml
  chains/orchestrator-paras/node/Cargo.toml
  chains/orchestrator-paras/node/src/chain_spec/dancebox.rs
  chains/orchestrator-paras/node/src/chain_spec/flashbox.rs
  chains/orchestrator-paras/runtime/common/src/migrations.rs
  chains/orchestrator-paras/runtime/dancebox/Cargo.toml
  chains/orchestrator-paras/runtime/dancebox/src/lib.rs
  chains/orchestrator-paras/runtime/dancebox/src/tests/common/mod.rs
  chains/orchestrator-paras/runtime/dancebox/src/tests/integration_test.rs
  chains/orchestrator-paras/runtime/flashbox/Cargo.toml
  chains/orchestrator-paras/runtime/flashbox/src/lib.rs
  chains/orchestrator-paras/runtime/flashbox/src/tests/integration_test.rs
  chains/orchestrator-relays/runtime/dancelight/Cargo.toml
  chains/orchestrator-relays/runtime/dancelight/src/genesis_config_presets.rs
  chains/orchestrator-relays/runtime/dancelight/src/lib.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/common/mod.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/integration_test.rs
  pallets/data-preservers/src/benchmarks.rs
  pallets/data-preservers/src/lib.rs
  pallets/data-preservers/src/mock.rs
  pallets/data-preservers/src/types.rs
  pallets/stream-payment/src/benchmarking.rs
  pallets/stream-payment/src/lib.rs
  pallets/stream-payment/src/mock.rs
  pallets/stream-payment/src/tests.rs
  primitives/data-preservers-common/Cargo.toml
  primitives/data-preservers-common/src/lib.rs
  primitives/stream-payment-common/Cargo.toml
  primitives/stream-payment-common/src/lib.rs
  typescript-api/src/dancebox/interfaces/augment-api-errors.ts
  typescript-api/src/dancebox/interfaces/augment-api-tx.ts
  typescript-api/src/dancebox/interfaces/lookup.ts
  typescript-api/src/dancebox/interfaces/registry.ts
  typescript-api/src/dancebox/interfaces/types-lookup.ts
  typescript-api/src/dancelight/interfaces/augment-api-errors.ts
  typescript-api/src/dancelight/interfaces/augment-api-tx.ts
  typescript-api/src/dancelight/interfaces/lookup.ts
  typescript-api/src/dancelight/interfaces/registry.ts
  typescript-api/src/dancelight/interfaces/types-lookup.ts
  typescript-api/src/flashbox/interfaces/augment-api-errors.ts
  typescript-api/src/flashbox/interfaces/augment-api-tx.ts
  typescript-api/src/flashbox/interfaces/lookup.ts
  typescript-api/src/flashbox/interfaces/registry.ts
  typescript-api/src/flashbox/interfaces/types-lookup.ts
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#917 [MD-952] The storage deposit for container-chain registration is insufficient
  chains/orchestrator-paras/runtime/dancebox/src/lib.rs
  chains/orchestrator-paras/runtime/dancebox/src/weights/pallet_registrar.rs
  chains/orchestrator-paras/runtime/flashbox/src/lib.rs
  chains/orchestrator-paras/runtime/flashbox/src/weights/pallet_registrar.rs
  chains/orchestrator-relays/runtime/dancelight/src/lib.rs
  chains/orchestrator-relays/runtime/dancelight/src/weights/pallet_registrar.rs
  pallets/registrar/src/benchmarks.rs
  pallets/registrar/src/lib.rs
  pallets/registrar/src/mock.rs
  pallets/registrar/src/tests.rs
  pallets/registrar/src/weights.rs
  test/suites/dev-tanssi/register-with-relay-proof/test_deregister_with_relay_proof.ts
  typescript-api/src/dancebox/interfaces/augment-api-consts.ts
  typescript-api/src/dancelight/interfaces/augment-api-consts.ts
  typescript-api/src/flashbox/interfaces/augment-api-consts.ts
Labels: A8-mergeoncegreen, B0-silent, breaking, D5-nicetohaveaudit⚠️

#935 Add reward checking to ethereum tests and other fixes
  .github/workflows/merge-when-ready.yml
  test/scripts/bridge/set-env.sh
  test/suites/zombie_tanssi_relay_eth_bridge/test_zombie_tanssi_relay_eth_bridge.ts
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#927 Add Dancelight specs to CLI option
  chains/orchestrator-relays/node/tanssi-relay-service/chain-specs/dancelight-raw-specs.json
  chains/orchestrator-relays/node/tanssi-relay-service/src/chain_spec.rs
Labels: A8-mergeoncegreen, B5-clientnoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#938 [MD-942] Expose rpc_rate_limit* cli options to parachains
  Cargo.lock
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#936 Bump node and runtime versions to 0.13.0 and 1300
  Cargo.lock
  chains/container-chains/nodes/frontier/Cargo.toml
  chains/container-chains/nodes/simple/Cargo.toml
  chains/container-chains/runtime-templates/frontier/src/lib.rs
  chains/container-chains/runtime-templates/simple/src/lib.rs
  chains/orchestrator-paras/node/Cargo.toml
  chains/orchestrator-paras/runtime/dancebox/src/lib.rs
  chains/orchestrator-paras/runtime/flashbox/src/lib.rs
  chains/orchestrator-relays/client/cli/Cargo.toml
  chains/orchestrator-relays/node/tanssi-relay-service/Cargo.toml
  chains/orchestrator-relays/node/tanssi-relay/Cargo.toml
  chains/orchestrator-relays/runtime/dancelight/src/lib.rs
  client/service-container-chain/Cargo.toml
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#931 Use 12 decimals for UNIT
  chains/orchestrator-paras/runtime/dancebox/src/tests/common/mod.rs
  chains/orchestrator-paras/runtime/dancebox/src/tests/integration_test.rs
  chains/orchestrator-paras/runtime/flashbox/src/tests/common/mod.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/common/mod.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/staking.rs
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#933 Fix some easy javascript lints
  biome.jsonc
  test/scripts/deriveTestIds.ts
  test/suites/smoke-test-common-parachain/test-block-author-logs.ts
  test/suites/smoke-test-dancelight/test-babe.ts
  test/suites/zombie_tanssi_one_node/test_zombie_tanssi_one_node.ts
  test/suites/zombie_tanssi_parathreads/test_zombie_tanssi_parathreads.ts
  test/suites/zombie_tanssi_rotation/test_zombie_tanssi_rotation.ts
  test/utils/genesis-data.ts
  test/utils/xcm.ts
  typescript-api/scripts/generate-types.ts
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#942 Disable polkadot binary checksum check in unsupported archs
  test/polkadotReleaseMapping.json
  test/scripts/download-polkadot.sh
  test/scripts/downloadPolkadot.ts
Labels: A8-mergeoncegreen, B0-silent, D2-notlive, not-breaking

#946 Update polkadot-sdk to include missing cherry-pick about metrics
  Cargo.lock
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#947 test slashes in the e2e tests
  test/scripts/bridge/set-env.sh
  test/suites/zombie_tanssi_relay_eth_bridge/test_zombie_tanssi_relay_eth_bridge.ts
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#948 Fixed Inbound channel validation reception
  test/suites/smoke-test-dancelight/test-inbound-channel-validation-reception.ts
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#934 [MD-952][part 2] Update usage of `ContainerChainGenesisData` from `dancekit` lib
  Cargo.lock
  chains/orchestrator-paras/node/src/chain_spec/dancebox.rs
  chains/orchestrator-paras/node/src/chain_spec/flashbox.rs
  chains/orchestrator-paras/runtime/dancebox/src/tests/integration_test.rs
  chains/orchestrator-paras/runtime/flashbox/src/tests/integration_test.rs
  chains/orchestrator-relays/node/tanssi-relay-service/src/chain_spec.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/common/mod.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/integration_test.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/relay_registrar.rs
  client/service-container-chain/src/cli.rs
  pallets/registrar/src/benchmarks.rs
  pallets/registrar/src/lib.rs
  pallets/registrar/src/tests.rs
  typescript-api/src/dancebox/interfaces/lookup.ts
  typescript-api/src/dancebox/interfaces/types-lookup.ts
  typescript-api/src/dancelight/interfaces/lookup.ts
  typescript-api/src/dancelight/interfaces/types-lookup.ts
  typescript-api/src/flashbox/interfaces/lookup.ts
  typescript-api/src/flashbox/interfaces/types-lookup.ts
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#951 - Fix for inbound channel reception - pending external index
  test/suites/smoke-test-dancelight/test-inbound-channel-validation-reception.ts
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#950 Remove unused dependencies from Cargo.toml
  Cargo.toml
Labels: A8-mergeoncegreen, B0-silent, D2-notlive, not-breaking

#952 Fix dancelight inflation
  chains/orchestrator-relays/runtime/dancelight/src/lib.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/inflation_rates.rs
Labels: bug, A8-mergeoncegreen, B7-runtimenoteworthy, D9-needsaudit👮, not-breaking
