Repository moondance-labs/tanssi, pull requests merged in 2025-01, with the labels that each got.

#796 update polkadot api and other dependencies in typescript-api
  pnpm-lock.yaml
  typescript-api/package.json
Labels: B0-silent, D2-notlive, not-breaking

#783 Fix: benchmarking for pallet-data-preservers and pallet-registrar on Dancelight
  .gitignore
  chains/orchestrator-relays/runtime/dancelight/src/lib.rs
  chains/orchestrator-relays/runtime/dancelight/src/weights/mod.rs
  chains/orchestrator-relays/runtime/dancelight/src/weights/pallet_data_preservers.rs
  pallets/data-preservers/src/benchmarks.rs
  pallets/registrar/src/benchmarks.rs
  pallets/registrar/src/lib.rs
  primitives/traits/src/lib.rs
  tools/dev-benchmark-pallet.sh
Labels: B0-silent, D3-trivial, not-breaking

#797 Fix bump-runtime-versions script
  scripts/bump-runtime-versions.sh
Labels: B0-silent, D3-trivial, not-breaking

#798 Fix publish runtime scripts
  .github/workflows/publish-runtime-chevdor.yml
  .github/workflows/publish-runtime.yml
Labels: B0-silent, D3-trivial, not-breaking

#787 Refactor on_container_author_noted hook to take a Vec
  chains/orchestrator-paras/runtime/dancebox/src/weights/pallet_author_noting.rs
  chains/orchestrator-paras/runtime/dancebox/src/weights/pallet_services_payment.rs
  chains/orchestrator-paras/runtime/flashbox/src/weights/pallet_author_noting.rs
  chains/orchestrator-paras/runtime/flashbox/src/weights/pallet_services_payment.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/inflation_rewards.rs
  chains/orchestrator-relays/runtime/dancelight/src/weights/pallet_author_noting.rs
  chains/orchestrator-relays/runtime/dancelight/src/weights/pallet_services_payment.rs
  pallets/author-noting/src/benchmarks.rs
  pallets/author-noting/src/lib.rs
  pallets/author-noting/src/weights.rs
  pallets/inflation-rewards/src/lib.rs
  pallets/inflation-rewards/src/tests.rs
  pallets/services-payment/src/benchmarks.rs
  pallets/services-payment/src/lib.rs
  pallets/services-payment/src/tests.rs
  pallets/services-payment/src/weights.rs
  pallets/xcm-core-buyer/src/lib.rs
  pallets/xcm-core-buyer/src/tests.rs
  primitives/traits/src/lib.rs
  test/suites/common-tanssi-parachain/services-payment/test_services_payment_block_credits.ts
  test/suites/common-tanssi-parachain/services-payment/test_services_payment_collator_credits.ts
  test/suites/dev-tanssi/weights/test_set_latest_author_data_weight.ts
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#804 Unit tests for bridge message Solidity encoding
  Cargo.lock
  primitives/bridge/Cargo.toml
  primitives/bridge/src/lib.rs
  primitives/bridge/src/tests.rs
Labels: a0-pleasereview, B0-silent, D3-trivial, not-breaking

#807 Add more tests for `ExternalValidatorsRewards` pallet
  chains/orchestrator-relays/runtime/dancelight/src/lib.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/common/mod.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/external_validators_tests.rs
  pallets/external-validators-rewards/src/lib.rs
  pallets/external-validators-rewards/src/mock.rs
  pallets/external-validators-rewards/src/tests.rs
  primitives/bridge/src/lib.rs
  typescript-api/src/dancelight/interfaces/augment-api-events.ts
  typescript-api/src/dancelight/interfaces/lookup.ts
  typescript-api/src/dancelight/interfaces/registry.ts
  typescript-api/src/dancelight/interfaces/types-lookup.ts
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#799 dev-benchmark-pallet: automatically benchmark runtimes
  tools/dev-benchmark-pallet.sh
Labels: B0-silent, D3-trivial, not-breaking

#809 Add test that tip is not charged when there are enough collators
  test/suites/common-tanssi-parachain/services-payment/test_services_payment_collator_tip.ts
Labels: B0-silent, D2-notlive, not-breaking

#810 Disable sibling calls from `EthereumSystem` pallet
  chains/orchestrator-relays/runtime/dancelight/src/bridge_to_ethereum_config.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/ethereum_system.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/mod.rs
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#811 Fix lscpu regex for ubuntu 24.04
  .github/workflow-templates/typescript-tests-moonwall/action.yml
Labels: B0-silent, D2-notlive, not-breaking

#795 Do not reward whitelisted validators
  chains/orchestrator-relays/runtime/dancelight/src/lib.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/common/mod.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/external_validators_tests.rs
  chains/orchestrator-relays/runtime/dancelight/src/weights/pallet_external_validators.rs
  pallets/external-validators-rewards/src/lib.rs
  pallets/external-validators-rewards/src/mock.rs
  pallets/external-validators/src/lib.rs
  pallets/external-validators/src/tests.rs
  pallets/external-validators/src/weights.rs
  primitives/bridge/src/symbiotic_message_processor.rs
  test/suites/dev-tanssi-relay/external-validators-rewards/test-rewards-runtime-api.ts
  test/suites/dev-tanssi-relay/external-validators-rewards/test_external_validator_reward_candidates.ts
  test/suites/dev-tanssi-relay/external-validators-rewards/test_external_validator_rewards.ts
  typescript-api/src/dancelight/interfaces/augment-api-query.ts
  typescript-api/src/dancelight/interfaces/augment-api-tx.ts
  typescript-api/src/dancelight/interfaces/lookup.ts
  typescript-api/src/dancelight/interfaces/types-lookup.ts
Labels: B7-runtimenoteworthy, breaking, D5-nicetohaveaudit⚠️

#802 Changes in dancelight to enable solochain message relay
  Cargo.lock
  Cargo.toml
  chains/orchestrator-relays/runtime/dancelight/Cargo.toml
  chains/orchestrator-relays/runtime/dancelight/src/bridge_to_ethereum_config.rs
  chains/orchestrator-relays/runtime/dancelight/src/lib.rs
  pallets/oubound-message-commitment-recorder/Cargo.toml
  pallets/oubound-message-commitment-recorder/src/lib.rs
  test/scripts/bridge-build-artifacts.sh
  test/scripts/bridge/assets/beefy-relay.json
  test/scripts/bridge/assets/substrate-relay.json
  test/scripts/bridge/build-relayer.sh
  test/scripts/bridge/build-snowbridge-contracts.sh
  test/scripts/bridge/build-symbiotic-contracts.sh
  test/scripts/bridge/checkout-tanssi-symbiotic.sh
  test/scripts/bridge/deploy-ethereum-contracts.sh
  test/scripts/bridge/generate-beefy-checkpoint.sh
  test/scripts/bridge/generate-eth-info.sh
  test/scripts/bridge/set-env.sh
  test/scripts/bridge/setup-relayer.sh
  test/scripts/bridge/start-relayer.sh
  test/suites/zombie_tanssi_relay_eth_bridge/test_zombie_tanssi_relay_eth_bridge.ts
  typescript-api/src/dancelight/interfaces/augment-api-events.ts
  typescript-api/src/dancelight/interfaces/augment-api-query.ts
  typescript-api/src/dancelight/interfaces/lookup.ts
  typescript-api/src/dancelight/interfaces/registry.ts
  typescript-api/src/dancelight/interfaces/types-lookup.ts
Labels: B7-runtimenoteworthy, breaking, D3-trivial

#793 Starlight <> Ethereum: Slashes mapping
  Cargo.lock
  chains/orchestrator-relays/runtime/dancelight/src/lib.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/common/mod.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/slashes.rs
  chains/orchestrator-relays/runtime/dancelight/src/weights/pallet_external_validator_slashes.rs
  pallets/external-validator-slashes/Cargo.toml
  pallets/external-validator-slashes/src/benchmarking.rs
  pallets/external-validator-slashes/src/lib.rs
  pallets/external-validator-slashes/src/mock.rs
  pallets/external-validator-slashes/src/tests.rs
  pallets/external-validator-slashes/src/weights.rs
  primitives/bridge/src/custom_do_process_message.rs
  primitives/bridge/src/lib.rs
  test/suites/dev-tanssi-relay/slashes/test_slashes_are_acummulated_across_blocks.ts
  test/suites/dev-tanssi-relay/slashes/test_slashes_are_acummulated_across_eras.ts
  test/suites/dev-tanssi-relay/slashes/test_slashes_are_confirmed_after_defer_period.ts
  test/util/constants.ts
  typescript-api/src/dancelight/interfaces/augment-api-consts.ts
  typescript-api/src/dancelight/interfaces/augment-api-events.ts
  typescript-api/src/dancelight/interfaces/augment-api-query.ts
  typescript-api/src/dancelight/interfaces/lookup.ts
  typescript-api/src/dancelight/interfaces/types-lookup.ts
Labels: a0-pleasereview, B7-runtimenoteworthy, breaking, D9-needsaudit👮

#814 fix bridge e2e test
  test/suites/zombie_tanssi_relay_eth_bridge/test_zombie_tanssi_relay_eth_bridge.ts
Labels: B0-silent, D2-notlive, not-breaking

#816 add timestamp to each slash
  chains/orchestrator-relays/runtime/dancelight/src/tests/slashes.rs
  pallets/external-validator-slashes/src/lib.rs
  pallets/external-validator-slashes/src/tests.rs
  primitives/bridge/src/lib.rs
  typescript-api/src/dancelight/interfaces/lookup.ts
  typescript-api/src/dancelight/interfaces/registry.ts
  typescript-api/src/dancelight/interfaces/types-lookup.ts
Labels: B3-apinoteworthy, B7-runtimenoteworthy, breaking, D3-trivial

#808 Mint inflation due to external validators rewards to Ethereum Sovereign Account
  Cargo.lock
  chains/orchestrator-relays/runtime/dancelight/src/genesis_config_presets.rs
  chains/orchestrator-relays/runtime/dancelight/src/lib.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/external_validators_tests.rs
  chains/orchestrator-relays/runtime/dancelight/src/xcm_config.rs
  pallets/external-validators-rewards/Cargo.toml
  pallets/external-validators-rewards/src/lib.rs
  pallets/external-validators-rewards/src/mock.rs
  pallets/external-validators-rewards/src/tests.rs
  primitives/bridge/Cargo.toml
  primitives/bridge/src/lib.rs
  test/scripts/bridge/assets/substrate-relay.json
  test/suites/dev-tanssi-relay/balances/test_balances.ts
  test/suites/dev-tanssi-relay/external-validators-rewards/test_external_validator_rewards.ts
Labels: a0-pleasereview, B7-runtimenoteworthy, D9-needsaudit👮, not-breaking

#818 change build binaries to tanssi-relesae
  .github/workflows/prepare-binary.yml
  .github/workflows/prepare-tanssi-relay-binary.yml
  .github/workflows/publish-binary-tannsi-relay.yml
  .github/workflows/publish-binary.yml
Labels: a0-pleasereview, B0-silent, D3-trivial, not-breaking

#820 Add missing workspace lints = true
  client/orchestrator-chain-rpc-interface/Cargo.toml
  pallets/xcm-core-buyer/Cargo.toml
Labels: B0-silent, D2-notlive, not-breaking

#822 fix eth encoding with respect to encoding slashes vector
  primitives/bridge/src/lib.rs
  primitives/bridge/src/tests.rs
Labels: B7-runtimenoteworthy, breaking, D5-nicetohaveaudit⚠️

#806 Test: Validators matching external validators smoke test
  test/suites/smoke-test-dancelight/test-validators-match-external-validators.ts
Labels: B0-silent, D2-notlive, not-breaking

#821 Fix upload action and missing protoc
  .github/workflows/publish-binary.yml
Labels: B0-silent, D2-notlive, not-breaking

#823 Add dependabot config to automatically check the version of the actions once a month
  .github/dependabot.yml
Labels: B0-silent, D2-notlive, not-breaking

#826 Send token id with rewards
  Cargo.lock
  chains/orchestrator-relays/node/tanssi-relay-service/Cargo.toml
  chains/orchestrator-relays/runtime/dancelight/Cargo.toml
  chains/orchestrator-relays/runtime/dancelight/constants/Cargo.toml
  chains/orchestrator-relays/runtime/dancelight/constants/src/lib.rs
  chains/orchestrator-relays/runtime/dancelight/src/bridge_to_ethereum_config.rs
  chains/orchestrator-relays/runtime/dancelight/src/lib.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/external_validators_tests.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/slashes.rs
  chains/orchestrator-relays/runtime/dancelight/src/weights/pallet_external_validators_rewards.rs
  chains/orchestrator-relays/runtime/dancelight/src/weights/snowbridge_pallet_system.rs
  chains/orchestrator-relays/runtime/dancelight/src/xcm_config.rs
  pallets/external-validators-rewards/Cargo.toml
  pallets/external-validators-rewards/src/benchmarking.rs
  pallets/external-validators-rewards/src/lib.rs
  pallets/external-validators-rewards/src/mock.rs
  pallets/external-validators-rewards/src/tests.rs
  primitives/bridge/Cargo.toml
  primitives/bridge/src/benchmarks.rs
  primitives/bridge/src/lib.rs
  primitives/bridge/src/tests.rs
  test/suites/dev-tanssi-relay/external-validators-rewards/test_external_validator_rewards.ts
  typescript-api/src/dancelight/interfaces/lookup.ts
  typescript-api/src/dancelight/interfaces/types-lookup.ts
Labels: B7-runtimenoteworthy, breaking, D5-nicetohaveaudit⚠️

#834 Add message id to slash and reward message events
  chains/orchestrator-relays/runtime/dancelight/src/tests/common/mod.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/external_validators_tests.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/slashes.rs
  pallets/external-validator-slashes/src/lib.rs
  pallets/external-validator-slashes/src/tests.rs
  pallets/external-validators-rewards/src/lib.rs
  pallets/external-validators-rewards/src/tests.rs
  primitives/bridge/src/lib.rs
  typescript-api/src/dancelight/interfaces/augment-api-events.ts
  typescript-api/src/dancelight/interfaces/lookup.ts
  typescript-api/src/dancelight/interfaces/types-lookup.ts
Labels: B0-silent, D3-trivial, not-breaking

#827 Update polkadot js to 15.4.1
  pnpm-lock.yaml
  test/package.json
  typescript-api/package.json
  typescript-api/src/dancebox/interfaces/augment-types.ts
  typescript-api/src/dancelight/interfaces/augment-types.ts
  typescript-api/src/flashbox/interfaces/augment-types.ts
Labels: B0-silent, D2-notlive, not-breaking

#837 be more hardcore on the checks on cores
  chains/orchestrator-relays/runtime/dancelight/src/lib.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/core_scheduling_tests.rs
Labels: B7-runtimenoteworthy, breaking, D5-nicetohaveaudit⚠️

#838 Slash + rewards e2e test version 1
  primitives/bridge/src/custom_do_process_message.rs
  test/scripts/bridge/build-symbiotic-contracts.sh
  test/scripts/bridge/set-env.sh
  test/scripts/bridge/setup-relayer.sh
  test/scripts/bridge/start-relayer.sh
  test/suites/zombie_tanssi_relay_eth_bridge/test_zombie_tanssi_relay_eth_bridge.ts
Labels: B0-silent, D2-notlive, not-breaking

#836 External Index handling as sent by external chain
  Cargo.lock
  chains/orchestrator-paras/runtime/common/Cargo.toml
  chains/orchestrator-paras/runtime/common/src/migrations.rs
  chains/orchestrator-relays/runtime/dancelight/src/lib.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/common/xcm/bridge_to_eth.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/external_validators_tests.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/inbound_queue_tests/integration_tests.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/inbound_queue_tests/message_processor_tests.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/integration_test.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/migrations_test.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/slashes.rs
  pallets/external-validator-slashes/src/benchmarking.rs
  pallets/external-validator-slashes/src/lib.rs
  pallets/external-validator-slashes/src/mock.rs
  pallets/external-validator-slashes/src/tests.rs
  pallets/external-validators-rewards/src/lib.rs
  pallets/external-validators-rewards/src/mock.rs
  pallets/external-validators-rewards/src/tests.rs
  pallets/external-validators/src/lib.rs
  pallets/external-validators/src/mock.rs
  pallets/external-validators/src/tests.rs
  primitives/bridge/src/lib.rs
  primitives/bridge/src/symbiotic_message_processor.rs
  primitives/bridge/src/tests.rs
  primitives/traits/src/lib.rs
  test/configs/zombie_tanssi_relay_eth_bridge.json
  test/scripts/bridge/build-relayer.sh
  test/scripts/bridge/set-env.sh
  test/suites/dev-tanssi-relay/external-validators-rewards/test-rewards-runtime-api.ts
  test/suites/dev-tanssi-relay/external-validators-rewards/test_external_validator_reward_candidates.ts
  test/suites/dev-tanssi-relay/external-validators-rewards/test_external_validator_rewards.ts
  test/suites/dev-tanssi-relay/proxy/test-proxy-validator-management.ts
  test/suites/dev-tanssi-relay/slashes/test_slashes_are_acummulated_across_blocks.ts
  test/suites/dev-tanssi-relay/slashes/test_slashes_are_acummulated_across_eras.ts
  test/suites/zombie_tanssi_relay_eth_bridge/test_zombie_tanssi_relay_eth_bridge.ts
  typescript-api/src/dancelight/interfaces/augment-api-query.ts
  typescript-api/src/dancelight/interfaces/augment-api-tx.ts
  typescript-api/src/dancelight/interfaces/lookup.ts
  typescript-api/src/dancelight/interfaces/types-lookup.ts
Labels: B7-runtimenoteworthy, breaking, D5-nicetohaveaudit⚠️
