Repository moondance-labs/tanssi, pull requests merged in 2025-02, with the labels that each got.

#841 introduce merge queue changes
  .github/workflow-templates/bridge-e2e/action.yml
  .github/workflows/coverage.yml
  .github/workflows/e2e-test-bridge.yml
  .github/workflows/release.yml
Labels: B0-silent, D3-trivial, not-breaking

#842 adding result collector job to the CI for merge queue matrices
  .github/workflows/release.yml
Labels: B0-silent, D3-trivial, not-breaking

#840 Refactor: root pnpm workspaces
  package.json
  pnpm-lock.yaml
  test/package.json
  typescript-api/package.json
Labels: B0-silent, D2-notlive

#843 Fix benchmark script for both benchmark modes
  tools/benchmarking.sh
Labels: B0-silent, D3-trivial, not-breaking

#845 Fix BABE smoke tests
  test/suites/smoke-test-dancelight/test-babe.ts
Labels: B0-silent, D2-notlive, not-breaking

#851 Fix runtime-publishing job & update upload action to v4
  .github/workflows/docker-runtime-draft.yml
  .github/workflows/prepare-binary.yml
  .github/workflows/prepare-tanssi-relay-binary.yml
  .github/workflows/publish-binary-tannsi-relay.yml
  .github/workflows/publish-runtime-chevdor.yml
  .github/workflows/publish-runtime.yml
  scripts/build-runtime-srtool.sh
  tools/github/generate-runtimes-body.ts
Labels: B0-silent, D3-trivial, not-breaking

#848 fix benchmarking tool
  benchmarking/frame-weight-runtime-template.hbs
  tools/benchmarking.sh
Labels: B0-silent, D3-trivial, not-breaking

#855 install always protoc in tanssi-release
  .github/workflows/prepare-binary.yml
  .github/workflows/prepare-tanssi-relay-binary.yml
  .github/workflows/publish-binary-tannsi-relay.yml
Labels: B0-silent, D3-trivial, not-breaking

#852 fix: 😅 Don't be hassled by download confirmations
  .prettierignore
  pnpm-lock.yaml
  test/moonwall.config.json
  test/package.json
  test/polkadotReleaseMapping.json
  test/scripts/download-polkadot.sh
  test/scripts/downloadPolkadot.ts
Labels: B0-silent, D2-notlive

#856 Disable automatic rebase in dependabot.yml
  .github/dependabot.yml
Labels: B0-silent, D3-trivial, not-breaking

#854 Add balance transfer to zombie upgrade tests
  test/suites/zombie_dancebox_upgrade/test_zombie_dancebox_upgrade.ts
  test/suites/zombie_dancelight_upgrade/test_zombie_dancelight_upgrade.ts
  test/suites/zombie_simple_template_upgrade/test_zombie_simple_template_upgrade.ts
Labels: B0-silent, D3-trivial, not-breaking

#865 Remove default WeightInfo if possible
  chains/orchestrator-relays/runtime/dancelight/src/lib.rs
  chains/orchestrator-relays/runtime/dancelight/src/weights/mod.rs
  chains/orchestrator-relays/runtime/dancelight/src/weights/pallet_beefy_mmr.rs
  chains/orchestrator-relays/runtime/dancelight/src/weights/pallet_configuration.rs
  chains/orchestrator-relays/runtime/dancelight/src/weights/pallet_mmr.rs
  chains/orchestrator-relays/runtime/dancelight/src/weights/pallet_multiblock_migrations.rs
Labels: a0-pleasereview, B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#853 Bump node and runtime versions to 0.12.0 and 1200
  Cargo.lock
  chains/container-chains/nodes/frontier/Cargo.toml
  chains/container-chains/nodes/simple/Cargo.toml
  chains/container-chains/runtime-templates/frontier/src/lib.rs
  chains/container-chains/runtime-templates/simple/src/lib.rs
  chains/orchestrator-paras/node/Cargo.toml
  chains/orchestrator-paras/runtime/dancebox/src/lib.rs
  chains/orchestrator-paras/runtime/flashbox/src/lib.rs
  chains/orchestrator-relays/node/tanssi-relay-service/Cargo.toml
  chains/orchestrator-relays/node/tanssi-relay/Cargo.toml
  chains/orchestrator-relays/runtime/dancelight/src/lib.rs
Labels: B0-silent, D3-trivial, not-breaking

#868 Fix type in BABE smoke test
  test/suites/smoke-test-dancelight/test-babe.ts
Labels: B0-silent, D3-trivial, not-breaking

#871 fix tests related to e2e
  test/suites/zombie_tanssi_relay_eth_bridge/test_zombie_tanssi_relay_eth_bridge.ts
Labels: B0-silent, D3-trivial, not-breaking

#866 Add new release instructions and fix wrong job
  .github/workflows/docker-runtime-draft.yml
  .github/workflows/publish-binary-tanssi-solochain.yml
  .github/workflows/publish-docker-runtime-tanssi-solochain.yml
  .github/workflows/publish-docker-tanssi-solochain.yml
  tools/github/print-client-release-issue.ts
  tools/github/print-runtime-release-issue.ts
Labels: B0-silent, D3-trivial, not-breaking

#858 Add pallet-multiblock-migrations to all runtimes
  Cargo.lock
  chains/container-chains/runtime-templates/frontier/Cargo.toml
  chains/container-chains/runtime-templates/frontier/src/lib.rs
  chains/container-chains/runtime-templates/frontier/src/weights/mod.rs
  chains/container-chains/runtime-templates/frontier/src/weights/pallet_multiblock_migrations.rs
  chains/container-chains/runtime-templates/simple/Cargo.toml
  chains/container-chains/runtime-templates/simple/src/lib.rs
  chains/container-chains/runtime-templates/simple/src/weights/mod.rs
  chains/container-chains/runtime-templates/simple/src/weights/pallet_multiblock_migrations.rs
  chains/orchestrator-paras/runtime/dancebox/Cargo.toml
  chains/orchestrator-paras/runtime/dancebox/src/lib.rs
  chains/orchestrator-paras/runtime/dancebox/src/weights/mod.rs
  chains/orchestrator-paras/runtime/dancebox/src/weights/pallet_multiblock_migrations.rs
  chains/orchestrator-paras/runtime/flashbox/Cargo.toml
  chains/orchestrator-paras/runtime/flashbox/src/lib.rs
  chains/orchestrator-paras/runtime/flashbox/src/weights/mod.rs
  chains/orchestrator-paras/runtime/flashbox/src/weights/pallet_multiblock_migrations.rs
  chains/orchestrator-relays/runtime/dancelight/src/lib.rs
  docs/benchmarking.md
  test/suites/zombie_tanssi_parathreads/test_zombie_tanssi_parathreads.ts
  test/util/block.ts
  tools/dev-benchmark-pallet.sh
  typescript-api/src/dancebox/interfaces/augment-api-consts.ts
  typescript-api/src/dancebox/interfaces/augment-api-errors.ts
  typescript-api/src/dancebox/interfaces/augment-api-events.ts
  typescript-api/src/dancebox/interfaces/augment-api-query.ts
  typescript-api/src/dancebox/interfaces/augment-api-tx.ts
  typescript-api/src/dancebox/interfaces/lookup.ts
  typescript-api/src/dancebox/interfaces/registry.ts
  typescript-api/src/dancebox/interfaces/types-lookup.ts
  typescript-api/src/flashbox/interfaces/augment-api-consts.ts
  typescript-api/src/flashbox/interfaces/augment-api-errors.ts
  typescript-api/src/flashbox/interfaces/augment-api-events.ts
  typescript-api/src/flashbox/interfaces/augment-api-query.ts
  typescript-api/src/flashbox/interfaces/augment-api-tx.ts
  typescript-api/src/flashbox/interfaces/lookup.ts
  typescript-api/src/flashbox/interfaces/registry.ts
  typescript-api/src/flashbox/interfaces/types-lookup.ts
Labels: B7-runtimenoteworthy, breaking, D5-nicetohaveaudit⚠️

#869 ci: :green_heart: Reduce self-hosted runner usage
  .github/workflow-templates/bridge-e2e/action.yml
  .github/workflows/release.yml
  .gitignore
Labels: B0-silent, D2-notlive

#873 first test workflow merge when ready
  .github/workflows/cancel.yml
  .github/workflows/merge-when-ready.yml
  .github/workflows/release.yml
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#876 CI cleanup
  .github/workflow-templates/cargo-build/action.yml
  .github/workflows/coverage.yml
  .github/workflows/e2e-test-bridge.yml
  .github/workflows/merge-when-ready.yml
  .github/workflows/release.yml
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#872 Fix tanssi-relay and container collator version to match tanssi-node
  Cargo.lock
  chains/container-chains/nodes/frontier/src/command.rs
  chains/container-chains/nodes/simple/src/command.rs
  chains/orchestrator-paras/node/src/command.rs
  chains/orchestrator-relays/client/cli/Cargo.toml
  chains/orchestrator-relays/client/cli/src/command.rs
  client/service-container-chain/Cargo.toml
  scripts/bump-runtime-versions.sh
Labels: A8-mergeoncegreen, B5-clientnoteworthy, D3-trivial, not-breaking

#857 Emitting event when setting external validators
  pallets/external-validators/src/lib.rs
  pallets/external-validators/src/mock.rs
  pallets/external-validators/src/tests.rs
  typescript-api/src/dancelight/interfaces/augment-api-events.ts
  typescript-api/src/dancelight/interfaces/lookup.ts
  typescript-api/src/dancelight/interfaces/types-lookup.ts
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#875 Add first bench tests
  .github/workflows/merge-when-ready.yml
  chains/orchestrator-relays/runtime/dancelight/src/bridge_to_ethereum_config.rs
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#835 `EthereumTokenTransfers` pallet
  Cargo.lock
  Cargo.toml
  chains/orchestrator-relays/runtime/dancelight/Cargo.toml
  chains/orchestrator-relays/runtime/dancelight/src/bridge_to_ethereum_config.rs
  chains/orchestrator-relays/runtime/dancelight/src/lib.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/ethereum_token_transfers.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/external_validators_tests.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/mod.rs
  chains/orchestrator-relays/runtime/dancelight/src/weights/mod.rs
  chains/orchestrator-relays/runtime/dancelight/src/weights/pallet_ethereum_token_transfers.rs
  pallets/ethereum-token-transfers/Cargo.toml
  pallets/ethereum-token-transfers/src/benchmarking.rs
  pallets/ethereum-token-transfers/src/lib.rs
  pallets/ethereum-token-transfers/src/mock.rs
  pallets/ethereum-token-transfers/src/tests.rs
  pallets/ethereum-token-transfers/src/weights.rs
  pallets/external-validators-rewards/src/benchmarking.rs
  pallets/external-validators-rewards/src/lib.rs
  primitives/bridge/Cargo.toml
  primitives/bridge/src/benchmarks.rs
  primitives/bridge/src/lib.rs
  test/helpers/events.ts
  test/helpers/index.ts
  test/suites/dev-tanssi-relay/ethereum-token-transfers/test_set_token_transfer_channel.ts
  test/suites/dev-tanssi-relay/ethereum-token-transfers/test_transfer_native_token.ts
  test/suites/dev-tanssi-relay/slashes/test_slashes_eth.ts
  typescript-api/src/dancelight/interfaces/augment-api-errors.ts
  typescript-api/src/dancelight/interfaces/augment-api-events.ts
  typescript-api/src/dancelight/interfaces/augment-api-query.ts
  typescript-api/src/dancelight/interfaces/augment-api-tx.ts
  typescript-api/src/dancelight/interfaces/lookup.ts
  typescript-api/src/dancelight/interfaces/registry.ts
  typescript-api/src/dancelight/interfaces/types-lookup.ts
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, breaking, D9-needsaudit👮

#867 refactor: 🔧 Update dancelight smoketests
  test/package.json
  test/suites/smoke-test-dancelight/test-authority-consistency-assignation.ts
  test/suites/smoke-test-dancelight/test-babe.ts
  test/suites/smoke-test-dancelight/test-beefy-mmr-digests.ts
  test/suites/smoke-test-dancelight/test-configuration-consistency.ts
  test/suites/smoke-test-dancelight/test-external-validators-rewards.ts
  test/suites/smoke-test-dancelight/test-inflation-rewards.ts
  test/suites/smoke-test-dancelight/test-para-inclusion.ts
  test/suites/smoke-test-dancelight/test-validators-match-external-validators.ts
Labels: A8-mergeoncegreen, B0-silent, D2-notlive

#877 test: 🧪 Added Session change test to Chopsticks
  test/moonwall.config.json
  test/suites/rt-upgrade-chopsticks-orchestrator/test-upgrade-chain.ts
Labels: A8-mergeoncegreen, B0-silent, D2-notlive

#885 Minor doc update and Node version compatibility
  .nvmrc
  README.md
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#887 Fix gsed dep in mac to run e2e tests
  test/scripts/bridge/set-env.sh
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#891 fix smoke test regarding external validators rewards
  test/suites/smoke-test-dancelight/test-external-validators-rewards.ts
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#894 Update to electra consensus
  Cargo.lock
  chains/orchestrator-relays/runtime/dancelight/src/bridge_to_ethereum_config.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/ethereum_client.rs
  test/scripts/bridge/assets/beacon-relay.json
  test/scripts/bridge/assets/execution-relay.json
  test/scripts/bridge/assets/genesis.json
  test/scripts/bridge/set-env.sh
  test/scripts/bridge/setup-relayer.sh
  test/scripts/bridge/start-ethereum-node.sh
  test/scripts/download-ethereum-client-test-files.sh
  test/suites/dev-tanssi-relay/eth-client/test-eth-ciient-submit-update-same-period.ts
  test/suites/dev-tanssi-relay/eth-client/test-eth-client-submit-update-cannot-be-done-without-injecting-new-committee.ts
  test/suites/dev-tanssi-relay/ethereum-token-transfers/test_transfer_native_token.ts
  typescript-api/src/dancelight/interfaces/lookup.ts
  typescript-api/src/dancelight/interfaces/types-lookup.ts
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, breaking, D5-nicetohaveaudit⚠️
