Repository moondance-labs/tanssi, pull requests merged in 2025-06, with the labels that each got.

#1069 fix publish docker
  .github/workflows/publish-docker.yml
Labels: a0-pleasereview, A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1055 Rewrite host_config_at_session in functional style, and avoid one read
  chains/orchestrator-relays/runtime/dancelight/src/lib.rs
  chains/orchestrator-relays/runtime/starlight/src/lib.rs
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1067 Treasury smoke test fix
  test/suites/smoke-test-common-all/test-fee-treasury.ts
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1073 Treasury smoke test fix - filter events by extrinsic index
  test/suites/smoke-test-common-all/test-fee-treasury.ts
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1072 Fix docker publish runtime draft
  .github/workflows/docker-runtime-draft.yml
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1077 Adds Icon
  media/tanssi_icon.png
Labels: a2-insubstantial, A8-mergeoncegreen, B0-silent, C1-low, D3-trivial

#1046 [MD-993] Deduplicate CI jobs
  .github/workflow-templates/cargo-build/action.yml
  .github/workflow-templates/copy-parachain-node-binaries/action.yml
  .github/workflow-templates/copy-relaychain-node-binaries/action.yml
  .github/workflow-templates/make-binaries-executable/action.yml
  .github/workflow-templates/publish-node-docker/action.yml
  .github/workflow-templates/publish-runtime-docker/action.yml
  .github/workflow-templates/typescript-create-api-interfaces/action.yml
  .github/workflow-templates/typescript-tests-moonwall/action.yml
  .github/workflows/cmd.yml
  .github/workflows/docker-runtime-draft.yml
  .github/workflows/merge-when-ready.yml
  .github/workflows/prepare-binary.yml
  .github/workflows/prepare-tanssi-relay-binary.yml
  .github/workflows/publish-binary-tanssi-solochain.yml
  .github/workflows/publish-binary.yml
  .github/workflows/publish-docker-runtime-containers.yml
  .github/workflows/publish-docker-runtime-tanssi-solochain.yml
  .github/workflows/publish-docker-runtime-tanssi.yml
  .github/workflows/publish-docker-tanssi-solochain.yml
  .github/workflows/publish-docker.yml
  .github/workflows/release.yml
  .github/workflows/run-zombienet-tests.yml
  .github/workflows/upgrade-typescript-api.yml
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#899 feat: inactivity tracking pallet (chain inactivity tracking)
  Cargo.lock
  Cargo.toml
  chains/orchestrator-paras/runtime/dancebox/Cargo.toml
  chains/orchestrator-paras/runtime/dancebox/src/lib.rs
  chains/orchestrator-paras/runtime/dancebox/src/tests/inactivity_tracking.rs
  chains/orchestrator-relays/node/tanssi-relay-service/Cargo.toml
  chains/orchestrator-relays/node/tanssi-relay-service/src/dev_service.rs
  chains/orchestrator-relays/runtime/dancelight/Cargo.toml
  chains/orchestrator-relays/runtime/dancelight/src/lib.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/inactivity_tracking.rs
  pallets/inactivity-tracking/src/lib.rs
  pallets/inactivity-tracking/src/mock.rs
  pallets/inactivity-tracking/src/tests.rs
  primitives/parathread-filter-common/Cargo.toml
  primitives/parathread-filter-common/src/lib.rs
  primitives/traits/src/lib.rs
  test/suites/dev-tanssi-relay/inactivity-tracking/test-inactivity-tracking.ts
  test/suites/dev-tanssi/inactivity-tracking/test-inactivity-tracking.ts
  typescript-api/src/dancebox/interfaces/augment-api-consts.ts
  typescript-api/src/dancebox/interfaces/augment-api-errors.ts
  typescript-api/src/dancebox/interfaces/augment-api-query.ts
  typescript-api/src/dancebox/interfaces/lookup.ts
  typescript-api/src/dancebox/interfaces/types-lookup.ts
  typescript-api/src/dancelight/interfaces/augment-api-consts.ts
  typescript-api/src/dancelight/interfaces/augment-api-errors.ts
  typescript-api/src/dancelight/interfaces/augment-api-query.ts
  typescript-api/src/dancelight/interfaces/lookup.ts
  typescript-api/src/dancelight/interfaces/types-lookup.ts
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, breaking, D5-nicetohaveaudit⚠️

#1090 Fix for forEach issue
  pnpm-lock.yaml
  test/package.json
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1091 Add minimal smoke test to CI
  .github/workflows/merge-when-ready.yml
Labels: A8-mergeoncegreen, B0-silent, D2-notlive, not-breaking

#1092 point to latest potential mastter in tanssi-symb
  test/scripts/bridge/set-env.sh
Labels: A8-mergeoncegreen, B0-silent, breaking, D3-trivial

#1075 Simplify add_invulnerable weight calculation
  pallets/external-validators/src/lib.rs
  pallets/invulnerables/src/lib.rs
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1094 Remove passed migrations
  chains/container-chains/runtime-templates/frontier/src/migrations.rs
  chains/container-chains/runtime-templates/simple/src/migrations.rs
  chains/orchestrator-paras/runtime/common/src/migrations.rs
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1052 test: inactivity tracking smoke test
  test/suites/smoke-test-dancebox/test-inactivity-tracking.ts
  test/suites/smoke-test-dancelight/test-inactivity-tracking.ts
  test/utils/block.ts
Labels: A8-mergeoncegreen, B0-silent, D2-notlive, not-breaking

#1102 Fixes for smoke tests
  test/suites/smoke-test-common-all/test-consistency-services-payment.ts
  test/suites/smoke-test-common-all/test-data-preservers.ts
  test/suites/smoke-test-common-parachain/test-configuration-consistency.ts
  test/suites/smoke-test-common-solo/test-configuration-consistency.ts
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1056 Fix pallet_collator_assignment randomness in relay chain mode
  chains/orchestrator-paras/runtime/dancebox/src/lib.rs
  chains/orchestrator-paras/runtime/dancebox/src/weights/pallet_collator_assignment.rs
  chains/orchestrator-paras/runtime/flashbox/src/lib.rs
  chains/orchestrator-paras/runtime/flashbox/src/weights/pallet_collator_assignment.rs
  chains/orchestrator-relays/runtime/dancelight/src/lib.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/collator_assignment_tests.rs
  chains/orchestrator-relays/runtime/dancelight/src/weights/pallet_collator_assignment.rs
  chains/orchestrator-relays/runtime/starlight/src/lib.rs
  chains/orchestrator-relays/runtime/starlight/src/tests/collator_assignment_tests.rs
  chains/orchestrator-relays/runtime/starlight/src/weights/pallet_collator_assignment.rs
  pallets/collator-assignment/src/benchmarking.rs
  pallets/collator-assignment/src/lib.rs
  pallets/collator-assignment/src/mock.rs
  pallets/collator-assignment/src/weights.rs
  test/suites/dev-tanssi-relay/collator-assignment/test-collator-assignment.ts
  test/suites/smoke-test-common-solo/test-randomness-consistency.ts
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, breaking, D9-needsaudit👮

#1109 fix test ethereum token trannsfer
  test/suites/smoke-test-common-solo/test-ethereum-token-transfers.ts
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking
