Repository moondance-labs/tanssi, pull requests merged in 2025-07, with the labels that each got.

#1111 Cleanup rustfmt and iforgor config
  .rustfmt.toml
  tools/iforgor/tanssi.toml
Labels: A8-mergeoncegreen, B0-silent, D2-notlive, not-breaking

#1121 Add testing support for sending WETH to Tanssi
  test/suites/dev-tanssi-relay/ethereum-token-transfers/test_receive_erc20_from_eth.ts
  test/suites/dev-tanssi-relay/ethereum-token-transfers/test_receive_eth_native_token_from_eth.ts
  test/suites/dev-tanssi-relay/foreign-assets/test-foreign-assets.ts
  test/suites/zombie_tanssi_relay_eth_bridge/test_zombie_tanssi_relay_eth_bridge.ts
  test/utils/constants.ts
Labels: A8-mergeoncegreen, B0-silent, D2-notlive, not-breaking

#1131 modify a few things related to the machines in which they run
  .github/workflows/coverage.yml
  .github/workflows/publish-binary-tanssi-solochain.yml
  .github/workflows/publish-binary.yml
  .github/workflows/publish-runtime.yml
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1137 Add SECURITY.md via upload
  SECURITY.md
Labels: documentation, A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1135 Ability to run publish-binary with a docker-uploaded image
  .github/workflows/publish-binary-from-docker.yml
  test/scripts/download-latest-rt-binaries.sh
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1132 Added URL to the files for easier navigation
  tools/show-me-the-weights.py
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1119 test: smoke tests for era changes
  test/moonwall.config.json
  test/suites/smoke-test-common-solo/test-era-changes.ts
  test/suites/smoke-test-dancelight/test-inactivity-tracking.ts
Labels: A8-mergeoncegreen, B0-silent, D2-notlive, not-breaking

#1143 fix: add era start session offset when checking for correct era changes
  test/suites/smoke-test-common-solo/test-era-changes.ts
Labels: A8-mergeoncegreen, B0-silent, D2-notlive, not-breaking

#1054 Send tokens back to Ethereum (dancelight)
  Cargo.lock
  chains/orchestrator-relays/runtime/dancelight/src/tests/ethereum_token_transfers.rs
  chains/orchestrator-relays/runtime/dancelight/src/xcm_config.rs
  primitives/bridge/Cargo.toml
  primitives/bridge/src/lib.rs
  primitives/bridge/src/snowbridge_outbound_token_transfer.rs
  primitives/bridge/src/tests.rs
  test/suites/dev-tanssi-relay/ethereum-token-transfers/test-send-erc20-back-to-eth.ts
Labels: a0-pleasereview, A8-mergeoncegreen, B7-runtimenoteworthy, breaking, D9-needsaudit👮

#1153 Fixed docker runtime workflow
  .github/workflows/docker-runtime-draft.yml
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1157 Fixed branch name for coverage CI
  .github/workflows/coverage.yml
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1106 Refactor common types within Dancelight and Starlight
  Cargo.lock
  chains/orchestrator-paras/runtime/dancebox/src/lib.rs
  chains/orchestrator-relays/runtime/dancelight/Cargo.toml
  chains/orchestrator-relays/runtime/dancelight/src/bridge_to_ethereum_config.rs
  chains/orchestrator-relays/runtime/dancelight/src/lib.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/collator_assignment_tests.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/ethereum_token_transfers.rs
  chains/orchestrator-relays/runtime/starlight/Cargo.toml
  chains/orchestrator-relays/runtime/starlight/src/bridge_to_ethereum_config.rs
  chains/orchestrator-relays/runtime/starlight/src/lib.rs
  chains/orchestrator-relays/runtime/starlight/src/tests/ethereum_token_transfers.rs
  chains/runtime-common/Cargo.toml
  chains/runtime-common/src/lib.rs
  chains/runtime-common/src/migrations.rs
  chains/runtime-common/src/relay.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, D3-trivial, not-breaking

#1154 Network Release minor fixes
  .github/workflows/client-release-issue.yml
  .github/workflows/docker-runtime-draft.yml
  .github/workflows/publish-runtime.yml
  tools/github/print-client-release-issue.ts
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1169 [MD-1197] Improve smoke ETH token transfer for ethereumInboundQueue
  test/suites/smoke-test-common-solo/test-ethereum-token-transfers.ts
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1166 Script that cancels other PR-s besides the specific one
  scripts/cancel_all_but.sh
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1172 Remove unused lastest_rt from set-tags job
  .github/workflows/release.yml
Labels: A8-mergeoncegreen, B0-silent, D2-notlive, not-breaking

#1177 tanssi symbiotic final commits
  test/scripts/bridge/set-env.sh
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1182 Make inbound event more reliable in e2e tests
  test/suites/zombie_tanssi_relay_eth_bridge/test_zombie_tanssi_relay_eth_bridge.ts
Labels: A8-mergeoncegreen, B0-silent, D2-notlive, not-breaking

#1171 Add zombienet suite to test finalization issues
  test/configs/zombie_tanssi_relay_finalization_recovery.json
  test/moonwall.config.json
  test/suites/zombie_tanssi_relay_finalization_recovery/test_zombie_tanssi_relay_finalization_recovery.ts
  test/utils/zombie.ts
Labels: A8-mergeoncegreen, B0-silent, D2-notlive, not-breaking

#1184 Fix era inflation smoke test for starlight
  test/suites/smoke-test-common-solo/test-external-validators-rewards.ts
  test/utils/constants.ts
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1178 Remove unused cli arg tanssi_experimental_max_pov_percentage
  chains/orchestrator-paras/node/src/cli.rs
  client/service-container-chain/src/cli.rs
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1187 Fix for era changes smoke test
  test/suites/smoke-test-common-solo/test-era-changes.ts
  test/utils/block.ts
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1186 enable register extrinsics
  chains/orchestrator-relays/runtime/starlight/src/lib.rs
  chains/orchestrator-relays/runtime/starlight/src/tests/relay_registrar.rs
  pallets/registrar/src/benchmarks.rs
  pallets/registrar/src/lib.rs
  test/helpers/starlightVersions.ts
  test/suites/dev-tanssi-relay/collator-assignment/test-configurable-priority.ts
  test/suites/dev-tanssi-relay/proxy/test-proxy-registrar.ts
  test/suites/dev-tanssi-relay/registrar/test_registrars.ts
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, breaking, D5-nicetohaveaudit⚠️

#1189 Fix build caching for the coverage case
  .github/workflow-templates/cargo-build/action.yml
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1192 update api to 1500
  tools/github/print-runtime-release-issue.ts
  typescript-api/package.json
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1108 Enable zombie upgrade tests in manual CI run
  .github/workflows/run-zombienet-tests.yml
Labels: A8-mergeoncegreen, B0-silent, D2-notlive, not-breaking

#1133 feat: enable inactivity tracking for Starlight
  Cargo.lock
  chains/orchestrator-relays/runtime/starlight/Cargo.toml
  chains/orchestrator-relays/runtime/starlight/src/lib.rs
  chains/orchestrator-relays/runtime/starlight/src/tests/inactivity_tracking.rs
  chains/orchestrator-relays/runtime/starlight/src/tests/mod.rs
  chains/orchestrator-relays/runtime/starlight/src/tests/offline_marking.rs
  chains/orchestrator-relays/runtime/starlight/src/weights/mod.rs
  chains/orchestrator-relays/runtime/starlight/src/weights/pallet_inactivity_tracking.rs
  test/suites/smoke-test-common-solo/test-inactivity-tracking.ts
  typescript-api/src/starlight/interfaces/lookup.ts
  typescript-api/src/starlight/interfaces/registry.ts
  typescript-api/src/starlight/interfaces/types-lookup.ts
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, breaking, D3-trivial

#1193 Update to new prod URLs
  test/configs/dancebox-migration.yml
  test/configs/dancebox.yml
  test/configs/dancelight.yml
  test/configs/frontierContainer.yml
  test/moonwall.config.json
  test/scripts/unhashKey.ts
Labels: A8-mergeoncegreen, B0-silent, D2-notlive, not-breaking

#1195 fix: prevent inactivity tracking smoke test from running for Starlight runtimes before 1500
  test/helpers/starlightVersions.ts
  test/suites/dev-tanssi/inactivity-tracking/test-offline-marking.ts
  test/suites/smoke-test-common-solo/test-inactivity-tracking.ts
Labels: A8-mergeoncegreen, B0-silent, D2-notlive, not-breaking

#1183 [MD-1245] Smoke test to check decision deposit in the recent referenda proposals
  test/suites/smoke-test-common-solo/test-referenda.ts
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1191 Improve error handling for ETH tokens processor
  chains/orchestrator-relays/runtime/dancelight/src/bridge_to_ethereum_config.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/ethereum_token_transfers.rs
Labels: A8-mergeoncegreen, B0-silent, D5-nicetohaveaudit⚠️, not-breaking
