Repository moondance-labs/tanssi, pull requests merged in 2025-08, with the labels that each got.

#1200 First try at comparing apis
  .github/workflows/release.yml
  test/package.json
  test/scripts/compare-apis.ts
  test/scripts/fetchRuntimeApi.ts
  test/scripts/run-check-api-diff-job.sh
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking, dependency-upgrade

#1199 Network release automation
  scripts/run-release-workflows.sh
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1202 Refactor run_to_block to use helper in unit tests
  Cargo.lock
  chains/xcm-integration-tests/emulated/tests/assets/dancebox/src/tests/core_buyer_common.rs
  pallets/authority-assignment/src/mock.rs
  pallets/collator-assignment/src/mock.rs
  pallets/configuration/src/mock.rs
  pallets/ethereum-token-transfers/src/mock.rs
  pallets/external-validator-slashes/src/mock.rs
  pallets/external-validator-slashes/src/tests.rs
  pallets/external-validators-rewards/src/mock.rs
  pallets/external-validators/src/mock.rs
  pallets/inactivity-tracking/src/mock.rs
  pallets/inactivity-tracking/src/tests/inactivity_tracking.rs
  pallets/inactivity-tracking/src/tests/offline_marking.rs
  pallets/inflation-rewards/src/mock.rs
  pallets/inflation-rewards/src/tests.rs
  pallets/invulnerables/src/mock.rs
  pallets/invulnerables/src/tests.rs
  pallets/pooled-staking/src/mock.rs
  pallets/pooled-staking/src/tests/delegator_flow.rs
  pallets/pooled-staking/src/tests/mod.rs
  pallets/pooled-staking/src/tests/rewards.rs
  pallets/registrar/Cargo.toml
  pallets/registrar/src/mock.rs
  pallets/registrar/src/tests.rs
  pallets/stream-payment/src/mock.rs
  pallets/stream-payment/src/tests.rs
  pallets/xcm-core-buyer/src/mock.rs
Labels: A8-mergeoncegreen, B0-silent, D2-notlive, not-breaking

#1198 Run specific zombienet tests on schedule
  .github/workflow-templates/zombienet-tests/action.yml
  .github/workflows/merge-when-ready.yml
  .github/workflows/run-zombienet-tests.yml
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1205 Use Storage::set instead of if let Some
  chains/orchestrator-paras/runtime/dancebox/src/xcm_config.rs
  pallets/services-payment/src/lib.rs
  pallets/xcm-core-buyer/src/lib.rs
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1212 Flashbox smoke fix for inflation rewards
  test/suites/smoke-test-common-parachain/test-inflation-rewards.ts
  test/suites/smoke-test-common-solo/test-inflation-rewards.ts
  test/utils/constants.ts
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1222 Update URL for Dancebox metadata
  typescript-api/package.json
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1223 Chains Log Alerting Rules
  test/chain-log-alerts/README.md
  test/chain-log-alerts/log-rules.json
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking
