Repository moondance-labs/tanssi, pull requests merged in 2025-10, with the labels that each got.

#1305 Make `RelayNetwork` param configurable through pallet parameters
  Cargo.lock
  chains/container-chains/runtime-templates/frontier/src/lib.rs
  chains/container-chains/runtime-templates/frontier/src/xcm_config.rs
  chains/container-chains/runtime-templates/simple/Cargo.toml
  chains/container-chains/runtime-templates/simple/src/lib.rs
  chains/container-chains/runtime-templates/simple/src/weights/mod.rs
  chains/container-chains/runtime-templates/simple/src/weights/pallet_parameters.rs
  chains/container-chains/runtime-templates/simple/src/xcm_config.rs
  test/suites/common-container-chains/dynamic-params/test-relay-network.ts
  test/suites/dev-frontier-template/test-contract/test-contract-deploy-filter.ts
  test/utils/constants.ts
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, breaking, D5-nicetohaveaudit⚠️

#1314 Update frontier template rpc for upgrade tests
  test/configs/frontierContainer.yml
  test/scripts/fetchRuntimeApi.ts
  test/scripts/unhashKey.ts
Labels: A8-mergeoncegreen, B0-silent, D2-notlive, not-breaking

#1319 Wait for first assignment for db_cleanup
  client/service-container-chain-spawner/src/spawner.rs
  test/suites/zombie_tanssi_keep_db/test_zombie_tanssi_keep_db.ts
  test/utils/dir-canary.ts
  test/utils/index.ts
Labels: A8-mergeoncegreen, B5-clientnoteworthy, breaking, D3-trivial
