Repository moondance-labs/tanssi, pull requests merged in 2025-05, with the labels that each got.

#1003 Expand multisig pallet typescript test
  test/suites/common-all/pallet-multisig/test_pallet_multisig.ts
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#980 Benchmark missing pallets
  Cargo.lock
  Cargo.toml
  chains/orchestrator-relays/runtime/dancelight/Cargo.toml
  chains/orchestrator-relays/runtime/dancelight/src/lib.rs
  chains/orchestrator-relays/runtime/dancelight/src/weights/mod.rs
  chains/orchestrator-relays/runtime/dancelight/src/weights/pallet_session.rs
  chains/orchestrator-relays/runtime/dancelight/src/weights/runtime_parachains_disputes_slashing.rs
  chains/orchestrator-relays/runtime/starlight/Cargo.toml
  chains/orchestrator-relays/runtime/starlight/src/lib.rs
  chains/orchestrator-relays/runtime/starlight/src/weights/mod.rs
  chains/orchestrator-relays/runtime/starlight/src/weights/pallet_session.rs
  chains/orchestrator-relays/runtime/starlight/src/weights/runtime_parachains_disputes_slashing.rs
  pallets/alt-benchmarks/Cargo.toml
  pallets/alt-benchmarks/src/bench_parachains_slashing.rs
  pallets/alt-benchmarks/src/lib.rs
Labels: a0-pleasereview, A8-mergeoncegreen, B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#1012 point to new bounded limits in container chain genesis data
  Cargo.lock
  typescript-api/src/dancebox/interfaces/lookup.ts
  typescript-api/src/dancebox/interfaces/types-lookup.ts
  typescript-api/src/dancelight/interfaces/lookup.ts
  typescript-api/src/dancelight/interfaces/types-lookup.ts
  typescript-api/src/flashbox/interfaces/lookup.ts
  typescript-api/src/flashbox/interfaces/types-lookup.ts
Labels: A8-mergeoncegreen, B5-clientnoteworthy, D3-trivial, not-breaking

#1008 Enable pallets for starlight runtime 1301
  chains/orchestrator-relays/runtime/starlight/src/lib.rs
  chains/orchestrator-relays/runtime/starlight/src/tests/test_disabled_extrinsics.rs
  test/suites/dev-tanssi-relay/proxy/test-proxy-registrar.ts
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, breaking, D3-trivial

#1015 Install locked twiggy version
  .github/workflows/release.yml
Labels: A8-mergeoncegreen, B0-silent, ci, D2-notlive, not-breaking

#1017 Change inflation values for mainnet
  chains/orchestrator-relays/runtime/starlight/src/lib.rs
  chains/orchestrator-relays/runtime/starlight/src/tests/inflation_rates.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, breaking, D5-nicetohaveaudit⚠️

#1013 Upgrade node version to 0.14.0 and runtime to 1400
  Cargo.lock
  chains/container-chains/nodes/frontier/Cargo.toml
  chains/container-chains/nodes/simple/Cargo.toml
  chains/container-chains/runtime-templates/frontier/src/lib.rs
  chains/container-chains/runtime-templates/simple/src/lib.rs
  chains/orchestrator-paras/node/Cargo.toml
  chains/orchestrator-paras/runtime/dancebox/src/lib.rs
  chains/orchestrator-paras/runtime/flashbox/src/lib.rs
  chains/orchestrator-relays/client/cli/Cargo.toml
  chains/orchestrator-relays/node/tanssi-relay-service/Cargo.toml
  chains/orchestrator-relays/node/tanssi-relay/Cargo.toml
  chains/orchestrator-relays/runtime/dancelight/src/lib.rs
  chains/orchestrator-relays/runtime/starlight/src/lib.rs
  chains/orchestrator-relays/runtime/starlight/src/tests/test_disabled_extrinsics.rs
  client/service-container-chain/Cargo.toml
  test/helpers/starlightVersions.ts
  test/suites/dev-tanssi-relay/ethereum-token-transfers/test_transfer_native_token.ts
  test/suites/dev-tanssi-relay/proxy/test-proxy-registrar.ts
Labels: A8-mergeoncegreen, B0-silent, D2-notlive, not-breaking

#997 Enabled GasLimitStorageGrowthRatio
  Cargo.lock
  chains/container-chains/runtime-templates/frontier/src/lib.rs
  chains/container-chains/runtime-templates/frontier/src/precompiles.rs
  test/contracts/solidity/Fibonacci.sol
  test/contracts/solidity/StorageLoop.sol
  test/suites/dev-frontier-template/test-precompiles/test-precompile-proxy.ts
  test/suites/dev-frontier-template/test-storage-growth/test-block-storage-growth.ts
  test/suites/dev-frontier-template/test-storage-growth/test-evm-create-storage-growth.ts
  test/suites/dev-frontier-template/test-storage-growth/test-evm-store-storage-growth.ts
  test/suites/dev-frontier-template/test-storage-growth/test-precompile-storage-growth.ts
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1022 [MD-1109] Missing API-s for starlight
  chains/orchestrator-relays/runtime/starlight/src/lib.rs
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1025 [MD-1111] Added typescript API for starlight
  typescript-api/package.json
  typescript-api/scripts/runtime-upgrade.ts
  typescript-api/src/starlight/index.ts
  typescript-api/src/starlight/interfaces/augment-types.ts
  typescript-api/src/starlight/interfaces/index.ts
  typescript-api/src/starlight/interfaces/lookup.ts
  typescript-api/src/starlight/interfaces/registry.ts
  typescript-api/src/starlight/interfaces/types-lookup.ts
  typescript-api/src/starlight/interfaces/types.ts
  typescript-api/src/starlight/tsconfig.json
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1024 [Ledger support] Adds hash metadata
  .github/workflows/cmd.yml
  .github/workflows/coverage.yml
  .github/workflows/merge-when-ready.yml
  .github/workflows/publish-runtime.yml
  .github/workflows/release.yml
  Cargo.lock
  chains/container-chains/runtime-templates/frontier/Cargo.toml
  chains/container-chains/runtime-templates/simple/Cargo.toml
  chains/orchestrator-paras/runtime/dancebox/Cargo.toml
  chains/orchestrator-paras/runtime/flashbox/Cargo.toml
  chains/orchestrator-relays/client/cli/Cargo.toml
  chains/orchestrator-relays/node/tanssi-relay-service/Cargo.toml
  chains/orchestrator-relays/node/tanssi-relay-service/src/chain_spec.rs
  chains/orchestrator-relays/node/tanssi-relay/Cargo.toml
  chains/orchestrator-relays/runtime/dancelight/Cargo.toml
  chains/orchestrator-relays/runtime/dancelight/build.rs
  chains/orchestrator-relays/runtime/starlight/Cargo.toml
  chains/orchestrator-relays/runtime/starlight/build.rs
  pnpm-lock.yaml
  scripts/build-runtime-srtool.sh
  test/package.json
  test/suites/dev-tanssi-relay/metadata-hash/test-transaction-metadata.ts
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, breaking, C7-high, D5-nicetohaveaudit⚠️

#1030 Add starlight weights tmp folder
  tools/benchmark-all-runtimes.sh
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1028 [MD-1112] Tx fees & tips go to protocol treasury on all runtimes
  chains/orchestrator-paras/node/src/chain_spec/dancebox.rs
  chains/orchestrator-paras/node/src/chain_spec/flashbox.rs
  chains/orchestrator-paras/runtime/common/src/lib.rs
  chains/orchestrator-paras/runtime/dancebox/src/lib.rs
  chains/orchestrator-paras/runtime/flashbox/src/lib.rs
  chains/orchestrator-relays/runtime/dancelight/src/genesis_config_presets.rs
  chains/orchestrator-relays/runtime/dancelight/src/lib.rs
  chains/orchestrator-relays/runtime/starlight/src/genesis_config_presets.rs
  chains/orchestrator-relays/runtime/starlight/src/lib.rs
  test/suites/common-tanssi-parachain/pallet-treasury/test_pallet_treasury.ts
  test/suites/common-tanssi/fees/test_fee_burning.ts
  test/suites/common-tanssi/pallet-treasury/test_pallet_treasury.ts
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, breaking, C7-high, D9-needsaudit👮

#1032 [MD-1120] Smoke tests for the treasury all runtimes
  test/suites/common-tanssi/pallet-treasury/test_pallet_treasury.ts
  test/suites/smoke-test-common-all/test-fee-treasury.ts
  test/utils/account.ts
  test/utils/constants.ts
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1026 Update polkadot js to 15.10.2
  package.json
  pnpm-lock.yaml
  test/package.json
  typescript-api/scripts/runtime-upgrade.ts
  typescript-api/src/dancebox/interfaces/augment-api-query.ts
  typescript-api/src/dancebox/interfaces/augment-api-runtime.ts
  typescript-api/src/dancebox/interfaces/augment-types.ts
  typescript-api/src/dancelight/interfaces/augment-api-query.ts
  typescript-api/src/dancelight/interfaces/augment-api-runtime.ts
  typescript-api/src/dancelight/interfaces/augment-types.ts
  typescript-api/src/flashbox/interfaces/augment-types.ts
  typescript-api/src/starlight/interfaces/augment-types.ts
Labels: A8-mergeoncegreen, B0-silent, D2-notlive, not-breaking

#1036 add new smoke tests dancelight
  test/suites/smoke-test-dancelight/test-invulnerables-priority.ts
  test/suites/smoke-test-dancelight/test-randomness-consistency.ts
  test/suites/smoke-test-dancelight/test-staking-consistency.ts
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1035 [MD-1043] Benchmarks testing for all runtimes using CI server
  .github/workflow-templates/gh-cli/action.yml
  .github/workflows/cmd.yml
  .github/workflows/test-all-benchmarks-schedule.yml
  tools/benchmark-all-runtimes.sh
  tools/benchmarking.sh
  tools/show-me-the-weights.py
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1020 Allow PooledStaking extrinsics in starlight 1400
  chains/orchestrator-relays/runtime/starlight/src/lib.rs
  chains/orchestrator-relays/runtime/starlight/src/tests/test_disabled_extrinsics.rs
  test/helpers/starlightVersions.ts
  test/suites/dev-tanssi-relay/staking/test_staking_rewards_balanced.ts
  test/suites/dev-tanssi-relay/staking/test_staking_rewards_non_balanced.ts
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, breaking, D3-trivial

#1011 Check inflation value on external validators reward
  test/suites/smoke-test-dancelight/test-external-validators-rewards.ts
  test/suites/smoke-test-dancelight/test-inflation-rewards.ts
  test/utils/constants.ts
Labels: a0-pleasereview, A8-mergeoncegreen, B0-silent, C1-low, D2-notlive, not-breaking

#1000 ban saturating_div
  Cargo.toml
  chains/container-chains/runtime-templates/frontier/src/lib.rs
  chains/container-chains/runtime-templates/simple/src/lib.rs
  chains/orchestrator-paras/runtime/dancebox/src/lib.rs
  clippy.toml
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1041 Add pallet_maintenance_mode to starlight
  Cargo.lock
  chains/container-chains/runtime-templates/frontier/src/lib.rs
  chains/container-chains/runtime-templates/simple/src/lib.rs
  chains/orchestrator-paras/runtime/dancebox/src/lib.rs
  chains/orchestrator-paras/runtime/flashbox/src/lib.rs
  chains/orchestrator-relays/runtime/dancelight/src/lib.rs
  chains/orchestrator-relays/runtime/starlight/Cargo.toml
  chains/orchestrator-relays/runtime/starlight/src/lib.rs
  test/suites/common-all/test-maintenance/test-maintenance-mode.ts
  typescript-api/src/starlight/interfaces/lookup.ts
  typescript-api/src/starlight/interfaces/registry.ts
  typescript-api/src/starlight/interfaces/types-lookup.ts
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, breaking, D3-trivial

#1047 [MD-1115] Add block range validation to eth_getLogs RPC
  Cargo.lock
  chains/container-chains/nodes/frontier/src/cli.rs
  chains/container-chains/nodes/frontier/src/command.rs
  chains/container-chains/nodes/frontier/src/rpc/eth.rs
  chains/container-chains/nodes/frontier/src/rpc/mod.rs
  chains/container-chains/nodes/frontier/src/service.rs
  test/suites/dev-frontier-template/test-eth-rpc/test-eth-rpc-log-filtering.ts
  test/types/rpc-response.type.ts
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1049 Benchmarking CI script fix
  .github/workflows/test-all-benchmarks-schedule.yml
  tools/benchmark-all-runtimes.sh
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1051 point to latest polkadot
  Cargo.lock
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, breaking, D5-nicetohaveaudit⚠️

#1050 [MD-1157] Enable Balances for Proxy calls for light chains
  chains/orchestrator-relays/runtime/dancelight/src/lib.rs
  chains/orchestrator-relays/runtime/starlight/src/lib.rs
  test/suites/common-all/proxy/test-proxy-balances.ts
  typescript-api/src/dancelight/interfaces/augment-api-tx.ts
  typescript-api/src/dancelight/interfaces/lookup.ts
  typescript-api/src/dancelight/interfaces/types-lookup.ts
  typescript-api/src/starlight/interfaces/lookup.ts
  typescript-api/src/starlight/interfaces/types-lookup.ts
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1059 Increment spec version to 1302 for light chains
  chains/orchestrator-relays/runtime/dancelight/src/lib.rs
  chains/orchestrator-relays/runtime/starlight/src/lib.rs
Labels: A8-mergeoncegreen, B0-silent, D3-trivial

#1062 add dancelight only and sarlight only to publish runtime
  .github/workflows/publish-runtime.yml
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking
