Repository moondance-labs/tanssi, pull requests merged in 2025-09, with the labels that each got.

#999 Enable eth foreign asset registration in starlight
  Cargo.lock
  chains/orchestrator-relays/runtime/starlight/Cargo.toml
  chains/orchestrator-relays/runtime/starlight/src/lib.rs
  chains/orchestrator-relays/runtime/starlight/src/tests/integration_test.rs
  chains/orchestrator-relays/runtime/starlight/src/weights/mod.rs
  chains/orchestrator-relays/runtime/starlight/src/weights/pallet_assets.rs
  chains/orchestrator-relays/runtime/starlight/src/weights/pallet_foreign_asset_creator.rs
  chains/orchestrator-relays/runtime/starlight/src/xcm_config.rs
  typescript-api/src/starlight/interfaces/augment-api-consts.ts
  typescript-api/src/starlight/interfaces/augment-api-errors.ts
  typescript-api/src/starlight/interfaces/augment-api-events.ts
  typescript-api/src/starlight/interfaces/augment-api-query.ts
  typescript-api/src/starlight/interfaces/augment-api-tx.ts
  typescript-api/src/starlight/interfaces/lookup.ts
  typescript-api/src/starlight/interfaces/registry.ts
  typescript-api/src/starlight/interfaces/types-lookup.ts
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, breaking, D5-nicetohaveaudit⚠️

#1126 Fix xcm foreign tokens config and use foreign token for benchmarks
  chains/orchestrator-relays/runtime/dancelight/src/lib.rs
  chains/orchestrator-relays/runtime/starlight/src/lib.rs
  chains/orchestrator-relays/runtime/starlight/src/weights/xcm/mod.rs
  chains/orchestrator-relays/runtime/starlight/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  chains/orchestrator-relays/runtime/starlight/src/xcm_config.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, D3-trivial, not-breaking

#1214 CI to detect unused dependencies + remove unused (Improves compilation time)
  .github/workflows/release.yml
  Cargo.lock
  chains/container-chains/nodes/frontier/Cargo.toml
  chains/container-chains/runtime-templates/frontier/Cargo.toml
  chains/container-chains/runtime-templates/simple/Cargo.toml
  chains/integration-tests/xcm/emulated/chains/templates/frontier-template/Cargo.toml
  chains/integration-tests/xcm/emulated/chains/templates/simple-template/Cargo.toml
  chains/integration-tests/xcm/emulated/common/Cargo.toml
  chains/orchestrator-paras/runtime/dancebox/Cargo.toml
  chains/orchestrator-paras/runtime/flashbox/Cargo.toml
  chains/orchestrator-relays/node/tanssi-relay-service/Cargo.toml
  chains/orchestrator-relays/node/tanssi-relay/Cargo.toml
  chains/orchestrator-relays/runtime/dancelight/Cargo.toml
  chains/orchestrator-relays/runtime/starlight/Cargo.toml
  chains/runtime-common/Cargo.toml
  client/consensus/Cargo.toml
  client/manual-randomness/Cargo.toml
  client/node-common/Cargo.toml
  client/orchestrator-chain-rpc-interface/Cargo.toml
  client/service-container-chain/Cargo.toml
  pallets/alt-benchmarks/Cargo.toml
  pallets/authority-assignment/Cargo.toml
  pallets/data-preservers/Cargo.toml
  pallets/ethereum-token-transfers/Cargo.toml
  pallets/inflation-rewards/Cargo.toml
  pallets/pooled-staking/Cargo.toml
  pallets/registrar/runtime-api/Cargo.toml
  pallets/stream-payment/Cargo.toml
  pallets/xcm-core-buyer/Cargo.toml
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1234 Fix for udeps if it is exists already.
  .github/workflows/release.yml
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1235 Bump CI actions
  .github/workflows/client-release-issue.yml
  .github/workflows/cmd.yml
  .github/workflows/coverage.yml
  .github/workflows/docker-runtime-draft.yml
  .github/workflows/merge-when-ready.yml
  .github/workflows/prepare-binary.yml
  .github/workflows/prepare-tanssi-relay-binary.yml
  .github/workflows/publish-binary-from-docker.yml
  .github/workflows/publish-binary-tanssi-solochain.yml
  .github/workflows/publish-binary.yml
  .github/workflows/publish-docker-runtime-containers.yml
  .github/workflows/publish-docker-runtime-tanssi-solochain.yml
  .github/workflows/publish-docker-runtime-tanssi.yml
  .github/workflows/publish-docker-tanssi-solochain.yml
  .github/workflows/publish-docker.yml
  .github/workflows/publish-runtime.yml
  .github/workflows/publish-typescript-api.yml
  .github/workflows/release.yml
  .github/workflows/run-zombienet-tests.yml
  .github/workflows/runtime-release-issue.yml
  .github/workflows/test-all-benchmarks-schedule.yml
  .github/workflows/upgrade-typescript-api.yml
  .github/workflows/version-bump.yml
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1100 [MD-1066] Container chain sending tokens to Ethereum
  Cargo.lock
  Cargo.toml
  README.md
  chains/container-chains/runtime-templates/frontier/Cargo.toml
  chains/container-chains/runtime-templates/frontier/src/lib.rs
  chains/container-chains/runtime-templates/frontier/src/xcm_config.rs
  chains/container-chains/runtime-templates/simple/Cargo.toml
  chains/container-chains/runtime-templates/simple/src/lib.rs
  chains/container-chains/runtime-templates/simple/src/xcm_config.rs
  chains/integration-tests/xcm/emulated/tests/assets/dancelight/Cargo.toml
  chains/integration-tests/xcm/emulated/tests/assets/dancelight/src/tests/container_chain_to_eth_transfer.rs
  chains/integration-tests/xcm/emulated/tests/assets/dancelight/src/tests/mod.rs
  chains/integration-tests/xcm/emulated/tests/assets/dancelight/src/tests/xcm_message_exporter.rs
  chains/orchestrator-relays/runtime/dancelight/src/weights/xcm/mod.rs
  chains/orchestrator-relays/runtime/dancelight/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  chains/orchestrator-relays/runtime/dancelight/src/xcm_config.rs
  docs/README.md
  docs/TRANSFER_CONTAINER_CHAIN_TOKEN_TO_ETHEREUM.MD
  docs/images/transfer_container_chain_token_to_eth.jpg
  primitives/bridge/src/container_token_to_ethereum_message_exporter.rs
  primitives/bridge/src/lib.rs
  primitives/bridge/src/snowbridge_outbound_token_transfer.rs
  primitives/container-chain/Cargo.toml
  primitives/container-chain/src/lib.rs
  primitives/container-chain/src/sovereign_paid_remote_exporter.rs
  test/helpers/starlightVersions.ts
  test/suites/common-container-chains/test-pallet-xcm-executor-utils/test-token-transfer-ethereum.ts
  test/suites/dev-tanssi-relay/inactivity-tracking/test-inactivity-tracking.ts
  test/suites/dev-tanssi-relay/xcm/test-export-errors-if-no-channel.ts
  test/suites/dev-tanssi-relay/xcm/test-export-errors-if-no-token-registration.ts
  test/suites/dev-tanssi-relay/xcm/test-export-expected--errors.ts
  test/suites/dev-tanssi-relay/xcm/test-export-message-faking-para-origin.ts
  test/suites/dev-tanssi-relay/xcm/test-export-message-from-para.ts
  test/suites/dev-tanssi-relay/xcm/test-export-without-sufficient-balance-sovereign.ts
  test/suites/zombie_tanssi_relay/test-token-transfer-ethereum.ts
  test/utils/block.ts
  test/utils/constants.ts
  test/utils/xcm.ts
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, D9-needsaudit👮, not-breaking

#1236 Remove the option_env from node version, we always know the version
  Cargo.lock
  chains/container-chains/nodes/frontier/src/command.rs
  chains/container-chains/nodes/simple/src/command.rs
  chains/orchestrator-paras/node/src/command.rs
  client/node-common/Cargo.toml
  client/node-common/build.rs
  client/node-common/src/command.rs
  scripts/bump-runtime-versions.sh
Labels: A8-mergeoncegreen, B5-clientnoteworthy, D3-trivial, not-breaking

#1240 [MD-1304] Fix benchmarks for the export_message function for the Relay exporter
  chains/orchestrator-relays/runtime/dancelight/src/lib.rs
  chains/orchestrator-relays/runtime/dancelight/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  primitives/bridge/src/container_token_to_ethereum_message_exporter.rs
  test/suites/dev-tanssi-relay/xcm/test-export-errors-if-no-channel.ts
  test/suites/dev-tanssi-relay/xcm/test-export-errors-if-no-token-registration.ts
  test/suites/dev-tanssi-relay/xcm/test-export-expected--errors.ts
  test/suites/dev-tanssi-relay/xcm/test-export-message-faking-para-origin.ts
  test/suites/dev-tanssi-relay/xcm/test-export-without-sufficient-balance-sovereign.ts
  tools/benchmarking.sh
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1241 not run chopsticks upgrade dancebox
  .github/workflows/release.yml
  test/configs/frontierContainer.yml
  test/scripts/fetchRuntimeApi.ts
  test/scripts/unhashKey.ts
  test/suites/zombie_tanssi_relay/test_receive_container_native_tokens_from_eth.ts
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1211 feat: collators offline marking cooldown
  Cargo.lock
  chains/integration-tests/dancebox-runtime-tests/src/tests/offline_marking.rs
  chains/orchestrator-paras/runtime/dancebox/src/lib.rs
  chains/orchestrator-relays/runtime/dancelight/src/lib.rs
  chains/orchestrator-relays/runtime/dancelight/src/tests/offline_marking.rs
  chains/orchestrator-relays/runtime/starlight/src/lib.rs
  chains/orchestrator-relays/runtime/starlight/src/tests/offline_marking.rs
  chains/runtime-common/Cargo.toml
  chains/runtime-common/src/migrations.rs
  pallets/inactivity-tracking/src/lib.rs
  pallets/inactivity-tracking/src/migrations.rs
  pallets/inactivity-tracking/src/mock.rs
  pallets/inactivity-tracking/src/tests/offline_marking.rs
  test/suites/dev-tanssi-relay/inactivity-tracking/test-offline-marking.ts
  test/suites/dev-tanssi/inactivity-tracking/test-offline-marking.ts
  typescript-api/src/dancebox/interfaces/augment-api-consts.ts
  typescript-api/src/dancebox/interfaces/augment-api-errors.ts
  typescript-api/src/dancebox/interfaces/augment-api-query.ts
  typescript-api/src/dancebox/interfaces/lookup.ts
  typescript-api/src/dancebox/interfaces/registry.ts
  typescript-api/src/dancebox/interfaces/types-lookup.ts
  typescript-api/src/dancelight/interfaces/augment-api-consts.ts
  typescript-api/src/dancelight/interfaces/augment-api-errors.ts
  typescript-api/src/dancelight/interfaces/augment-api-query.ts
  typescript-api/src/dancelight/interfaces/lookup.ts
  typescript-api/src/dancelight/interfaces/registry.ts
  typescript-api/src/dancelight/interfaces/types-lookup.ts
  typescript-api/src/starlight/interfaces/augment-api-consts.ts
  typescript-api/src/starlight/interfaces/augment-api-errors.ts
  typescript-api/src/starlight/interfaces/augment-api-query.ts
  typescript-api/src/starlight/interfaces/lookup.ts
  typescript-api/src/starlight/interfaces/registry.ts
  typescript-api/src/starlight/interfaces/types-lookup.ts
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, breaking, D5-nicetohaveaudit⚠️

#1246 Update polkadot-sdk commit in Cargo.lock to include chain stall fix
  Cargo.lock
Labels: A8-mergeoncegreen, B0-silent, D2-notlive, not-breaking

#1247 Dedup foreign assets bench config
  chains/orchestrator-relays/runtime/starlight/src/lib.rs
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1255 small fixes release script
  scripts/run-release-workflows.sh
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1229 Improve e2e tests for ETH bridge
  test/configs/zombie_tanssi_relay_eth_bridge.json
  test/moonwall.config.json
  test/suites/zombie_tanssi_relay_eth_bridge/test_zombie_tanssi_relay_eth_bridge.ts
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1270 Improve export fees handling
  Cargo.lock
  chains/container-chains/runtime-templates/frontier/src/xcm_config.rs
  chains/container-chains/runtime-templates/simple/src/xcm_config.rs
  chains/integration-tests/xcm/emulated/chains/relays/dancelight/src/genesis.rs
  chains/integration-tests/xcm/emulated/chains/relays/dancelight/src/lib.rs
  chains/integration-tests/xcm/emulated/networks/dancelight-system/src/lib.rs
  chains/integration-tests/xcm/emulated/tests/assets/dancelight/Cargo.toml
  chains/integration-tests/xcm/emulated/tests/assets/dancelight/src/tests/container_chain_to_eth_transfer.rs
  chains/orchestrator-relays/runtime/dancelight/src/xcm_config.rs
  chains/runtime-common/Cargo.toml
  chains/runtime-common/src/relay.rs
  primitives/container-chain/src/sovereign_paid_remote_exporter.rs
  test/suites/zombie_tanssi_relay/test-token-transfer-ethereum.ts
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, breaking, D5-nicetohaveaudit⚠️

#1282 Reverted implementation of `getLastSessionEndBlock` for dancebox runtime
  test/suites/smoke-test-dancebox/test-inactivity-tracking.ts
  test/utils/block.ts
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1271 Add github action to bump runtime and client versions
  .github/workflows/bump-runtime-versions.yml
Labels: A8-mergeoncegreen, B0-silent, D2-notlive, not-breaking

#1287 Fix bump-runtime-versions.yml
  .github/workflows/bump-runtime-versions.yml
Labels: A8-mergeoncegreen, B0-silent, D2-notlive, not-breaking

#1290 [MD-1339] Zombienet tests improvements
  test/suites/zombie_tanssi_relay/test_zombie_tanssi_relay.ts
  test/utils/block-production-monitor.ts
  test/utils/block.ts
  test/utils/zombie.ts
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1296 [MD-1320] Run Semgrep on schedule
  .github/workflows/semgrep.yml
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1285 change costs constants for rt api in dev tests
  test/suites/common-tanssi/services-payment/test_service_payment_removes_tank_money_and_burns.ts
  test/suites/common-tanssi/services-payment/test_service_payment_removes_tank_money_and_refunds.ts
  test/suites/common-tanssi/services-payment/test_services_payment_block_credit_buying_free_combined.ts
  test/suites/common-tanssi/services-payment/test_services_payment_collator_credit_buying_free_combined.ts
  test/suites/common-tanssi/services-payment/test_services_payment_no_free_credits.ts
  test/suites/dev-tanssi-relay/services-payment/test_services_payment_block_credits.ts
  test/suites/dev-tanssi-relay/services-payment/test_services_payment_collator_credits.ts
  test/suites/dev-tanssi-relay/services-payment/test_services_payment_cost_values.ts
  test/suites/dev-tanssi-relay/xcm/test-export-errors-if-no-channel.ts
  test/suites/dev-tanssi-relay/xcm/test-export-errors-if-no-token-registration.ts
  test/suites/dev-tanssi-relay/xcm/test-export-expected--errors.ts
  test/suites/dev-tanssi-relay/xcm/test-export-expected-errors.ts
  test/suites/dev-tanssi-relay/xcm/test-export-message-faking-para-origin.ts
  test/suites/dev-tanssi-relay/xcm/test-export-message-from-para.ts
  test/suites/dev-tanssi-relay/xcm/test-export-without-sufficient-balance-sovereign.ts
  test/suites/smoke-test-common-all/test-consistency-services-payment.ts
  test/suites/smoke-test-common-all/test-services-payment-costs.ts
  test/suites/smoke-test-common-solo/test-configuration-consistency.ts
  test/utils/index.ts
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking
